//---Tabla
var columsTable1 = [
  { title:"Tipo", field:'tipo',hozAlign:"left",width:200},
  { title:"Ruma", field:'ruma',hozAlign:"left",width:200},
  { title:"Fecha de primer ingreso a En Cancha", field:'primer_ingresoCancha',hozAlign:"left",width:200},
  { title:"Fecha de primer ingreso a Proceso", field:'primer_ingresoProceso',hozAlign:"left",width:200},
  { title:"Fecha de Terminación",  field:'fecha_terminacion',hozAlign:"left",width:200 },
  { title:"Cliente",  field:'cliente',hozAlign:"left",width:200 },
  { title:"Mina de procedencia",  field:'mina_procedencia',hozAlign:"left",width:200 },
  { title:"Peso Neto",  field:'peso_neto',hozAlign:"left",width:200 },
  { title:"Estatus",  field:'status',hozAlign:"left",width:200 },
  { title:"Fecha y hora",  field:'fecha_hora',hozAlign:"left",width:200 },
  { title:"Peso Faja (KG)",  field:'peso_faja',hozAlign:"center",width:200 },
  { title:"PH",  field:'ph',hozAlign:"center",width:200 },
  { title:"Densidad",  field:'densidad',hozAlign:"center",width:200 },
  { title:"% malla",  field:'malla',hozAlign:"center",width:200 },
  { title:"Sacos de cal",  field:'sacos_cal',hozAlign:"center",width:200 },
  { title:"Kg utilizados de bolas 2.5",  field:'kg_25',hozAlign:"center",width:200 },
  { title:"Kg utilizados de bolas 3.5",  field:'kg_35',hozAlign:"center",width:200 },
  { title:"kg total utilizados",  field:'kg_total',hozAlign:"center",width:200 },
  { title:"Capacidad actual por hora",  field:'capacidad_hora',hozAlign:"center",width:200 },
  { title:"Mineral",  field:'mineral',hozAlign:"left",width:200 },
  { title:"Proceso",  field:'proceso',hozAlign:"left",width:200 },
  { title:"Hora ",  field:'hora_flotacion',hozAlign:"right",width:200 },
  { title:"Kg de DOWFROTH 250 Asignados",  field:'kg_dowfroth_asignado',hozAlign:"center",width:250 },
  { title:"Kg de DOWFROTH 250 Usados",  field:'kg_dowfroth_usado',hozAlign:"center",width:250 },
  { title:"Kg de DOWFROTH 250 Sobrantes",  field:'kg_dowfroth_sobrantes',hozAlign:"center",width:250 },
  { title:"Kg de FLOCULANTE Asignados",  field:'kg_floculante_asignado',hozAlign:"center",width:250 },
  { title:"Kg de FLOCULANTE Usados",  field:'kg_floculante_usado',hozAlign:"center",width:250 },
  { title:"Kg de FLOCULANTE Sobrantes",  field:'kg_floculante_sobrantes',hozAlign:"center",width:250 },
  { title:"Kg de XANTATO Z-6 Asignados",  field:'kg_xantato_asignado',hozAlign:"center",width:250 },
  { title:"Kg de XANTATO Z-6 Usados",  field:'kg_xantato_usado',hozAlign:"center",width:250 },
  { title:"Kg de XANTATO Z-6 Sobrantes",  field:'kg_xantato_sobrantes',hozAlign:"center",width:250 },
  { title:"Kg de A-208 Asignados",  field:'kg_208_asignado',hozAlign:"center",width:250 },
  { title:"Kg de A-208 Usados",  field:'kg_208_usado',hozAlign:"center",width:250 },
  { title:"Kg de A-208 Sobrantes",  field:'kg_208_sobrantes',hozAlign:"center",width:250 },
  { title:"Kg de MIBC Asignados",  field:'kg_mibc_asignado',hozAlign:"center",width:250 },
  { title:"Kg de MIBC Usados",  field:'kg_mibc_usado',hozAlign:"center",width:250 },
  { title:"Kg de MIBC Sobrantes",  field:'kg_mibc_sobrantes',hozAlign:"center",width:250 },
  { title:"Kg de A-31 Asignados",  field:'kg_a31_asignado',hozAlign:"center",width:250 },
  { title:"Kg de A-31 Usados",  field:'kg_a31_usado',hozAlign:"center",width:250 },
  { title:"Kg de A-31 Sobrantes",  field:'kg_a31_sobrantes',hozAlign:"center",width:250 },
  { title:"Kg de A-404 Asignados",  field:'kg_a404_asignado',hozAlign:"center",width:250 },
  { title:"Kg de A-404 Usados",  field:'kg_a404_usado',hozAlign:"center",width:250 },
  { title:"Kg de A-404 Sobrantes",  field:'kg_a404_sobrantes',hozAlign:"center",width:250 },
  { title:"Kg de A-3418 Asignados",  field:'kg_a3418_asignado',hozAlign:"center",width:250 },
  { title:"Kg de A-3418 Usados",  field:'kg_a3418_usado',hozAlign:"center",width:250 },
  { title:"Kg de A-3418 Sobrantes",  field:'kg_a3418_sobrantes',hozAlign:"center",width:250 },
  { title:"Kg de SILICATO DE SODIO Asignados",  field:'kg_silicato_asignado',hozAlign:"center",width:250 },
  { title:"Kg de SILICATO DE SODIO Usados",  field:'kg_silicato_usado',hozAlign:"center",width:250 },
  { title:"Kg de SILICATO DE SODIO Sobrantes",  field:'kg_silicato_sobrantes',hozAlign:"center",width:250 },
  { title:"Kg de MIX-980 Asignados",  field:'kg_mix980_asignado',hozAlign:"center",width:250 },
  { title:"Kg de MIX-980 Usados",  field:'kg_mix980_usado',hozAlign:"center",width:250 },
  { title:"Kg de MIX-980 Sobrantes",  field:'kg_mix980_sobrantes',hozAlign:"center",width:250 },
  { title:"Kg de RC-215 Asignados",  field:'kg_rc215_asignado',hozAlign:"center",width:250 },
  { title:"Kg de RC-215 Usados",  field:'kg_rc215_usado',hozAlign:"center",width:250 },
  { title:"Kg de RC-215 Sobrantes",  field:'kg_rc215_sobrantes',hozAlign:"center",width:250 }, 
  { title:"Kg Otros usados Asignados",  field:'kg_otros_asignados',hozAlign:"center",width:250 },
  { title:"Kg Otros usados Usados",  field:'kg_otros_usado',hozAlign:"center",width:250 },
  { title:"Kg Otros usados Sobrantes",  field:'kg_otros_sobrantes',hozAlign:"center",width:250 },




];


var dataTable1 = [
  {
    ruma: "19", 
    fecha_ingreso : "06/09/2022",
		fecha_terminación : "06/09/2022",
		cliente : "CLiente Ejemplo",
		mina_procedencia : "MIna Central",
		peso_neto : "20",
		status : "EN proceso",
		fecha : "",
		peso_faja : "",
		ph : "",
		densidad : "",
		porcentaje_malla : "",
		sacos_cal : "",
		kg_25 : "",
		kg_35 : "",
		kg_utilizados : "",
		capacidad_hora : "",
		control : "",
		mineral : "",
		proceso : "",
		hora : "",
		kg_250 : "",
		kg_floculante : "",
		kg_xantato : "",
		kg_a208 : "",
		kg_mibc : "",
		kg_a31 : "",
		kg_a404 : "",
		kg_3418 : "",
		kg_silicato : "",
		kg_980 : "",
		kg_rc215 : "",
		kg_250 : "",
		kg_floculante : "",
		kg_xantatoz6 : "",
		kg_a208 : "",
		kg_mibcUsados : "",
		kg_a31Usados : "",
		kg_a404Usados : "",
		kg_3418Usados : "",
		kg_silicatoUsados : "",
		kg_980Usados : "",
		kg_rc215Usados : "",
		kg_otros : "",
  },
  {
    ruma: "", 
    fecha_ingreso : "",
		fecha_terminación : "",
		cliente : "",
		mina_procedencia : "",
		peso_neto : "",
		status : "",
		fecha : "06/09/2022",
		peso_faja : "36",
		ph : "6",
		densidad : "15",
		porcentaje_malla : "20",
		sacos_cal : "13",
		kg_25 : "25",
		kg_35 : "40",
		kg_utilizados : "65",
		capacidad_hora : "20",
		control : "Procso",
		mineral : "Cobre",
		proceso : "Proceso ejemplo",
		hora : "01:20:50",
		kg_250 : "",
		kg_floculante : "",
		kg_xantato : "",
		kg_a208 : "",
		kg_mibc : "",
		kg_a31 : "",
		kg_a404 : "",
		kg_3418 : "",
		kg_silicato : "",
		kg_980 : "",
		kg_rc215 : "",
		kg_250 : "",
		kg_floculante : "",
		kg_xantatoz6 : "",
		kg_a208 : "",
		kg_mibcUsados : "",
		kg_a31Usados : "",
		kg_a404Usados : "",
		kg_3418Usados : "",
		kg_silicatoUsados : "",
		kg_980Usados : "",
		kg_rc215Usados : "",
		kg_otros : "",
  },
  {
    ruma: "", 
    fecha_ingreso : "",
		fecha_terminación : "",
		cliente : "",
		mina_procedencia : "",
		peso_neto : "",
		status : "",
		fecha : "",
		peso_faja : "",
		ph : "",
		densidad : "",
		porcentaje_malla : "",
		sacos_cal : "",
		kg_25 : "",
		kg_35 : "",
		kg_utilizados : "",
		capacidad_hora : "",
		control : "",
		mineral : "",
		proceso : "",
		hora : "",

		kg_250 : "20",
		kg_floculante : "20",
		kg_xantato : "20",
		kg_a208 : "20",
		kg_mibc : "20",
		kg_a31 : "20",
		kg_a404 : "20",
		kg_3418 : "30",
		kg_silicato : "30",
		kg_980 : "30",
		kg_rc215 : "30",
		kg_250 : "30",
		kg_floculante : "30",
		kg_xantatoz6 : "30",
		kg_a208 : "30",
		kg_mibcUsados : "30",
		kg_a31Usados : "",
		kg_a404Usados : "78",
		kg_3418Usados : "78",
		kg_silicatoUsados : "78",
		kg_980Usados : "78",
		kg_rc215Usados : "78",
		kg_otros : "78",
  },
    {
    ruma: "22", 
    fecha_ingreso : "06/09/2022",
		fecha_terminación : "06/09/2022",
		cliente : "CLiente Ejemplo",
		mina_procedencia : "MIna Central",
		peso_neto : "20",
		status : "EN proceso",
		fecha : "",
		peso_faja : "",
		ph : "",
		densidad : "",
		porcentaje_malla : "",
		sacos_cal : "",
		kg_25 : "",
		kg_35 : "",
		kg_utilizados : "",
		capacidad_hora : "",
		control : "",
		mineral : "",
		proceso : "",
		hora : "",
		kg_250 : "",
		kg_floculante : "",
		kg_xantato : "",
		kg_a208 : "",
		kg_mibc : "",
		kg_a31 : "",
		kg_a404 : "",
		kg_3418 : "",
		kg_silicato : "",
		kg_980 : "",
		kg_rc215 : "",
		kg_250 : "",
		kg_floculante : "",
		kg_xantatoz6 : "",
		kg_a208 : "",
		kg_mibcUsados : "",
		kg_a31Usados : "",
		kg_a404Usados : "",
		kg_3418Usados : "",
		kg_silicatoUsados : "",
		kg_980Usados : "",
		kg_rc215Usados : "",
		kg_otros : "",
  },
  {
    ruma: "", 
    fecha_ingreso : "",
		fecha_terminación : "",
		cliente : "",
		mina_procedencia : "",
		peso_neto : "",
		status : "",
		fecha : "06/09/2022",
		peso_faja : "36",
		ph : "6",
		densidad : "15",
		porcentaje_malla : "20",
		sacos_cal : "13",
		kg_25 : "25",
		kg_35 : "40",
		kg_utilizados : "65",
		capacidad_hora : "20",
		control : "Procso",
		mineral : "Cobre",
		proceso : "Proceso ejemplo",
		hora : "01:20:50",
		kg_250 : "",
		kg_floculante : "",
		kg_xantato : "",
		kg_a208 : "",
		kg_mibc : "",
		kg_a31 : "",
		kg_a404 : "",
		kg_3418 : "",
		kg_silicato : "",
		kg_980 : "",
		kg_rc215 : "",
		kg_250 : "",
		kg_floculante : "",
		kg_xantatoz6 : "",
		kg_a208 : "",
		kg_mibcUsados : "",
		kg_a31Usados : "",
		kg_a404Usados : "",
		kg_3418Usados : "",
		kg_silicatoUsados : "",
		kg_980Usados : "",
		kg_rc215Usados : "",
		kg_otros : "",
  },
  {
    ruma: "", 
    fecha_ingreso : "",
		fecha_terminación : "",
		cliente : "",
		mina_procedencia : "",
		peso_neto : "",
		status : "",
		fecha : "",
		peso_faja : "",
		ph : "",
		densidad : "",
		porcentaje_malla : "",
		sacos_cal : "",
		kg_25 : "",
		kg_35 : "",
		kg_utilizados : "",
		capacidad_hora : "",
		control : "",
		mineral : "",
		proceso : "",
		hora : "",

		kg_250 : "20",
		kg_floculante : "20",
		kg_xantato : "20",
		kg_a208 : "20",
		kg_mibc : "20",
		kg_a31 : "20",
		kg_a404 : "20",
		kg_3418 : "30",
		kg_silicato : "30",
		kg_980 : "30",
		kg_rc215 : "30",
		kg_250 : "30",
		kg_floculante : "30",
		kg_xantatoz6 : "30",
		kg_a208 : "30",
		kg_mibcUsados : "30",
		kg_a31Usados : "",
		kg_a404Usados : "78",
		kg_3418Usados : "78",
		kg_silicatoUsados : "78",
		kg_980Usados : "78",
		kg_rc215Usados : "78",
		kg_otros : "78",
  },
    {
    ruma: "23", 
    fecha_ingreso : "06/09/2022",
		fecha_terminación : "06/09/2022",
		cliente : "CLiente Ejemplo",
		mina_procedencia : "MIna Central",
		peso_neto : "20",
		status : "EN proceso",
		fecha : "",
		peso_faja : "",
		ph : "",
		densidad : "",
		porcentaje_malla : "",
		sacos_cal : "",
		kg_25 : "",
		kg_35 : "",
		kg_utilizados : "",
		capacidad_hora : "",
		control : "",
		mineral : "",
		proceso : "",
		hora : "",
		kg_250 : "",
		kg_floculante : "",
		kg_xantato : "",
		kg_a208 : "",
		kg_mibc : "",
		kg_a31 : "",
		kg_a404 : "",
		kg_3418 : "",
		kg_silicato : "",
		kg_980 : "",
		kg_rc215 : "",
		kg_250 : "",
		kg_floculante : "",
		kg_xantatoz6 : "",
		kg_a208 : "",
		kg_mibcUsados : "",
		kg_a31Usados : "",
		kg_a404Usados : "",
		kg_3418Usados : "",
		kg_silicatoUsados : "",
		kg_980Usados : "",
		kg_rc215Usados : "",
		kg_otros : "",
  },
  {
    ruma: "", 
    fecha_ingreso : "",
		fecha_terminación : "",
		cliente : "",
		mina_procedencia : "",
		peso_neto : "",
		status : "",
		fecha : "06/09/2022",
		peso_faja : "36",
		ph : "6",
		densidad : "15",
		porcentaje_malla : "20",
		sacos_cal : "13",
		kg_25 : "25",
		kg_35 : "40",
		kg_utilizados : "65",
		capacidad_hora : "20",
		control : "Procso",
		mineral : "Cobre",
		proceso : "Proceso ejemplo",
		hora : "01:20:50",
		kg_250 : "",
		kg_floculante : "",
		kg_xantato : "",
		kg_a208 : "",
		kg_mibc : "",
		kg_a31 : "",
		kg_a404 : "",
		kg_3418 : "",
		kg_silicato : "",
		kg_980 : "",
		kg_rc215 : "",
		kg_250 : "",
		kg_floculante : "",
		kg_xantatoz6 : "",
		kg_a208 : "",
		kg_mibcUsados : "",
		kg_a31Usados : "",
		kg_a404Usados : "",
		kg_3418Usados : "",
		kg_silicatoUsados : "",
		kg_980Usados : "",
		kg_rc215Usados : "",
		kg_otros : "",
  },
  {
    ruma: "", 
    fecha_ingreso : "",
		fecha_terminación : "",
		cliente : "",
		mina_procedencia : "",
		peso_neto : "",
		status : "",
		fecha : "",
		peso_faja : "",
		ph : "",
		densidad : "",
		porcentaje_malla : "",
		sacos_cal : "",
		kg_25 : "",
		kg_35 : "",
		kg_utilizados : "",
		capacidad_hora : "",
		control : "",
		mineral : "",
		proceso : "",
		hora : "",

		kg_250 : "20",
		kg_floculante : "20",
		kg_xantato : "20",
		kg_a208 : "20",
		kg_mibc : "20",
		kg_a31 : "20",
		kg_a404 : "20",
		kg_3418 : "30",
		kg_silicato : "30",
		kg_980 : "30",
		kg_rc215 : "30",
		kg_250 : "30",
		kg_floculante : "30",
		kg_xantatoz6 : "30",
		kg_a208 : "30",
		kg_mibcUsados : "30",
		kg_a31Usados : "",
		kg_a404Usados : "78",
		kg_3418Usados : "78",
		kg_silicatoUsados : "78",
		kg_980Usados : "78",
		kg_rc215Usados : "78",
		kg_otros : "78",
  },
    {
    ruma: "25", 
    fecha_ingreso : "06/09/2022",
		fecha_terminación : "06/09/2022",
		cliente : "CLiente Ejemplo",
		mina_procedencia : "MIna Central",
		peso_neto : "20",
		status : "EN proceso",
		fecha : "",
		peso_faja : "",
		ph : "",
		densidad : "",
		porcentaje_malla : "",
		sacos_cal : "",
		kg_25 : "",
		kg_35 : "",
		kg_utilizados : "",
		capacidad_hora : "",
		control : "",
		mineral : "",
		proceso : "",
		hora : "",
		kg_250 : "",
		kg_floculante : "",
		kg_xantato : "",
		kg_a208 : "",
		kg_mibc : "",
		kg_a31 : "",
		kg_a404 : "",
		kg_3418 : "",
		kg_silicato : "",
		kg_980 : "",
		kg_rc215 : "",
		kg_250 : "",
		kg_floculante : "",
		kg_xantatoz6 : "",
		kg_a208 : "",
		kg_mibcUsados : "",
		kg_a31Usados : "",
		kg_a404Usados : "",
		kg_3418Usados : "",
		kg_silicatoUsados : "",
		kg_980Usados : "",
		kg_rc215Usados : "",
		kg_otros : "",
  },
  {
    ruma: "", 
    fecha_ingreso : "",
		fecha_terminación : "",
		cliente : "",
		mina_procedencia : "",
		peso_neto : "",
		status : "",
		fecha : "06/09/2022",
		peso_faja : "36",
		ph : "6",
		densidad : "15",
		porcentaje_malla : "20",
		sacos_cal : "13",
		kg_25 : "25",
		kg_35 : "40",
		kg_utilizados : "65",
		capacidad_hora : "20",
		control : "Procso",
		mineral : "Cobre",
		proceso : "Proceso ejemplo",
		hora : "01:20:50",
		kg_250 : "",
		kg_floculante : "",
		kg_xantato : "",
		kg_a208 : "",
		kg_mibc : "",
		kg_a31 : "",
		kg_a404 : "",
		kg_3418 : "",
		kg_silicato : "",
		kg_980 : "",
		kg_rc215 : "",
		kg_250 : "",
		kg_floculante : "",
		kg_xantatoz6 : "",
		kg_a208 : "",
		kg_mibcUsados : "",
		kg_a31Usados : "",
		kg_a404Usados : "",
		kg_3418Usados : "",
		kg_silicatoUsados : "",
		kg_980Usados : "",
		kg_rc215Usados : "",
		kg_otros : "",
  },
  {
    ruma: "", 
    fecha_ingreso : "",
		fecha_terminación : "",
		cliente : "",
		mina_procedencia : "",
		peso_neto : "",
		status : "",
		fecha : "",
		peso_faja : "",
		ph : "",
		densidad : "",
		porcentaje_malla : "",
		sacos_cal : "",
		kg_25 : "",
		kg_35 : "",
		kg_utilizados : "",
		capacidad_hora : "",
		control : "",
		mineral : "",
		proceso : "",
		hora : "",

		kg_250 : "20",
		kg_floculante : "20",
		kg_xantato : "20",
		kg_a208 : "20",
		kg_mibc : "20",
		kg_a31 : "20",
		kg_a404 : "20",
		kg_3418 : "30",
		kg_silicato : "30",
		kg_980 : "30",
		kg_rc215 : "30",
		kg_250 : "30",
		kg_floculante : "30",
		kg_xantatoz6 : "30",
		kg_a208 : "30",
		kg_mibcUsados : "30",
		kg_a31Usados : "",
		kg_a404Usados : "78",
		kg_3418Usados : "78",
		kg_silicatoUsados : "78",
		kg_980Usados : "78",
		kg_rc215Usados : "78",
		kg_otros : "78",
  },
    {
    ruma: "20", 
    fecha_ingreso : "06/09/2022",
		fecha_terminación : "06/09/2022",
		cliente : "CLiente Ejemplo",
		mina_procedencia : "MIna Central",
		peso_neto : "20",
		status : "EN proceso",
		fecha : "",
		peso_faja : "",
		ph : "",
		densidad : "",
		porcentaje_malla : "",
		sacos_cal : "",
		kg_25 : "",
		kg_35 : "",
		kg_utilizados : "",
		capacidad_hora : "",
		control : "",
		mineral : "",
		proceso : "",
		hora : "",
		kg_250 : "",
		kg_floculante : "",
		kg_xantato : "",
		kg_a208 : "",
		kg_mibc : "",
		kg_a31 : "",
		kg_a404 : "",
		kg_3418 : "",
		kg_silicato : "",
		kg_980 : "",
		kg_rc215 : "",
		kg_250 : "",
		kg_floculante : "",
		kg_xantatoz6 : "",
		kg_a208 : "",
		kg_mibcUsados : "",
		kg_a31Usados : "",
		kg_a404Usados : "",
		kg_3418Usados : "",
		kg_silicatoUsados : "",
		kg_980Usados : "",
		kg_rc215Usados : "",
		kg_otros : "",
  },
  {
    ruma: "", 
    fecha_ingreso : "",
		fecha_terminación : "",
		cliente : "",
		mina_procedencia : "",
		peso_neto : "",
		status : "",
		fecha : "06/09/2022",
		peso_faja : "36",
		ph : "6",
		densidad : "15",
		porcentaje_malla : "20",
		sacos_cal : "13",
		kg_25 : "25",
		kg_35 : "40",
		kg_utilizados : "65",
		capacidad_hora : "20",
		control : "Procso",
		mineral : "Cobre",
		proceso : "Proceso ejemplo",
		hora : "01:20:50",
		kg_250 : "",
		kg_floculante : "",
		kg_xantato : "",
		kg_a208 : "",
		kg_mibc : "",
		kg_a31 : "",
		kg_a404 : "",
		kg_3418 : "",
		kg_silicato : "",
		kg_980 : "",
		kg_rc215 : "",
		kg_250 : "",
		kg_floculante : "",
		kg_xantatoz6 : "",
		kg_a208 : "",
		kg_mibcUsados : "",
		kg_a31Usados : "",
		kg_a404Usados : "",
		kg_3418Usados : "",
		kg_silicatoUsados : "",
		kg_980Usados : "",
		kg_rc215Usados : "",
		kg_otros : "",
  },
  {
    ruma: "", 
    fecha_ingreso : "",
		fecha_terminación : "",
		cliente : "",
		mina_procedencia : "",
		peso_neto : "",
		status : "",
		fecha : "",
		peso_faja : "",
		ph : "",
		densidad : "",
		porcentaje_malla : "",
		sacos_cal : "",
		kg_25 : "",
		kg_35 : "",
		kg_utilizados : "",
		capacidad_hora : "",
		control : "",
		mineral : "",
		proceso : "",
		hora : "",

		kg_250 : "20",
		kg_floculante : "20",
		kg_xantato : "20",
		kg_a208 : "20",
		kg_mibc : "20",
		kg_a31 : "20",
		kg_a404 : "20",
		kg_3418 : "30",
		kg_silicato : "30",
		kg_980 : "30",
		kg_rc215 : "30",
		kg_250 : "30",
		kg_floculante : "30",
		kg_xantatoz6 : "30",
		kg_a208 : "30",
		kg_mibcUsados : "30",
		kg_a31Usados : "",
		kg_a404Usados : "78",
		kg_3418Usados : "78",
		kg_silicatoUsados : "78",
		kg_980Usados : "78",
		kg_rc215Usados : "78",
		kg_otros : "78",
  },
];




