// Datos demo para Reporte ENcuestas MOntaje

//-- Tabla 1 
var columsTable1 = [
  { title:"NO.", field:'no',hozAlign:"center",width:100},
  { title:"NOMRE DEL EQUIPO",  field:'nombre',hozAlign:"center",width:500 },
  { title:"NO. SERIE",  field:'serie',hozAlign:"center", width:200 },
  { title:"NO. MAC",  field:'mac',hozAlign:"center",width:200 },
  { title:"MODELO",  field:'modelo',hozAlign:"center",width:300 },
  { title:"MARCA", field:"marca", hozAlign:"center",width:400},
  { title:"TIPO", field:"tipo", hozAlign:"center",width:400},
  { title:"LUGAR", field:"lugar", hozAlign:"center",width:400},
  { title:"CONDICIÓN", field:"condicion", hozAlign:"center",width:300},
  { title:"TOTAL SALIDAS", field:"total_salidas", hozAlign:"center",width:200},
  { title:"TOTAL ENTRADAS", field:"total_entradas", hozAlign:"center",width:200},
  { title:"EXISTENCIAS", field:"existencias", hozAlign:"center",width:200},
];


var dataTable1 = [
  {
    no:"1",
    nombre:"Nombre Example",
    serie:"Serie Example",
    mac:"Mac Example",
    modelo:"Modelo",
    marca:"Marca Example",
    tipo:"Tipo Example",
    lugar:"Lugar Example",
    condicion:"COndición Example",
    total_salidas:"1000",
    total_entradas:"1000",
    existencias:"100",
  },
    {
    no:"1",
    nombre:"Nombre Example",
    serie:"Serie Example",
    mac:"Mac Example",
    modelo:"Modelo",
    marca:"Marca Example",
    tipo:"Tipo Example",
    lugar:"Lugar Example",
    condicion:"COndición Example",
    total_salidas:"1000",
    total_entradas:"1000",
    existencias:"100",
  },
    {
    no:"1",
    nombre:"Nombre Example",
    serie:"Serie Example",
    mac:"Mac Example",
    modelo:"Modelo",
    marca:"Marca Example",
    tipo:"Tipo Example",
    lugar:"Lugar Example",
    condicion:"COndición Example",
    total_salidas:"1000",
    total_entradas:"1000",
    existencias:"100",
  },
    {
    no:"1",
    nombre:"Nombre Example",
    serie:"Serie Example",
    mac:"Mac Example",
    modelo:"Modelo",
    marca:"Marca Example",
    tipo:"Tipo Example",
    lugar:"Lugar Example",
    condicion:"COndición Example",
    total_salidas:"1000",
    total_entradas:"1000",
    existencias:"100",
  },
    {
    no:"1",
    nombre:"Nombre Example",
    serie:"Serie Example",
    mac:"Mac Example",
    modelo:"Modelo",
    marca:"Marca Example",
    tipo:"Tipo Example",
    lugar:"Lugar Example",
    condicion:"COndición Example",
    total_salidas:"1000",
    total_entradas:"1000",
    existencias:"100",
  },
    {
    no:"1",
    nombre:"Nombre Example",
    serie:"Serie Example",
    mac:"Mac Example",
    modelo:"Modelo",
    marca:"Marca Example",
    tipo:"Tipo Example",
    lugar:"Lugar Example",
    condicion:"COndición Example",
    total_salidas:"1000",
    total_entradas:"1000",
    existencias:"100",
  },
    {
    no:"1",
    nombre:"Nombre Example",
    serie:"Serie Example",
    mac:"Mac Example",
    modelo:"Modelo",
    marca:"Marca Example",
    tipo:"Tipo Example",
    lugar:"Lugar Example",
    condicion:"COndición Example",
    total_salidas:"1000",
    total_entradas:"1000",
    existencias:"100",
  },
];

