version: '3.4'

services:
  servido:
    restart: "no"
    container_name: servido
    hostname: servido
    environment:
      - FLASK_APP=servido.py
    image: linkaform/servido:latest
    ports:
      - "8080:8080"
    volumes:
      - ../nginx/certs:/etc/nginx/certs
      - ../servido_api/certs:/srv/servido/servido_api/certs
    build:
     context: ../
     dockerfile: Dockerfile_Soter
     target: production
    command: /docker/run_soter
    stdin_open: true
    tty: true
