#!/bin/bash
# wget https://f001.backblazeb2.com/file/lkf-resources/lkf-models-0.1.tar.gz
# pip install lkf-models-0.1.tar.gz
# tar -xzvf lkf-models-0.1.tar.gz
# pip install ./lkf-models-0.1/
# pip install ./lkf-models-0.1/
echo '================================================='
echo "RUNNING on prodution server mode!!!!"
echo '================================================='
cd /srv/servido/
/bin/sh -c 'nginx && uwsgi --ini /etc/uwsgi/apps-enabled/servido.ini'
