#!/bin/bash


echo '================================================='
echo "RUNNING on prodution server mode!!!!"
echo "Servido WebApp and API comming to live . . ."
echo '================================================='
cd /srv/servido/
/bin/sh -c 'nginx && uwsgi --ini /etc/uwsgi/apps-enabled/servido.ini'
