#!/bin/bash


echo '================================================='
echo "RUNNING on prodution server mode!!!!"
echo "Servido WebApp and API comming to live . . ."
echo '================================================='
cd /srv/servido/
exec nginx -g "daemon off;"
