// Datos demo para Reporte Desempeno Jornales

//--Table Facturación
var columsTable1 = [
  { title:"Fecha", field:'fecha',hozAlign:"center",width:200},
  { title:"Mesa", field:'mesa', hozAlign:"right", width:300},
  { title:"Tipo Tarea" , field:'tipo_tarea', hozAlign:"center", width:260, },
  { title:"Nombre Funcionario" , field:'funcionario', hozAlign:"left", width:260, },
  { title:"Codigo " , field:'codigo', hozAlign:"center", width:260, },
  { title:"Personas en Mesa" , field:'personas_mesa', hozAlign:"right", width:260, },
  { title:"Cantidad Cajas" , field:'cantidad_cajas', hozAlign:"right", width:260, },
  { title:"Descripción Producto" , field:'desc_producto', hozAlign:"left", width:260, },
  { title:"Cantidad Funcionarias" , field:'cajas_funcionarias', hozAlign:"right", width:260, },
  { title:"Un X Caja" , field:'caja', hozAlign:"right", width:260, },
  { title:"Precio por Unidades", field:'precio_unidad',hozAlign:"right",width:200 ,formatter: "money",
    formatterParams: {symbol: "$", symbolAfter: "", decimal: ".", thousand: ",", precision: 2} },
  { title:"Tipo Promoción" , field:'tipo_promocion', hozAlign:"center", width:260, },
  { title:"Total Unidades" , field:'total_unidades', hozAlign:"right", width:260, },
  { title:"Total", field:'total',hozAlign:"right",width:200 ,formatter: "money",
  formatterParams: {symbol: "$", symbolAfter: "", decimal: ".", thousand: ",", precision: 2} },
];



//--Table Horas
var columsTable2 = [
  { title:"Fecha", field:'fecha',hozAlign:"center",width:200},
  { title:"Mesa", field:'mesa', hozAlign:"right", width:300},
  { title:"Cantidad Funcionario" , field:'cajas_funcionario', hozAlign:"right", width:260, },
  { title:"Cantidad de tiempo en minutos" , field:'cantidad_tiempo', hozAlign:"right", width:260, },
  { title:"Minutos / 60 Minutos" , field:'cantidad_minutos', hozAlign:"right", width:260, },
  { title:"Horas" ,field:'horas', hozAlign:"right", width:260, },
  { title:"Extras" ,field:'extras', hozAlign:"right", width:260, },
  { title:"Nocturna" ,field:'nocturna', hozAlign:"right", width:260, },
  { title:"Precio Unidad", field:'precio_unidad',hozAlign:"right",width:200 ,formatter: "money",
  formatterParams: {symbol: "$", symbolAfter: "", decimal: ".", thousand: ",", precision: 2} },
  { title:"Motivo" ,field:'motivo', hozAlign:"right", width:260, },
  { title:"Pago", field:'pago',hozAlign:"right",width:200 ,formatter: "money",
  formatterParams: {symbol: "$", symbolAfter: "", decimal: ".", thousand: ",", precision: 2} },
  { title:"TOtal en Horas" ,field:'total_horas', hozAlign:"right", width:260, },
];


var dataTable1 = [
  {
    fecha :"6/14/2022",
    mesa :"16",
    tipo_tarea :"EN7",
    funcionario :"YANINA DIAZ",
    codigo :"68704806",
    personas_mesa :"4",
    cantidad_cajas :"656",
    desc_producto :"SUAVE SH+AC BRILLO CERAM 4X930ML 50%DTO",
    cajas_funcionarias :"164",
    caja :"4",
    precio_unidad :"4.327",
    tipo_promocion :"EN7",
    total_unidades :"656",
    total :"2838.71",
  },
    {
    fecha :"6/14/2022",
    mesa :"16",
    tipo_tarea :"EN7",
    funcionario :"YANINA DIAZ",
    codigo :"68704806",
    personas_mesa :"4",
    cantidad_cajas :"656",
    desc_producto :"SUAVE SH+AC BRILLO CERAM 4X930ML 50%DTO",
    cajas_funcionarias :"164",
    caja :"4",
    precio_unidad :"4.327",
    tipo_promocion :"EN7",
    total_unidades :"656",
    total :"2838.71",
  },
  {
    fecha :"6/14/2022",
    mesa :"16",
    tipo_tarea :"EN7",
    funcionario :"YANINA DIAZ",
    codigo :"68704806",
    personas_mesa :"4",
    cantidad_cajas :"656",
    desc_producto :"SUAVE SH+AC BRILLO CERAM 4X930ML 50%DTO",
    cajas_funcionarias :"164",
    caja :"4",
    precio_unidad :"4.327",
    tipo_promocion :"EN7",
    total_unidades :"656",
    total :"2838.71",
  },
];

var dataTable2 = [
  {
    fecha:"6/1/2022",
    mesa:"12",
    cajas_funcionario:"4",
    cantidad_tiempo:"30",
    cantidad_minutos:"0",
    horas:"0.50",
    extras:"",
    nocturna:"",
    precio_unidad:"298",
    motivo:"Se revisan y etiquetan las ref 5723/5728 ",
    pago:"596",
    total_horas:"2",
  },
  {
    fecha:"6/1/2022",
    mesa:"12",
    cajas_funcionario:"4",
    cantidad_tiempo:"30",
    cantidad_minutos:"0",
    horas:"0.50",
    extras:"",
    nocturna:"",
    precio_unidad:"298",
    motivo:"Se revisan y etiquetan las ref 5723/5728 ",
    pago:"596",
    total_horas:"2",
  },
  {
    fecha:"6/1/2022",
    mesa:"12",
    cajas_funcionario:"4",
    cantidad_tiempo:"30",
    cantidad_minutos:"0",
    horas:"0.50",
    extras:"",
    nocturna:"",
    precio_unidad:"298",
    motivo:"Se revisan y etiquetan las ref 5723/5728 ",
    pago:"596",
    total_horas:"2",
  },
];