// Datos demo para Reporte Desempeno Jornales

//--Table Facturación
var columsTable1 = [
  { title:"Folio", field:'folio',hozAlign:"center",formatter:"link", formatterParams:{
    url:function(cell){return "https://app.linkaform.com/#/records/detail/" + cell.getData().record_id}, 
    target:"_blank",},width:200},
  { title:"Fecha", field:'fecha',hozAlign:"center",width:200},
  { title:"Mesa", field:'mesa', hozAlign:"right", width:100},
  { title:"Tipo Tarea" , field:'tarea', hozAlign:"center", width:150, },
  { title:"Nombre Funcionario" , field:'funcionario', hozAlign:"left", width:300, },
  { title:"Codigo " , field:'codigo', hozAlign:"center", width:150, },
  { title:"Personas en Mesa" , field:'personas_mesa', hozAlign:"right", width:100, },
  { title:"Cantidad Cajas" , field:'cantidad_cajas', hozAlign:"right", width:100, },
  { title:"Descripción Producto" , field:'producto', hozAlign:"left", width:300, },
  { title:"Cajas Funcionarias" , field:'cajas_funcionaria', hozAlign:"right", width:260, formatter: "money",
  formatterParams: {symbol: "", symbolAfter: "", decimal: ".", thousand: ",", precision: 2}},
  { title:"Un X Caja" , field:'cajas_unidad', hozAlign:"right", width:100, },
  { title:"Precio por Unidades", field:'precio_unidad',hozAlign:"right",width:100 ,formatter: "money",
    formatterParams: {symbol: "$", symbolAfter: "", decimal: ".", thousand: ",", precision: 2} },
  { title:"Tipo Promoción" , field:'promocion', hozAlign:"center", width:100, },
  { title:"Total Unidades" , field:'total_unidades', hozAlign:"right", width:200,formatter: "money",
  formatterParams: {symbol: "", symbolAfter: "", decimal: ".", thousand: ",", precision: 2},bottomCalc:"sum", bottomCalcParams:{
    precision:2,} ,bottomCalcFormatter: "money",bottomCalcFormatterParams:  {decimal: ".",thousand: ",",symbol: ""},},
  { title:"Total", field:'total',hozAlign:"right",width:200 ,formatter: "money",
  formatterParams: {symbol: "$", symbolAfter: "", decimal: ".", thousand: ",", precision: 2},bottomCalc:"sum", bottomCalcParams:{
    precision:2,} ,bottomCalcFormatter: "money",bottomCalcFormatterParams:  {decimal: ".",thousand: ",",symbol: "$"},},
];



//--Table Horas
var columsTable2 = [
  { title:"Folio", field:'folio',hozAlign:"center",formatter:"link", formatterParams:{
    url:function(cell){return "https://app.linkaform.com/#/records/detail/" + cell.getData().record_id}, 
    target:"_blank",},width:200},
  { title:"Fecha", field:'fecha',hozAlign:"center",width:200},
  { title:"Mesa", field:'mesa', hozAlign:"right", width:100},
  { title:"Cantidad Funcionarios" , field:'num_funcionarias', hozAlign:"right", width:100, },
  { title:"Cantidad de tiempo en minutos" , field:'cantidad_minutos', hozAlign:"right", width:100, },
  { title:"Minutos / 60 Minutos" , field:'cantidad_horas', hozAlign:"right", width:100, },
  { title:"Precio Unidad", field:'precio_unidad',hozAlign:"right",width:200 ,formatter: "money",
  formatterParams: {symbol: "$", symbolAfter: "", decimal: ".", thousand: ",", precision: 2} },
  { title:"Motivo" ,field:'motivo', hozAlign:"right", width:400, },
  { title:"Pago", field:'pago',hozAlign:"right",width:200 ,formatter: "money",
  formatterParams: {symbol: "$", symbolAfter: "", decimal: ".", thousand: ",", precision: 2},bottomCalc:"sum", bottomCalcParams:{
    precision:2,} ,bottomCalcFormatter: "money",bottomCalcFormatterParams:  {decimal: ".",thousand: ",",symbol: "$"}, },
  { title:"Total en Horas" ,field:'total_horas', hozAlign:"right", width:150,bottomCalc:"sum", bottomCalcParams:{
    precision:2,}  },
];


var dataTable1 = [
  {
    folio :"19-589",
    record_id :"589",
    fecha :"6/14/2022",
    mesa :"16",
    tipo_tarea :"EN7",
    funcionario :"YANINA DIAZ",
    codigo :"68704806",
    personas_mesa :"4",
    cantidad_cajas :"656",
    desc_producto :"SUAVE SH+AC BRILLO CERAM 4X930ML 50%DTO",
    cajas_funcionarias :"164",
    caja :"4",
    precio_unidad :"4.327",
    tipo_promocion :"EN7",
    total_unidades :"656",
    total :"2838.71",
  },
    {
    folio :"19-589",
    record_id :"589",
    fecha :"6/14/2022",
    mesa :"16",
    tipo_tarea :"EN7",
    funcionario :"YANINA DIAZ",
    codigo :"68704806",
    personas_mesa :"4",
    cantidad_cajas :"656",
    desc_producto :"SUAVE SH+AC BRILLO CERAM 4X930ML 50%DTO",
    cajas_funcionarias :"164",
    caja :"4",
    precio_unidad :"4.327",
    tipo_promocion :"EN7",
    total_unidades :"656",
    total :"2838.71",
  },
  {
    folio :"19-589",
    record_id :"589",
    fecha :"6/14/2022",
    mesa :"16",
    tipo_tarea :"EN7",
    funcionario :"YANINA DIAZ",
    codigo :"68704806",
    personas_mesa :"4",
    cantidad_cajas :"656",
    desc_producto :"SUAVE SH+AC BRILLO CERAM 4X930ML 50%DTO",
    cajas_funcionarias :"164",
    caja :"4",
    precio_unidad :"4.327",
    tipo_promocion :"EN7",
    total_unidades :"656",
    total :"2838.71",
  },
];

var dataTable2 = [
  {
    folio :"19-589",
    record_id :"589",
    fecha:"6/1/2022",
    mesa:"12",
    cajas_funcionario:"4",
    cantidad_tiempo:"30",
    cantidad_minutos:"0",
    horas:"0.50",
    extras:"",
    nocturna:"",
    precio_unidad:"298",
    motivo:"Se revisan y etiquetan las ref 5723/5728 ",
    pago:"596",
    total_horas:"2",
  },
  {
    folio :"19-589",
    record_id :"589",
    fecha:"6/1/2022",
    mesa:"12",
    cajas_funcionario:"4",
    cantidad_tiempo:"30",
    cantidad_minutos:"0",
    horas:"0.50",
    extras:"",
    nocturna:"",
    precio_unidad:"298",
    motivo:"Se revisan y etiquetan las ref 5723/5728 ",
    pago:"596",
    total_horas:"2",
  },
  {
    folio :"19-589",
    record_id :"589",
    fecha:"6/1/2022",
    mesa:"12",
    cajas_funcionario:"4",
    cantidad_tiempo:"30",
    cantidad_minutos:"0",
    horas:"0.50",
    extras:"",
    nocturna:"",
    precio_unidad:"298",
    motivo:"Se revisan y etiquetan las ref 5723/5728 ",
    pago:"596",
    total_horas:"2",
  },
];