// Datos demo 
var array_background = getPAlleteColors(10,12);
console.log(array_background)

//--Table 
var columsTable1 = [
  { title:"Folio", field:'folio', hozAlign:"left", formatter:"link", formatterParams:{
  url:function(cell){return "https://app.linkaform.com/#/records/detail/" + cell.getData().record_id}, 
  target:"_blank",}, width:150},
  { title:"Numero Equipo", field:'numero_equipo',hozAlign:"left",width:150},
  { title:"Estatus Equipo", field:'status_equipo',hozAlign:"left",width:250},
  { title:"Acción Realizada", field:'acción_realizada',hozAlign:"left",width:250},
  { title:"Rata Noruega", field:'rata_noruega',hozAlign:"right",width:150},
  { title:"Rata Dejado", field:'rata_tejado',hozAlign:"right",width:150},
  { title:"Raton Domestico", field:'raton_domestico',hozAlign:"right",width:150},
  { title:"Raton Campo", field:'raton_campo',hozAlign:"right",width:150},
  { title:"Cucaracha Alemana", field:'cucaracha_alemana',hozAlign:"right",width:150},
  { title:"Cucaracha Americana", field:'cucaracha_americana',hozAlign:"right",width:150},
  { title:"Hormiga", field:'hormiga',hozAlign:"right",width:150},
  { title:"Tijerilla", field:'tijerilla',hozAlign:"right",width:150},
  { title:"Grillo", field:'grillo',hozAlign:"right",width:150},
  { title:"Pulga", field:'pulga',hozAlign:"right",width:150},
  { title:"Gorgojo", field:'gorgojo',hozAlign:"right",width:150},
  { title:"Escarabajo", field:'escarabajo',hozAlign:"right",width:150},
  { title:"Otra Plaga", field:'otra_plaga',hozAlign:"right",width:150},

  { title:"Descripción", field:'descripcion',hozAlign:"left",width:250},
  { title:"Realizada", field:'realizada',hozAlign:"left",width:250},
];



//---CONFIG DATA TABLE
var dataTable1 = [
  {
    "folio": '0001-369',
    "numero_equipo": '11598753214',
    "status_equipo": 'Optimo',
    "acción_realizada": 'Limpieza y monitoreo',
    "rata_noruega": '1',
    "rata_tejado": '3',
    "raton_domestico": '5',
    "raton_campo": '8',
    "cucaracha_alemana": '7',
    "cucaracha_americana": '2',
    "hormiga": '1',
    "tijerilla": '0',
    "grillo": '0',
    "pulga": '0',
    "gorgojo": '5',
    "escarabajo": '3',
    "otra_plaga": '8',
    "descripcion": 'Otro',
    "realizada": 'Gerardo Fernández',
  },
    {
    "folio": '0001-369',
    "numero_equipo": '11598753214',
    "status_equipo": 'Optimo',
    "acción_realizada": 'Limpieza y monitoreo',
    "rata_noruega": '1',
    "rata_tejado": '3',
    "raton_domestico": '5',
    "raton_campo": '8',
    "cucaracha_alemana": '7',
    "cucaracha_americana": '2',
    "hormiga": '1',
    "tijerilla": '0',
    "grillo": '0',
    "pulga": '0',
    "gorgojo": '5',
    "escarabajo": '3',
    "otra_plaga": '8',
    "descripcion": 'Otro',
    "realizada": 'Gerardo Fernández',
  },
  {
    "folio": '0001-369',
    "numero_equipo": '11598753214',
    "status_equipo": 'Optimo',
    "acción_realizada": 'Limpieza y monitoreo',
    "rata_noruega": '1',
    "rata_tejado": '3',
    "raton_domestico": '5',
    "raton_campo": '8',
    "cucaracha_alemana": '7',
    "cucaracha_americana": '2',
    "hormiga": '1',
    "tijerilla": '0',
    "grillo": '0',
    "pulga": '0',
    "gorgojo": '5',
    "escarabajo": '3',
    "otra_plaga": '8',
    "descripcion": 'Otro',
    "realizada": 'Gerardo Fernández',
  },
  {
    "folio": '0001-369',
    "numero_equipo": '11598753214',
    "status_equipo": 'Optimo',
    "acción_realizada": 'Limpieza y monitoreo',
    "rata_noruega": '1',
    "rata_tejado": '3',
    "raton_domestico": '5',
    "raton_campo": '8',
    "cucaracha_alemana": '7',
    "cucaracha_americana": '2',
    "hormiga": '1',
    "tijerilla": '0',
    "grillo": '0',
    "pulga": '0',
    "gorgojo": '5',
    "escarabajo": '3',
    "otra_plaga": '8',
    "descripcion": 'Otro',
    "realizada": 'Gerardo Fernández',
  },
  {
    "folio": '0001-369',
    "numero_equipo": '11598753214',
    "status_equipo": 'Optimo',
    "acción_realizada": 'Limpieza y monitoreo',
    "rata_noruega": '1',
    "rata_tejado": '3',
    "raton_domestico": '5',
    "raton_campo": '8',
    "cucaracha_alemana": '7',
    "cucaracha_americana": '2',
    "hormiga": '1',
    "tijerilla": '0',
    "grillo": '0',
    "pulga": '0',
    "gorgojo": '5',
    "escarabajo": '3',
    "otra_plaga": '8',
    "descripcion": 'Otro',
    "realizada": 'Gerardo Fernández',
  },
  {
    "folio": '0001-369',
    "numero_equipo": '11598753214',
    "status_equipo": 'Optimo',
    "acción_realizada": 'Limpieza y monitoreo',
    "rata_noruega": '1',
    "rata_tejado": '3',
    "raton_domestico": '5',
    "raton_campo": '8',
    "cucaracha_alemana": '7',
    "cucaracha_americana": '2',
    "hormiga": '1',
    "tijerilla": '0',
    "grillo": '0',
    "pulga": '0',
    "gorgojo": '5',
    "escarabajo": '3',
    "otra_plaga": '8',
    "descripcion": 'Otro',
    "realizada": 'Gerardo Fernández',
  },
  {
    "folio": '0001-369',
    "numero_equipo": '11598753214',
    "status_equipo": 'Optimo',
    "acción_realizada": 'Limpieza y monitoreo',
    "rata_noruega": '1',
    "rata_tejado": '3',
    "raton_domestico": '5',
    "raton_campo": '8',
    "cucaracha_alemana": '7',
    "cucaracha_americana": '2',
    "hormiga": '1',
    "tijerilla": '0',
    "grillo": '0',
    "pulga": '0',
    "gorgojo": '5',
    "escarabajo": '3',
    "otra_plaga": '8',
    "descripcion": 'Otro',
    "realizada": 'Gerardo Fernández',
  },
  {
    "folio": '0001-369',
    "numero_equipo": '11598753214',
    "status_equipo": 'Optimo',
    "acción_realizada": 'Limpieza y monitoreo',
    "rata_noruega": '1',
    "rata_tejado": '3',
    "raton_domestico": '5',
    "raton_campo": '8',
    "cucaracha_alemana": '7',
    "cucaracha_americana": '2',
    "hormiga": '1',
    "tijerilla": '0',
    "grillo": '0',
    "pulga": '0',
    "gorgojo": '5',
    "escarabajo": '3',
    "otra_plaga": '8',
    "descripcion": 'Otro',
    "realizada": 'Gerardo Fernández',
  },
  {
    "folio": '0001-369',
    "numero_equipo": '11598753214',
    "status_equipo": 'Optimo',
    "acción_realizada": 'Limpieza y monitoreo',
    "rata_noruega": '1',
    "rata_tejado": '3',
    "raton_domestico": '5',
    "raton_campo": '8',
    "cucaracha_alemana": '7',
    "cucaracha_americana": '2',
    "hormiga": '1',
    "tijerilla": '0',
    "grillo": '0',
    "pulga": '0',
    "gorgojo": '5',
    "escarabajo": '3',
    "otra_plaga": '8',
    "descripcion": 'Otro',
    "realizada": 'Gerardo Fernández',
  },
  {
    "folio": '0001-369',
    "numero_equipo": '11598753214',
    "status_equipo": 'Optimo',
    "acción_realizada": 'Limpieza y monitoreo',
    "rata_noruega": '1',
    "rata_tejado": '3',
    "raton_domestico": '5',
    "raton_campo": '8',
    "cucaracha_alemana": '7',
    "cucaracha_americana": '2',
    "hormiga": '1',
    "tijerilla": '0',
    "grillo": '0',
    "pulga": '0',
    "gorgojo": '5',
    "escarabajo": '3',
    "otra_plaga": '8',
    "descripcion": 'Otro',
    "realizada": 'Gerardo Fernández',
  },
  {
    "folio": '0001-369',
    "numero_equipo": '11598753214',
    "status_equipo": 'Optimo',
    "acción_realizada": 'Limpieza y monitoreo',
    "rata_noruega": '1',
    "rata_tejado": '3',
    "raton_domestico": '5',
    "raton_campo": '8',
    "cucaracha_alemana": '7',
    "cucaracha_americana": '2',
    "hormiga": '1',
    "tijerilla": '0',
    "grillo": '0',
    "pulga": '0',
    "gorgojo": '5',
    "escarabajo": '3',
    "otra_plaga": '8',
    "descripcion": 'Otro',
    "realizada": 'Gerardo Fernández',
  },
  {
    "folio": '0001-369',
    "numero_equipo": '11598753214',
    "status_equipo": 'Optimo',
    "acción_realizada": 'Limpieza y monitoreo',
    "rata_noruega": '1',
    "rata_tejado": '3',
    "raton_domestico": '5',
    "raton_campo": '8',
    "cucaracha_alemana": '7',
    "cucaracha_americana": '2',
    "hormiga": '1',
    "tijerilla": '0',
    "grillo": '0',
    "pulga": '0',
    "gorgojo": '5',
    "escarabajo": '3',
    "otra_plaga": '8',
    "descripcion": 'Otro',
    "realizada": 'Gerardo Fernández',
  },
  {
    "folio": '0001-369',
    "numero_equipo": '11598753214',
    "status_equipo": 'Optimo',
    "acción_realizada": 'Limpieza y monitoreo',
    "rata_noruega": '1',
    "rata_tejado": '3',
    "raton_domestico": '5',
    "raton_campo": '8',
    "cucaracha_alemana": '7',
    "cucaracha_americana": '2',
    "hormiga": '1',
    "tijerilla": '0',
    "grillo": '0',
    "pulga": '0',
    "gorgojo": '5',
    "escarabajo": '3',
    "otra_plaga": '8',
    "descripcion": 'Otro',
    "realizada": 'Gerardo Fernández',
  },
  {
    "folio": '0001-369',
    "numero_equipo": '11598753214',
    "status_equipo": 'Optimo',
    "acción_realizada": 'Limpieza y monitoreo',
    "rata_noruega": '1',
    "rata_tejado": '3',
    "raton_domestico": '5',
    "raton_campo": '8',
    "cucaracha_alemana": '7',
    "cucaracha_americana": '2',
    "hormiga": '1',
    "tijerilla": '0',
    "grillo": '0',
    "pulga": '0',
    "gorgojo": '5',
    "escarabajo": '3',
    "otra_plaga": '8',
    "descripcion": 'Otro',
    "realizada": 'Gerardo Fernández',
  },
  {
    "folio": '0001-369',
    "numero_equipo": '11598753214',
    "status_equipo": 'Optimo',
    "acción_realizada": 'Limpieza y monitoreo',
    "rata_noruega": '1',
    "rata_tejado": '3',
    "raton_domestico": '5',
    "raton_campo": '8',
    "cucaracha_alemana": '7',
    "cucaracha_americana": '2',
    "hormiga": '1',
    "tijerilla": '0',
    "grillo": '0',
    "pulga": '0',
    "gorgojo": '5',
    "escarabajo": '3',
    "otra_plaga": '8',
    "descripcion": 'Otro',
    "realizada": 'Gerardo Fernández',
  },
  {
    "folio": '0001-369',
    "numero_equipo": '11598753214',
    "status_equipo": 'Optimo',
    "acción_realizada": 'Limpieza y monitoreo',
    "rata_noruega": '1',
    "rata_tejado": '3',
    "raton_domestico": '5',
    "raton_campo": '8',
    "cucaracha_alemana": '7',
    "cucaracha_americana": '2',
    "hormiga": '1',
    "tijerilla": '0',
    "grillo": '0',
    "pulga": '0',
    "gorgojo": '5',
    "escarabajo": '3',
    "otra_plaga": '8',
    "descripcion": 'Otro',
    "realizada": 'Gerardo Fernández',
  },
  {
    "folio": '0001-369',
    "numero_equipo": '11598753214',
    "status_equipo": 'Optimo',
    "acción_realizada": 'Limpieza y monitoreo',
    "rata_noruega": '1',
    "rata_tejado": '3',
    "raton_domestico": '5',
    "raton_campo": '8',
    "cucaracha_alemana": '7',
    "cucaracha_americana": '2',
    "hormiga": '1',
    "tijerilla": '0',
    "grillo": '0',
    "pulga": '0',
    "gorgojo": '5',
    "escarabajo": '3',
    "otra_plaga": '8',
    "descripcion": 'Otro',
    "realizada": 'Gerardo Fernández',
  },
];


//---CONFIG GRAPHIC
var data1 = {
  labels: ['2022-12-01','2022-12-08','2022-12-15','2022-12-25','2023-01-03'],
  datasets: [
    {
      label: 'Plaga 1',
      data: [25,10,20,25,20],
      borderColor: "#264653",
      fill: false
    },
        {
      label: 'Plaga 2',
      data: [5,52,11,85,65],
      borderColor: "#1b747c",
      fill: false
    },
        {
      label: 'Plaga 3',
      data: [12,4,20,54,30],
      borderColor: "#26988e",
      fill: false
    },
        {
      label: 'Plaga 4',
      data: [15,20,30,45,50],
      borderColor: "#1c7c81",
      fill: false
    },
  ]
};



var setOptions1 = {
  responsive: true,
  plugins: {
    legend: {
      display: true,
      position: 'top',
    },
    title: {
        display: true,
        text: 'Reporte de Consolidado De Visitas De Goma',
        font: {
          size: 25
        }
    },
    datalabels: {
      color: 'white',
    }
  },
  scales: {
    y:{
      ticks: {
        stepSize: 1
      }, 
    }
  },
};