// Datos demo 

//--Table 
var columsTable1 = [
  { title:"Forma", field:'forma',hozAlign:"left",width:250},
  { title:"Fecha", field:'fecha',hozAlign:"left",width:250},
  { title:"Cliente", field:'cliente',hozAlign:"left",width:250},
  { title:"Sucursal", field:'sucursal',hozAlign:"left",width:250},
  { title:"Año", field:'year',hozAlign:"left",width:250},
  { title:"Mes", field:'mes',hozAlign:"left",width:250},

  { title:"MoscaD", field:'mosca_d',hozAlign:"left",width:250},
  { title:"MoscaFru", field:'mosca_fru',hozAlign:"left",width:250},
  { title:"MoscaDre", field:'mosca_dre',hozAlign:"left",width:250},
  { title:"MoscaM", field:'mosca_m',hozAlign:"left",width:250},
  { title:"MoscaFlo", field:'mosca_flo',hozAlign:"left",width:250},
  { title:"Palomilla", field:'palomilla',hozAlign:"left",width:250},
  { title:"Otras Palomillas", field:'otras_Palomillas',hozAlign:"left",width:250},
  { title:"Gorgojos", field:'gorgojos',hozAlign:"left",width:250},
  { title:"Otros Escarabajos", field:'otros_escarabajos',hozAlign:"left",width:250},
  { title:"Abeja", field:'abeja',hozAlign:"left",width:250},
  { title:"Avispa", field:'avispa',hozAlign:"left",width:250},
  { title:"Zancudo", field:'Zancudo',hozAlign:"left",width:250},
  { title:"Insectos", field:'Insectos AV',hozAlign:"left",width:250},
  { title:"Otros", field:'Otros',hozAlign:"left",width:250},
  { title:"Dispositivo", field:'dispositivo',hozAlign:"left",width:250},
  { title:"Total", field:'total',hozAlign:"left",width:250},
];

var dataTable1 = [
  {
    forma:"251-10626",
    fecha:"20/7/2022",
    cliente:"Cliente Example",
    sucursal:"Sucursal Example",
    year:"2022",
    mes:"11",
    mosca_d:"1",
    mosca_fru:"1",
    mosca_dre:"1",
    mosca_m:"1",
    mosca_flo:"1",
    palomilla:"1",
    otras_Palomillas:"1",
    gorgojos:"1",
    otros_escarabajos:"1",
    abeja:"1",
    avispa:"1",
    zancudo:"1",
    insectos:"1",
    otros:"1",
    dispositivo:"1542-98",
    total:"15",
  },
    {
    forma:"251-10626",
    fecha:"20/7/2022",
    cliente:"Cliente Example",
    sucursal:"Sucursal Example",
    year:"2022",
    mes:"11",
    mosca_d:"1",
    mosca_fru:"1",
    mosca_dre:"1",
    mosca_m:"1",
    mosca_flo:"1",
    palomilla:"1",
    otras_Palomillas:"1",
    gorgojos:"1",
    otros_escarabajos:"1",
    abeja:"1",
    avispa:"1",
    zancudo:"1",
    insectos:"1",
    otros:"1",
    dispositivo:"1542-98",
    total:"15",
  },
    {
    forma:"251-10626",
    fecha:"20/7/2022",
    cliente:"Cliente Example",
    sucursal:"Sucursal Example",
    year:"2022",
    mes:"11",
    mosca_d:"1",
    mosca_fru:"1",
    mosca_dre:"1",
    mosca_m:"1",
    mosca_flo:"1",
    palomilla:"1",
    otras_Palomillas:"1",
    gorgojos:"1",
    otros_escarabajos:"1",
    abeja:"1",
    avispa:"1",
    zancudo:"1",
    insectos:"1",
    otros:"1",
    dispositivo:"1542-98",
    total:"15",
  },
    {
    forma:"251-10626",
    fecha:"20/7/2022",
    cliente:"Cliente Example",
    sucursal:"Sucursal Example",
    year:"2022",
    mes:"11",
    mosca_d:"1",
    mosca_fru:"1",
    mosca_dre:"1",
    mosca_m:"1",
    mosca_flo:"1",
    palomilla:"1",
    otras_Palomillas:"1",
    gorgojos:"1",
    otros_escarabajos:"1",
    abeja:"1",
    avispa:"1",
    zancudo:"1",
    insectos:"1",
    otros:"1",
    dispositivo:"1542-98",
    total:"15",
  },
    {
    forma:"251-10626",
    fecha:"20/7/2022",
    cliente:"Cliente Example",
    sucursal:"Sucursal Example",
    year:"2022",
    mes:"11",
    mosca_d:"1",
    mosca_fru:"1",
    mosca_dre:"1",
    mosca_m:"1",
    mosca_flo:"1",
    palomilla:"1",
    otras_Palomillas:"1",
    gorgojos:"1",
    otros_escarabajos:"1",
    abeja:"1",
    avispa:"1",
    zancudo:"1",
    insectos:"1",
    otros:"1",
    dispositivo:"1542-98",
    total:"15",
  },
    {
    forma:"251-10626",
    fecha:"20/7/2022",
    cliente:"Cliente Example",
    sucursal:"Sucursal Example",
    year:"2022",
    mes:"11",
    mosca_d:"1",
    mosca_fru:"1",
    mosca_dre:"1",
    mosca_m:"1",
    mosca_flo:"1",
    palomilla:"1",
    otras_Palomillas:"1",
    gorgojos:"1",
    otros_escarabajos:"1",
    abeja:"1",
    avispa:"1",
    zancudo:"1",
    insectos:"1",
    otros:"1",
    dispositivo:"1542-98",
    total:"15",
  },
    {
    forma:"251-10626",
    fecha:"20/7/2022",
    cliente:"Cliente Example",
    sucursal:"Sucursal Example",
    year:"2022",
    mes:"11",
    mosca_d:"1",
    mosca_fru:"1",
    mosca_dre:"1",
    mosca_m:"1",
    mosca_flo:"1",
    palomilla:"1",
    otras_Palomillas:"1",
    gorgojos:"1",
    otros_escarabajos:"1",
    abeja:"1",
    avispa:"1",
    zancudo:"1",
    insectos:"1",
    otros:"1",
    dispositivo:"1542-98",
    total:"15",
  },
];
