// Datos demo para Reporte ENcuestas MOntaje

//--Table Montajes Por Mes
var columsTable1 = [
  { title:"Fecha", field:'fecha',hozAlign:"left",width:250},
  { title:"Cliente", field:'cliente',hozAlign:"left",width:250},
  { title:"Sucursal", field:'sucursal',hozAlign:"left",width:250},
  { title:"Num Equipo", field:'num_equipo',hozAlign:"left",width:250},
  { title:"Año", field:'year',hozAlign:"left",width:250},
  { title:"Mes", field:'mes',hozAlign:"left",width:250},
  { title:"Condición", field:'condicion',hozAlign:"left",width:250},
  { title:"Condición Cebo", field:'cond_cebo',hozAlign:"left",width:250},
  { title:"Acción", field:'accion',hozAlign:"left",width:250},
  { title:"Consumo", field:'consumo',hozAlign:"left",width:250},
  { title:"Cordon Sanitario", field:'cordon_sanitario',hozAlign:"left",width:250},
  { title:"Tienda", field:'tienda',hozAlign:"left",width:250},
  { title:"Promedio", field:'promedio',hozAlign:"left",width:250},
  { title:"Consumos", field:'consumos',hozAlign:"left",width:250},
  { title:"Tienda", field:'tienda',hozAlign:"left",width:250},
  { title:"Promedio", field:'promedio',hozAlign:"left",width:250},
  { title:"Consumos", field:'consumos',hozAlign:"left",width:250},
  { title:"Actividad Cebo", field:'actividad_cebo',hozAlign:"left",width:250},
  { title:"Cant Cebos", field:'cantidad_cebos',hozAlign:"left",width:250},
];

var dataTable1 = [
  {
    fecha:"2022/12/31",
    cliente:"Cliente Example",
    sucursal:"Sucursal Example",
    num_equipo:"NUmero Equipo",
    year:"2022",
    mes:"DIciembre",
    condicion:"Condición",
    cond_cebo:"OK",
    accion:"OK",
    consumo:"1000",
    cordon_sanitario:"Example",
    tienda:"Tienda Example",
    promedio:"1100",
    consumos:"2000",
    tienda:"1000",
    promedio:"100",
    consumos:"2000",
    actividad_cebo:"1000",
    cantidad_cebos:"1000",
  },
    {
    fecha:"2022/12/31",
    cliente:"Cliente Example",
    sucursal:"Sucursal Example",
    num_equipo:"NUmero Equipo",
    year:"2022",
    mes:"DIciembre",
    condicion:"Condición",
    cond_cebo:"OK",
    accion:"OK",
    consumo:"1000",
    cordon_sanitario:"Example",
    tienda:"Tienda Example",
    promedio:"1100",
    consumos:"2000",
    tienda:"1000",
    promedio:"100",
    consumos:"2000",
    actividad_cebo:"1000",
    cantidad_cebos:"1000",
  },
    {
    fecha:"2022/12/31",
    cliente:"Cliente Example",
    sucursal:"Sucursal Example",
    num_equipo:"NUmero Equipo",
    year:"2022",
    mes:"DIciembre",
    condicion:"Condición",
    cond_cebo:"OK",
    accion:"OK",
    consumo:"1000",
    cordon_sanitario:"Example",
    tienda:"Tienda Example",
    promedio:"1100",
    consumos:"2000",
    tienda:"1000",
    promedio:"100",
    consumos:"2000",
    actividad_cebo:"1000",
    cantidad_cebos:"1000",
  },
    {
    fecha:"2022/12/31",
    cliente:"Cliente Example",
    sucursal:"Sucursal Example",
    num_equipo:"NUmero Equipo",
    year:"2022",
    mes:"DIciembre",
    condicion:"Condición",
    cond_cebo:"OK",
    accion:"OK",
    consumo:"1000",
    cordon_sanitario:"Example",
    tienda:"Tienda Example",
    promedio:"1100",
    consumos:"2000",
    tienda:"1000",
    promedio:"100",
    consumos:"2000",
    actividad_cebo:"1000",
    cantidad_cebos:"1000",
  },
    {
    fecha:"2022/12/31",
    cliente:"Cliente Example",
    sucursal:"Sucursal Example",
    num_equipo:"NUmero Equipo",
    year:"2022",
    mes:"DIciembre",
    condicion:"Condición",
    cond_cebo:"OK",
    accion:"OK",
    consumo:"1000",
    cordon_sanitario:"Example",
    tienda:"Tienda Example",
    promedio:"1100",
    consumos:"2000",
    tienda:"1000",
    promedio:"100",
    consumos:"2000",
    actividad_cebo:"1000",
    cantidad_cebos:"1000",
  },
    {
    fecha:"2022/12/31",
    cliente:"Cliente Example",
    sucursal:"Sucursal Example",
    num_equipo:"NUmero Equipo",
    year:"2022",
    mes:"DIciembre",
    condicion:"Condición",
    cond_cebo:"OK",
    accion:"OK",
    consumo:"1000",
    cordon_sanitario:"Example",
    tienda:"Tienda Example",
    promedio:"1100",
    consumos:"2000",
    tienda:"1000",
    promedio:"100",
    consumos:"2000",
    actividad_cebo:"1000",
    cantidad_cebos:"1000",
  },
    {
    fecha:"2022/12/31",
    cliente:"Cliente Example",
    sucursal:"Sucursal Example",
    num_equipo:"NUmero Equipo",
    year:"2022",
    mes:"DIciembre",
    condicion:"Condición",
    cond_cebo:"OK",
    accion:"OK",
    consumo:"1000",
    cordon_sanitario:"Example",
    tienda:"Tienda Example",
    promedio:"1100",
    consumos:"2000",
    tienda:"1000",
    promedio:"100",
    consumos:"2000",
    actividad_cebo:"1000",
    cantidad_cebos:"1000",
  },
    {
    fecha:"2022/12/31",
    cliente:"Cliente Example",
    sucursal:"Sucursal Example",
    num_equipo:"NUmero Equipo",
    year:"2022",
    mes:"DIciembre",
    condicion:"Condición",
    cond_cebo:"OK",
    accion:"OK",
    consumo:"1000",
    cordon_sanitario:"Example",
    tienda:"Tienda Example",
    promedio:"1100",
    consumos:"2000",
    tienda:"1000",
    promedio:"100",
    consumos:"2000",
    actividad_cebo:"1000",
    cantidad_cebos:"1000",
  },
    {
    fecha:"2022/12/31",
    cliente:"Cliente Example",
    sucursal:"Sucursal Example",
    num_equipo:"NUmero Equipo",
    year:"2022",
    mes:"DIciembre",
    condicion:"Condición",
    cond_cebo:"OK",
    accion:"OK",
    consumo:"1000",
    cordon_sanitario:"Example",
    tienda:"Tienda Example",
    promedio:"1100",
    consumos:"2000",
    tienda:"1000",
    promedio:"100",
    consumos:"2000",
    actividad_cebo:"1000",
    cantidad_cebos:"1000",
  },
    {
    fecha:"2022/12/31",
    cliente:"Cliente Example",
    sucursal:"Sucursal Example",
    num_equipo:"NUmero Equipo",
    year:"2022",
    mes:"DIciembre",
    condicion:"Condición",
    cond_cebo:"OK",
    accion:"OK",
    consumo:"1000",
    cordon_sanitario:"Example",
    tienda:"Tienda Example",
    promedio:"1100",
    consumos:"2000",
    tienda:"1000",
    promedio:"100",
    consumos:"2000",
    actividad_cebo:"1000",
    cantidad_cebos:"1000",
  },
    {
    fecha:"2022/12/31",
    cliente:"Cliente Example",
    sucursal:"Sucursal Example",
    num_equipo:"NUmero Equipo",
    year:"2022",
    mes:"DIciembre",
    condicion:"Condición",
    cond_cebo:"OK",
    accion:"OK",
    consumo:"1000",
    cordon_sanitario:"Example",
    tienda:"Tienda Example",
    promedio:"1100",
    consumos:"2000",
    tienda:"1000",
    promedio:"100",
    consumos:"2000",
    actividad_cebo:"1000",
    cantidad_cebos:"1000",
  },
];
