// Datos demo 

//--Table 
var columsTable1 = [
  { title:"Forma", field:'forma',hozAlign:"left",width:250},
  { title:"Cliente", field:'cliente',hozAlign:"left",width:250},
  { title:"Fecha", field:'fecha',hozAlign:"left",width:250},
  { title:"Mes", field:'mes',hozAlign:"left",width:250},
  { title:"No. Equipo", field:'numero_equipo',hozAlign:"left",width:250},
  { title:"Año", field:'year',hozAlign:"left",width:250},
  { title:"Ratan", field:'ratan',hozAlign:"left",width:250},
  { title:"RataT", field:'ratat',hozAlign:"left",width:250},
  { title:"RataD", field:'ratad',hozAlign:"left",width:250},
  { title:"RataC", field:'ratac',hozAlign:"left",width:250},
  { title:"CucarachaAl", field:'cucaracha_al',hozAlign:"left",width:250},
  { title:"CucarachaAm", field:'cucaracha_am',hozAlign:"left",width:250},
  { title:"CucarachaO", field:'cucaracha_o',hozAlign:"left",width:250},
  { title:"Hormiga", field:'hormiga',hozAlign:"left",width:250},
  { title:"HormigaC", field:'hormiga_c',hozAlign:"left",width:250},
  { title:"Tijerilla", field:'tijerilla',hozAlign:"left",width:250},
  { title:"Grillo", field:'grillo',hozAlign:"left",width:250},
  { title:"PescaditoP", field:'pescadito_p',hozAlign:"left",width:250},
  { title:"Pulga", field:'pulga',hozAlign:"left",width:250},
  { title:"ChincheC", field:'chinche_c',hozAlign:"left",width:250},
  { title:"Mosca", field:'mosca',hozAlign:"left",width:250},
  { title:"Palomilla", field:'palomilla',hozAlign:"left",width:250},
  { title:"Gorgojo", field:'gorgojo',hozAlign:"left",width:250},
  { title:"EscarabajoP", field:'escabarajo_p',hozAlign:"left",width:250},
  { title:"TermitaS", field:'termitas_s',hozAlign:"left",width:250},
  { title:"Caracol", field:'caracol',hozAlign:"left",width:250},
  { title:"Otra", field:'otra',hozAlign:"left",width:250},
  { title:"Total", field:'total',hozAlign:"left",width:250},

];

var dataTable1 = [
  {
    forma:"251-10626",
    cliente:"Cliente Example",
    fecha:"20/7/2022",
    mes:"Julio",
    numero_equipo:"0250",
    year:"2022",
    ratan:"12",
    ratat:"12",
    ratad:"12",
    ratac:"12",
    cucaracha_al:"13",
    cucaracha_am:"13",
    cucaracha_o:"13",
    hormiga:"14",
    hormiga_c:"14",
    tijerilla:"15",
    grillo:"15",
    pescadito_p:"16",
    pulga:"17",
    chinche_c:"18",
    mosca:"19",
    palomilla:"19",
    gorgojo:"20",
    escabarajo_p:"20",
    termitas_s:"21",
    caracol:"22",
    otra:"22",
    total:"500",
  },
  {
    forma:"251-10626",
    cliente:"Cliente Example",
    fecha:"20/7/2022",
    mes:"Julio",
    numero_equipo:"0250",
    year:"2022",
    ratan:"12",
    ratat:"12",
    ratad:"12",
    ratac:"12",
    cucaracha_al:"13",
    cucaracha_am:"13",
    cucaracha_o:"13",
    hormiga:"14",
    hormiga_c:"14",
    tijerilla:"15",
    grillo:"15",
    pescadito_p:"16",
    pulga:"17",
    chinche_c:"18",
    mosca:"19",
    palomilla:"19",
    gorgojo:"20",
    escabarajo_p:"20",
    termitas_s:"21",
    caracol:"22",
    otra:"22",
    total:"500",
  },
  {
    forma:"251-10626",
    cliente:"Cliente Example",
    fecha:"20/7/2022",
    mes:"Julio",
    numero_equipo:"0250",
    year:"2022",
    ratan:"12",
    ratat:"12",
    ratad:"12",
    ratac:"12",
    cucaracha_al:"13",
    cucaracha_am:"13",
    cucaracha_o:"13",
    hormiga:"14",
    hormiga_c:"14",
    tijerilla:"15",
    grillo:"15",
    pescadito_p:"16",
    pulga:"17",
    chinche_c:"18",
    mosca:"19",
    palomilla:"19",
    gorgojo:"20",
    escabarajo_p:"20",
    termitas_s:"21",
    caracol:"22",
    otra:"22",
    total:"500",
  },
  {
    forma:"251-10626",
    cliente:"Cliente Example",
    fecha:"20/7/2022",
    mes:"Julio",
    numero_equipo:"0250",
    year:"2022",
    ratan:"12",
    ratat:"12",
    ratad:"12",
    ratac:"12",
    cucaracha_al:"13",
    cucaracha_am:"13",
    cucaracha_o:"13",
    hormiga:"14",
    hormiga_c:"14",
    tijerilla:"15",
    grillo:"15",
    pescadito_p:"16",
    pulga:"17",
    chinche_c:"18",
    mosca:"19",
    palomilla:"19",
    gorgojo:"20",
    escabarajo_p:"20",
    termitas_s:"21",
    caracol:"22",
    otra:"22",
    total:"500",
  },
  {
    forma:"251-10626",
    cliente:"Cliente Example",
    fecha:"20/7/2022",
    mes:"Julio",
    numero_equipo:"0250",
    year:"2022",
    ratan:"12",
    ratat:"12",
    ratad:"12",
    ratac:"12",
    cucaracha_al:"13",
    cucaracha_am:"13",
    cucaracha_o:"13",
    hormiga:"14",
    hormiga_c:"14",
    tijerilla:"15",
    grillo:"15",
    pescadito_p:"16",
    pulga:"17",
    chinche_c:"18",
    mosca:"19",
    palomilla:"19",
    gorgojo:"20",
    escabarajo_p:"20",
    termitas_s:"21",
    caracol:"22",
    otra:"22",
    total:"500",
  },
  {
    forma:"251-10626",
    cliente:"Cliente Example",
    fecha:"20/7/2022",
    mes:"Julio",
    numero_equipo:"0250",
    year:"2022",
    ratan:"12",
    ratat:"12",
    ratad:"12",
    ratac:"12",
    cucaracha_al:"13",
    cucaracha_am:"13",
    cucaracha_o:"13",
    hormiga:"14",
    hormiga_c:"14",
    tijerilla:"15",
    grillo:"15",
    pescadito_p:"16",
    pulga:"17",
    chinche_c:"18",
    mosca:"19",
    palomilla:"19",
    gorgojo:"20",
    escabarajo_p:"20",
    termitas_s:"21",
    caracol:"22",
    otra:"22",
    total:"500",
  },
  {
    forma:"251-10626",
    cliente:"Cliente Example",
    fecha:"20/7/2022",
    mes:"Julio",
    numero_equipo:"0250",
    year:"2022",
    ratan:"12",
    ratat:"12",
    ratad:"12",
    ratac:"12",
    cucaracha_al:"13",
    cucaracha_am:"13",
    cucaracha_o:"13",
    hormiga:"14",
    hormiga_c:"14",
    tijerilla:"15",
    grillo:"15",
    pescadito_p:"16",
    pulga:"17",
    chinche_c:"18",
    mosca:"19",
    palomilla:"19",
    gorgojo:"20",
    escabarajo_p:"20",
    termitas_s:"21",
    caracol:"22",
    otra:"22",
    total:"500",
  },
  {
    forma:"251-10626",
    cliente:"Cliente Example",
    fecha:"20/7/2022",
    mes:"Julio",
    numero_equipo:"0250",
    year:"2022",
    ratan:"12",
    ratat:"12",
    ratad:"12",
    ratac:"12",
    cucaracha_al:"13",
    cucaracha_am:"13",
    cucaracha_o:"13",
    hormiga:"14",
    hormiga_c:"14",
    tijerilla:"15",
    grillo:"15",
    pescadito_p:"16",
    pulga:"17",
    chinche_c:"18",
    mosca:"19",
    palomilla:"19",
    gorgojo:"20",
    escabarajo_p:"20",
    termitas_s:"21",
    caracol:"22",
    otra:"22",
    total:"500",
  },
];
