// Datos demo para Reporte ENcuestas MOntaje

//--Table Montajes Por Mes
var columsTable1 = [
  { title:"Formulario", field:'formulario',hozAlign:"left",width:250},
  { title:"Fecha", field:'fecha',hozAlign:"left",width:250},
  { title:"Cliente", field:'cliente',hozAlign:"left",width:250},
  { title:"Sucursal", field:'sucursal',hozAlign:"left",width:250},
  { title:"Año", field:'year',hozAlign:"left",width:250},
  { title:"Mes", field:'mes',hozAlign:"left",width:250},
  { title:"MoscaD", field:'mosca',hozAlign:"left",width:250},
  { title:"MoscaFru", field:'mosca_fru',hozAlign:"left",width:250},
  { title:"MoscaDre", field:'mosca_dre',hozAlign:"left",width:250},
  { title:"MoscaM", field:'mosca_m',hozAlign:"left",width:250},
  { title:"Palomilla", field:'palomilla',hozAlign:"left",width:250},
  { title:"Otras Palomillas", field:'otras_palomillas',hozAlign:"left",width:250},
  { title:"Gorgojos", field:'gorgojos',hozAlign:"left",width:250},
  { title:"Otros Escarabajos", field:'otros_escarabajos',hozAlign:"left",width:250},
  { title:"Abeja", field:'abeja',hozAlign:"left",width:250},
  { title:"Avispa", field:'avispa',hozAlign:"left",width:250},
  { title:"Zancudo", field:'zancudo',hozAlign:"left",width:250},
  { title:"Insectos AV", field:'insectos',hozAlign:"left",width:250},
  { title:"Otros", field:'otros',hozAlign:"left",width:250},
  { title:"Dispositivo", field:'dispositivo',hozAlign:"left",width:250},
  { title:"Total", field:'total',hozAlign:"left",width:250},
];

var dataTable1 = [
  {
    formulario: "Formulario Example",
    fecha: "2022/12/30",
    cliente: "Cliente Example",
    sucursal: "Sucursal Example",
    year: "2022",
    mes: "Diciembre",
    mosca: "150",
    mosca_fru: "150",
    mosca_dre: "150",
    mosca_m: "150",
    palomilla: "150",
    otras_palomillas: "150",
    gorgojos: "150",
    otros_escarabajos: "150",
    abeja: "150",
    avispa: "150",
    zancudo: "150",
    insectos: "150",
    otros: "100",
    dispositivo: "5",
    total: "1500",
  },
    {
    formulario: "Formulario Example",
    fecha: "2022/12/30",
    cliente: "Cliente Example",
    sucursal: "Sucursal Example",
    year: "2022",
    mes: "Diciembre",
    mosca: "150",
    mosca_fru: "150",
    mosca_dre: "150",
    mosca_m: "150",
    palomilla: "150",
    otras_palomillas: "150",
    gorgojos: "150",
    otros_escarabajos: "150",
    abeja: "150",
    avispa: "150",
    zancudo: "150",
    insectos: "150",
    otros: "100",
    dispositivo: "5",
    total: "1500",
  },
    {
    formulario: "Formulario Example",
    fecha: "2022/12/30",
    cliente: "Cliente Example",
    sucursal: "Sucursal Example",
    year: "2022",
    mes: "Diciembre",
    mosca: "150",
    mosca_fru: "150",
    mosca_dre: "150",
    mosca_m: "150",
    palomilla: "150",
    otras_palomillas: "150",
    gorgojos: "150",
    otros_escarabajos: "150",
    abeja: "150",
    avispa: "150",
    zancudo: "150",
    insectos: "150",
    otros: "100",
    dispositivo: "5",
    total: "1500",
  },
    {
    formulario: "Formulario Example",
    fecha: "2022/12/30",
    cliente: "Cliente Example",
    sucursal: "Sucursal Example",
    year: "2022",
    mes: "Diciembre",
    mosca: "150",
    mosca_fru: "150",
    mosca_dre: "150",
    mosca_m: "150",
    palomilla: "150",
    otras_palomillas: "150",
    gorgojos: "150",
    otros_escarabajos: "150",
    abeja: "150",
    avispa: "150",
    zancudo: "150",
    insectos: "150",
    otros: "100",
    dispositivo: "5",
    total: "1500",
  },
    {
    formulario: "Formulario Example",
    fecha: "2022/12/30",
    cliente: "Cliente Example",
    sucursal: "Sucursal Example",
    year: "2022",
    mes: "Diciembre",
    mosca: "150",
    mosca_fru: "150",
    mosca_dre: "150",
    mosca_m: "150",
    palomilla: "150",
    otras_palomillas: "150",
    gorgojos: "150",
    otros_escarabajos: "150",
    abeja: "150",
    avispa: "150",
    zancudo: "150",
    insectos: "150",
    otros: "100",
    dispositivo: "5",
    total: "1500",
  },
    {
    formulario: "Formulario Example",
    fecha: "2022/12/30",
    cliente: "Cliente Example",
    sucursal: "Sucursal Example",
    year: "2022",
    mes: "Diciembre",
    mosca: "150",
    mosca_fru: "150",
    mosca_dre: "150",
    mosca_m: "150",
    palomilla: "150",
    otras_palomillas: "150",
    gorgojos: "150",
    otros_escarabajos: "150",
    abeja: "150",
    avispa: "150",
    zancudo: "150",
    insectos: "150",
    otros: "100",
    dispositivo: "5",
    total: "1500",
  },
    {
    formulario: "Formulario Example",
    fecha: "2022/12/30",
    cliente: "Cliente Example",
    sucursal: "Sucursal Example",
    year: "2022",
    mes: "Diciembre",
    mosca: "150",
    mosca_fru: "150",
    mosca_dre: "150",
    mosca_m: "150",
    palomilla: "150",
    otras_palomillas: "150",
    gorgojos: "150",
    otros_escarabajos: "150",
    abeja: "150",
    avispa: "150",
    zancudo: "150",
    insectos: "150",
    otros: "100",
    dispositivo: "5",
    total: "1500",
  },
    {
    formulario: "Formulario Example",
    fecha: "2022/12/30",
    cliente: "Cliente Example",
    sucursal: "Sucursal Example",
    year: "2022",
    mes: "Diciembre",
    mosca: "150",
    mosca_fru: "150",
    mosca_dre: "150",
    mosca_m: "150",
    palomilla: "150",
    otras_palomillas: "150",
    gorgojos: "150",
    otros_escarabajos: "150",
    abeja: "150",
    avispa: "150",
    zancudo: "150",
    insectos: "150",
    otros: "100",
    dispositivo: "5",
    total: "1500",
  },
    {
    formulario: "Formulario Example",
    fecha: "2022/12/30",
    cliente: "Cliente Example",
    sucursal: "Sucursal Example",
    year: "2022",
    mes: "Diciembre",
    mosca: "150",
    mosca_fru: "150",
    mosca_dre: "150",
    mosca_m: "150",
    palomilla: "150",
    otras_palomillas: "150",
    gorgojos: "150",
    otros_escarabajos: "150",
    abeja: "150",
    avispa: "150",
    zancudo: "150",
    insectos: "150",
    otros: "100",
    dispositivo: "5",
    total: "1500",
  },
    {
    formulario: "Formulario Example",
    fecha: "2022/12/30",
    cliente: "Cliente Example",
    sucursal: "Sucursal Example",
    year: "2022",
    mes: "Diciembre",
    mosca: "150",
    mosca_fru: "150",
    mosca_dre: "150",
    mosca_m: "150",
    palomilla: "150",
    otras_palomillas: "150",
    gorgojos: "150",
    otros_escarabajos: "150",
    abeja: "150",
    avispa: "150",
    zancudo: "150",
    insectos: "150",
    otros: "100",
    dispositivo: "5",
    total: "1500",
  },
    {
    formulario: "Formulario Example",
    fecha: "2022/12/30",
    cliente: "Cliente Example",
    sucursal: "Sucursal Example",
    year: "2022",
    mes: "Diciembre",
    mosca: "150",
    mosca_fru: "150",
    mosca_dre: "150",
    mosca_m: "150",
    palomilla: "150",
    otras_palomillas: "150",
    gorgojos: "150",
    otros_escarabajos: "150",
    abeja: "150",
    avispa: "150",
    zancudo: "150",
    insectos: "150",
    otros: "100",
    dispositivo: "5",
    total: "1500",
  },
];
