// Datos demo para Reporte ENcuestas MOntaje

//--Table Montajes Por Mes

var columsTable1 = [
  { title:"Production Year", field:'production_year',hozAlign:"left",width:250},
  { title:"Week", field:'week',hozAlign:"right",width:250},
  { title:"Week Production :Priority", field:'priority',hozAlign:"left",width:250},
  { title:"Week Production: Plant: Plant Code", field:'plant_code',hozAlign:"left",width:250},
  { title:"Week Production: Plant: Plant Name", field:'plant_name',hozAlign:"left",width:250},
  { title:"Plan Requier Eaches", field:'requier_eaches',hozAlign:"right",width:250},
  { title:"Stock available eaches", field:'stock_available',hozAlign:"right",width:250},
  { title:"Week Production: Requierd Eaches Qty", field:'requierd_eaches_qty',hozAlign:"right",width:250},
  { title:"Week Production: Comments", field:'comments',hozAlign:"left",width:250},
  
];

var dataTable1 = [
  {
    "production_year":"2023",
    "week":"8",
    "priority":"",
    "plant_code":"FEAS",
    "plant_name":"Asparagus Fern",
    "requier_eaches":"1400",
    "stock_available":"1000",
    "requierd_eaches_qty":"10000",
    "comments":"Primer Set",
  },
  {
    "production_year":"2023",
    "week":"8",
    "priority":"",
    "plant_code":"LACBS",
    "plant_name":"Copper Plant",
    "requier_eaches":"1400",
    "stock_available":"1000",
    "requierd_eaches_qty":"10000",
    "comments":"Segundo Set",
  },
  {
    "production_year":"2023",
    "week":"8",
    "priority":"",
    "plant_code":"FEAS",
    "plant_name":"Asparagus Fern",
    "requier_eaches":"1400",
    "stock_available":"1000",
    "requierd_eaches_qty":"10000",
    "comments":"Primer Set",
  },
  {
    "production_year":"2023",
    "week":"8",
    "priority":"",
    "plant_code":"LACBS",
    "plant_name":"Copper Plant",
    "requier_eaches":"1400",
    "stock_available":"1000",
    "requierd_eaches_qty":"10000",
    "comments":"Segundo Set",
  },
  {
    "production_year":"2023",
    "week":"8",
    "priority":"",
    "plant_code":"FEAS",
    "plant_name":"Asparagus Fern",
    "requier_eaches":"1400",
    "stock_available":"1000",
    "requierd_eaches_qty":"10000",
    "comments":"Primer Set",
  },
  {
    "production_year":"2023",
    "week":"8",
    "priority":"",
    "plant_code":"LACBS",
    "plant_name":"Copper Plant",
    "requier_eaches":"1400",
    "stock_available":"1000",
    "requierd_eaches_qty":"10000",
    "comments":"Segundo Set",
  },
  {
    "production_year":"2023",
    "week":"8",
    "priority":"",
    "plant_code":"FEAS",
    "plant_name":"Asparagus Fern",
    "requier_eaches":"1400",
    "stock_available":"1000",
    "requierd_eaches_qty":"10000",
    "comments":"Primer Set",
  },
  {
    "production_year":"2023",
    "week":"8",
    "priority":"",
    "plant_code":"LACBS",
    "plant_name":"Copper Plant",
    "requier_eaches":"1400",
    "stock_available":"1000",
    "requierd_eaches_qty":"10000",
    "comments":"Segundo Set",
  },
  {
    "production_year":"2023",
    "week":"8",
    "priority":"",
    "plant_code":"FEAS",
    "plant_name":"Asparagus Fern",
    "requier_eaches":"1400",
    "stock_available":"1000",
    "requierd_eaches_qty":"10000",
    "comments":"Primer Set",
  },
  {
    "production_year":"2023",
    "week":"8",
    "priority":"",
    "plant_code":"LACBS",
    "plant_name":"Copper Plant",
    "requier_eaches":"1400",
    "stock_available":"1000",
    "requierd_eaches_qty":"10000",
    "comments":"Segundo Set",
  },
  {
    "production_year":"2023",
    "week":"8",
    "priority":"",
    "plant_code":"FEAS",
    "plant_name":"Asparagus Fern",
    "requier_eaches":"1400",
    "stock_available":"1000",
    "requierd_eaches_qty":"10000",
    "comments":"Primer Set",
  },
  {
    "production_year":"2023",
    "week":"8",
    "priority":"",
    "plant_code":"LACBS",
    "plant_name":"Copper Plant",
    "requier_eaches":"1400",
    "stock_available":"1000",
    "requierd_eaches_qty":"10000",
    "comments":"Segundo Set",
  },
];
