// Datos demo para Reporte ENcuestas MOntaje

//--Table Montajes Por Mes

var columsTable1 = [
  { title:"Technician", field:'technician',hozAlign:"left",width:250},
  { title:"Cut day", field:'cut_day',hozAlign:"left",width:250},
  { title:"Plant Code", field:'plant_code',hozAlign:"left",width:250},
  { title:"Plant Name", field:'plant_name',hozAlign:"left",width:250},
  { title:"Stage", field:'stage',hozAlign:"left",width:250},

  { title:"Initial stock", field:'initial_stock',hozAlign:"right",bottomCalc:"sum", bottomCalcParams:{precision:2,},width:250},
  { title:"Produced", field:'produced',hozAlign:"right",bottomCalc:"sum", bottomCalcParams:{precision:2,},width:250},
  { title:"Multiplication Factor", field:'multiplication_factor',hozAlign:"right",bottomCalc:"sum", bottomCalcParams:{precision:2,},width:250},
  { title:"Start time", field:'start_time',hozAlign:"right",bottomCalc:"sum", bottomCalcParams:{precision:2,},width:250},
  { title:"End time", field:'end_time',hozAlign:"right",bottomCalc:"sum", bottomCalcParams:{precision:2,},width:250},
  { title:"Worked Hours", field:'worked_hours',hozAlign:"right",bottomCalc:"sum", bottomCalcParams:{precision:2,},width:250},
  { title:"Productivity", field:'productivity',hozAlign:"right",bottomCalc:"sum", bottomCalcParams:{precision:2,},width:250},
];

var dataTable1 = [
  {
    technician: "Jose Fernando Patricio",
    cut_day: "05/19/2022",
    plant_code: "LAGBG",
    plant_name: "Blue Glow Agave",
    stage: "2",
    initial_stock: 5008,
    produced: 3008,
    multiplication_factor: 8,
    start_time: 708,
    end_time: 2008,
    worked_hours: 100,
    productivity: 800,
  },
  {
    technician: "Jose Fernando Patricio",
    cut_day: "05/19/2022",
    plant_code: "LAGBG",
    plant_name: "Blue Glow Agave",
    stage: "2",
    initial_stock: 5008,
    produced: 3008,
    multiplication_factor: 8,
    start_time: 708,
    end_time: 2008,
    worked_hours: 100,
    productivity: 800,
  },
  {
    technician: "Jose Fernando Patricio",
    cut_day: "05/19/2022",
    plant_code: "LAGBG",
    plant_name: "Blue Glow Agave",
    stage: "2",
    initial_stock: 5008,
    produced: 3008,
    multiplication_factor: 8,
    start_time: 708,
    end_time: 2008,
    worked_hours: 100,
    productivity: 800,
  },
  {
    technician: "Jose Fernando Patricio",
    cut_day: "05/19/2022",
    plant_code: "LAGBG",
    plant_name: "Blue Glow Agave",
    stage: "2",
    initial_stock: 5008,
    produced: 3008,
    multiplication_factor: 8,
    start_time: 708,
    end_time: 2008,
    worked_hours: 100,
    productivity: 800,
  },
  {
    technician: "Jose Fernando Patricio",
    cut_day: "05/19/2022",
    plant_code: "LAGBG",
    plant_name: "Blue Glow Agave",
    stage: "2",
    initial_stock: 5008,
    produced: 3008,
    multiplication_factor: 8,
    start_time: 708,
    end_time: 2008,
    worked_hours: 100,
    productivity: 800,
  },
  {
    technician: "Jose Fernando Patricio",
    cut_day: "05/19/2022",
    plant_code: "LAGBG",
    plant_name: "Blue Glow Agave",
    stage: "2",
    initial_stock: 5008,
    produced: 3008,
    multiplication_factor: 8,
    start_time: 708,
    end_time: 2008,
    worked_hours: 100,
    productivity: 800,
  },
  {
    technician: "Jose Fernando Patricio",
    cut_day: "05/19/2022",
    plant_code: "LAGBG",
    plant_name: "Blue Glow Agave",
    stage: "2",
    initial_stock: 5008,
    produced: 3008,
    multiplication_factor: 8,
    start_time: 708,
    end_time: 2008,
    worked_hours: 100,
    productivity: 800,
  },
  {
    technician: "Jose Fernando Patricio",
    cut_day: "05/19/2022",
    plant_code: "LAGBG",
    plant_name: "Blue Glow Agave",
    stage: "2",
    initial_stock: 5008,
    produced: 3008,
    multiplication_factor: 8,
    start_time: 708,
    end_time: 2008,
    worked_hours: 100,
    productivity: 800,
  },
  {
    technician: "Jose Fernando Patricio",
    cut_day: "05/19/2022",
    plant_code: "LAGBG",
    plant_name: "Blue Glow Agave",
    stage: "2",
    initial_stock: 5008,
    produced: 3008,
    multiplication_factor: 8,
    start_time: 708,
    end_time: 2008,
    worked_hours: 100,
    productivity: 800,
  },
];

