// Datos demo para Reporte ENcuestas MOntaje
var columsTable1 = [
  { title:"Plant Code", field:'plant_code',hozAlign:"left",width:250},
  { title:"NextCut Week", field:'next_week',hozAlign:"left",width:250},
  { title:"Stage ", field:'stage',hozAlign:"left",width:250},
  { title:"Quantity (eaches)", field:'eaches',hozAlign:"left",width:250},
  { title:"Grow Time", field:'grow_time',hozAlign:"right",width:250},
  { title:"Plant Group", field:'plant_group',hozAlign:"right",width:250},
  { title:"Location", field:'location',hozAlign:"right",width:250},
  { title:"Cycles", field:'cycles',hozAlign:"right",width:250},
  { title:"Last Cut Day", field:'last_cut',hozAlign:"right",width:250},
  { title:"Cycle age", field:'cycle_age',hozAlign:"right",width:250},
  { title:"Group age (days)", field:'group_ages',hozAlign:"right",width:250},
  { title:"Contamination", field:'contamination',hozAlign:"right",width:250},
  { title:"Multiplication Factor", field:'multiplication',hozAlign:"right",width:250},
  { title:"Rooting %", field:'rooting',hozAlign:"right",width:250},
  
];

var dataTable1 = [
  {
    plant_code:"LAGBG",
    next_week:"2",
    stage:"2",
    eaches:"10",
    grow_time:"15",
    plant_group:"2",
    location:"6",
    cycles:"3",
    last_cut:"10/08/90",
    cycle_age:"5",
    group_ages:"10",
    contamination:"12",
    multiplication:"2",
    rooting:"36",
  },
  {
    plant_code:"LAGBG",
    next_week:"2",
    stage:"2",
    eaches:"10",
    grow_time:"15",
    plant_group:"2",
    location:"6",
    cycles:"3",
    last_cut:"10/08/90",
    cycle_age:"5",
    group_ages:"10",
    contamination:"12",
    multiplication:"2",
    rooting:"36",
  },
  {
    plant_code:"LAGBG",
    next_week:"2",
    stage:"2",
    eaches:"10",
    grow_time:"15",
    plant_group:"2",
    location:"6",
    cycles:"3",
    last_cut:"10/08/90",
    cycle_age:"5",
    group_ages:"10",
    contamination:"12",
    multiplication:"2",
    rooting:"36",
  },
  {
    plant_code:"LAGBG",
    next_week:"2",
    stage:"2",
    eaches:"10",
    grow_time:"15",
    plant_group:"2",
    location:"6",
    cycles:"3",
    last_cut:"10/08/90",
    cycle_age:"5",
    group_ages:"10",
    contamination:"12",
    multiplication:"2",
    rooting:"36",
  },
  {
    plant_code:"LAGBG",
    next_week:"2",
    stage:"2",
    eaches:"10",
    grow_time:"15",
    plant_group:"2",
    location:"6",
    cycles:"3",
    last_cut:"10/08/90",
    cycle_age:"5",
    group_ages:"10",
    contamination:"12",
    multiplication:"2",
    rooting:"36",
  },
  {
    plant_code:"LAGBG",
    next_week:"2",
    stage:"2",
    eaches:"10",
    grow_time:"15",
    plant_group:"2",
    location:"6",
    cycles:"3",
    last_cut:"10/08/90",
    cycle_age:"5",
    group_ages:"10",
    contamination:"12",
    multiplication:"2",
    rooting:"36",
  },
  {
    plant_code:"LAGBG",
    next_week:"2",
    stage:"2",
    eaches:"10",
    grow_time:"15",
    plant_group:"2",
    location:"6",
    cycles:"3",
    last_cut:"10/08/90",
    cycle_age:"5",
    group_ages:"10",
    contamination:"12",
    multiplication:"2",
    rooting:"36",
  },
  {
    plant_code:"LAGBG",
    next_week:"2",
    stage:"2",
    eaches:"10",
    grow_time:"15",
    plant_group:"2",
    location:"6",
    cycles:"3",
    last_cut:"10/08/90",
    cycle_age:"5",
    group_ages:"10",
    contamination:"12",
    multiplication:"2",
    rooting:"36",
  },
  {
    plant_code:"LAGBG",
    next_week:"2",
    stage:"2",
    eaches:"10",
    grow_time:"15",
    plant_group:"2",
    location:"6",
    cycles:"3",
    last_cut:"10/08/90",
    cycle_age:"5",
    group_ages:"10",
    contamination:"12",
    multiplication:"2",
    rooting:"36",
  },
  {
    plant_code:"LAGBG",
    next_week:"2",
    stage:"2",
    eaches:"10",
    grow_time:"15",
    plant_group:"2",
    location:"6",
    cycles:"3",
    last_cut:"10/08/90",
    cycle_age:"5",
    group_ages:"10",
    contamination:"12",
    multiplication:"2",
    rooting:"36",
  },
  {
    plant_code:"LAGBG",
    next_week:"2",
    stage:"2",
    eaches:"10",
    grow_time:"15",
    plant_group:"2",
    location:"6",
    cycles:"3",
    last_cut:"10/08/90",
    cycle_age:"5",
    group_ages:"10",
    contamination:"12",
    multiplication:"2",
    rooting:"36",
  },
];

