// Datos demo para Reporte ENcuestas MOntaje

//--Table Montajes Por Mes
var columsTable1 = [
  { title:"EBC", field:'ebc',hozAlign:"left",width:250},
  { title:"Provincia ", field:'provincia',hozAlign:"left",width:250},
  { title:"Canton ", field:'canton',hozAlign:"left",width:250},
  { title:"Fecha de obtención permiso ", field:'fecha_permiso',hozAlign:"left",width:250},
  { title:"Fecha de inspeccion ", field:'fecha_inspeccion',hozAlign:"left",width:250},
  {title:"Folio", field:'folio', hozAlign:"right", formatter:"link", formatterParams:{
    url:function(cell){return "https://app.linkaform.com/#/records/detail/" + cell.getData().record_id}, 
    target:"_blank",},  headerTooltip:true,width:100},
];


var columsTable2 = [
  { title:"EBC", field:'ebc',hozAlign:"left",width:250},
  { title:"Provincia", field:'provincia',hozAlign:"left",width:250},
  { title:"Canton ", field:'canton',hozAlign:"left",width:250},
  { title:"Fecha de obtención permiso ", field:'fecha_permiso',hozAlign:"left",width:250},
  { title:"Proxima inspeccion ", field:'fecha_inspeccion',hozAlign:"left",width:250},
  { title:"Días para vencimiento", field:'dias_vencimiento',hozAlign:"right",width:250},
  { title:"", field:'color_status', formatter:"color", hozAlign:"right",width:50},
];


var dataTable1 = [
  {
    ebc: 'ELPANGUI',
    provincia: 'ZAMORA CHINCHIPE',
    canton: 'El Pangui',
    fecha_permiso: '5/12/2014',
    fecha_inspeccion: '25/1/2023',
    folio: '140-11665',
  },
    {
    ebc: 'JAMACITY',
    provincia: 'MANABI',
    canton: 'Jama',
    fecha_permiso: '5/8/2020',
    fecha_inspeccion: '26/1/2023',
    folio: '141-11665',
  },
    {
    ebc: 'SARACAYORO',
    provincia: 'EL ORO',
    canton: 'Pinas',
    fecha_permiso: '23/02/2016',
    fecha_inspeccion: '27/1/2023',
    folio: '142-11665',
  },
    {
    ebc: 'ELPANGUI',
    provincia: 'ZAMORA CHINCHIPE',
    canton: 'El Pangui',
    fecha_permiso: '5/12/2014',
    fecha_inspeccion: '25/1/2023',
    folio: '140-11665',
  },
    {
    ebc: 'JAMACITY',
    provincia: 'MANABI',
    canton: 'Jama',
    fecha_permiso: '5/8/2020',
    fecha_inspeccion: '26/1/2023',
    folio: '141-11665',
  },
    {
    ebc: 'SARACAYORO',
    provincia: 'EL ORO',
    canton: 'Pinas',
    fecha_permiso: '23/02/2016',
    fecha_inspeccion: '27/1/2023',
    folio: '142-11665',
  },
    {
    ebc: 'ELPANGUI',
    provincia: 'ZAMORA CHINCHIPE',
    canton: 'El Pangui',
    fecha_permiso: '5/12/2014',
    fecha_inspeccion: '25/1/2023',
    folio: '140-11665',
  },
    {
    ebc: 'JAMACITY',
    provincia: 'MANABI',
    canton: 'Jama',
    fecha_permiso: '5/8/2020',
    fecha_inspeccion: '26/1/2023',
    folio: '141-11665',
  },
    {
    ebc: 'SARACAYORO',
    provincia: 'EL ORO',
    canton: 'Pinas',
    fecha_permiso: '23/02/2016',
    fecha_inspeccion: '27/1/2023',
    folio: '142-11665',
  },

];

var dataTable2 = [
  {
    ebc: 'ELPANGUI',
    provincia: 'ZAMORA CHINCHIPE',
    canton: 'El Pangui',
    fecha_permiso: '5/12/2014',
    fecha_inspeccion: '25/1/2023',
    folio: '140-11665',
    dias_vencimiento: '-5',
    color_status: '#E74C3C',
  },
    {
    ebc: 'JAMACITY',
    provincia: 'MANABI',
    canton: 'Jama',
    fecha_permiso: '5/8/2020',
    fecha_inspeccion: '26/1/2023',
    folio: '141-11665',
    dias_vencimiento: '5',
    color_status: '#F4D03F',
  },
    {
    ebc: 'SARACAYORO',
    provincia: 'EL ORO',
    canton: 'Pinas',
    fecha_permiso: '23/02/2016',
    fecha_inspeccion: '27/1/2023',
    folio: '142-11665',
    dias_vencimiento: '15',
    color_status: '#2ECC71',
  },
    {
    ebc: 'ELPANGUI',
    provincia: 'ZAMORA CHINCHIPE',
    canton: 'El Pangui',
    fecha_permiso: '5/12/2014',
    fecha_inspeccion: '25/1/2023',
    folio: '140-11665',
    dias_vencimiento: '-5',
    color_status: '#E74C3C',
  },
    {
    ebc: 'JAMACITY',
    provincia: 'MANABI',
    canton: 'Jama',
    fecha_permiso: '5/8/2020',
    fecha_inspeccion: '26/1/2023',
    folio: '141-11665',
    dias_vencimiento: '5',
    color_status: '#F4D03F',
  },
    {
    ebc: 'SARACAYORO',
    provincia: 'EL ORO',
    canton: 'Pinas',
    fecha_permiso: '23/02/2016',
    fecha_inspeccion: '27/1/2023',
    folio: '142-11665',
    dias_vencimiento: '15',
    color_status: '#2ECC71',
  },
    {
    ebc: 'ELPANGUI',
    provincia: 'ZAMORA CHINCHIPE',
    canton: 'El Pangui',
    fecha_permiso: '5/12/2014',
    fecha_inspeccion: '25/1/2023',
    folio: '140-11665',
    dias_vencimiento: '-5',
    color_status: '#E74C3C',
  },
    {
    ebc: 'JAMACITY',
    provincia: 'MANABI',
    canton: 'Jama',
    fecha_permiso: '5/8/2020',
    fecha_inspeccion: '26/1/2023',
    folio: '141-11665',
    dias_vencimiento: '5',
    color_status: '#F4D03F',
  },
    {
    ebc: 'SARACAYORO',
    provincia: 'EL ORO',
    canton: 'Pinas',
    fecha_permiso: '23/02/2016',
    fecha_inspeccion: '27/1/2023',
    folio: '142-11665',
    dias_vencimiento: '15',
    color_status: '#2ECC71',
  },
    {
    ebc: 'ELPANGUI',
    provincia: 'ZAMORA CHINCHIPE',
    canton: 'El Pangui',
    fecha_permiso: '5/12/2014',
    fecha_inspeccion: '25/1/2023',
    folio: '140-11665',
    dias_vencimiento: '-5',
    color_status: '#E74C3C',
  },
    {
    ebc: 'JAMACITY',
    provincia: 'MANABI',
    canton: 'Jama',
    fecha_permiso: '5/8/2020',
    fecha_inspeccion: '26/1/2023',
    folio: '141-11665',
    dias_vencimiento: '5',
    color_status: '#F4D03F',
  },
    {
    ebc: 'SARACAYORO',
    provincia: 'EL ORO',
    canton: 'Pinas',
    fecha_permiso: '23/02/2016',
    fecha_inspeccion: '27/1/2023',
    folio: '142-11665',
    dias_vencimiento: '15',
    color_status: '#2ECC71',
  },
];
