var array_background = getPAlleteColors(4,4);
console.log(array_background)
var array_background = getPAlleteColors(6,4);
console.log(array_background)
var array_background = getPAlleteColors(7,4);
console.log(array_background)



var array_background = getPAlleteColors(10,12);
console.log(array_background)

//--Table Montajes Por Mes


var columsTable1 = [
  { title:"Folio", field:'folio', hozAlign:"left", formatter:"link", formatterParams:{
  url:function(cell){return "https://app.linkaform.com/#/records/detail/" + cell.getData().record_id}, 
  target:"_blank",}, width:150},
  { title:"Cordon", field:'cordon',hozAlign:"left",width:250},
  { title:"Num Dispositivo", field:'num_dispositivo',hozAlign:"left",width:250},
  { title:"Tipo de Control", field:'tipo_control',hozAlign:"left",width:250},
  { title:"Criterio de cambio", field:'criterio_cambio',hozAlign:"left",width:250},
  { title:"Condicion Dispositivo", field:'condicion_dispositivo',hozAlign:"left",width:250},
  { title:"Actividad", field:'actividad',hozAlign:"left",width:250},
  { title:"Rata", field:'rata',hozAlign:"left",width:250},
  { title:"Raton", field:'raton',hozAlign:"left",width:250},
  { title:"Cucaracha", field:'cucaracha',hozAlign:"left",width:250},
  { title:"Hormiga", field:'hormiga',hozAlign:"left",width:250},
  { title:"Aves", field:'aves',hozAlign:"left",width:250},
  { title:"Grillo", field:'grillo',hozAlign:"left",width:250},
  { title:"Hormiga carpintera", field:'hormiga_carpintera',hozAlign:"left",width:250},
  { title:"Tijerilla", field:'tijerilla',hozAlign:"left",width:250},
  { title:"Pescadito plata", field:'pescadito_plata',hozAlign:"left",width:250},
  { title:"Pulga", field:'pulga',hozAlign:"left",width:250},
  { title:"Chinche cama", field:'chinche_cama',hozAlign:"left",width:250},
  { title:"Mosca", field:'mosca',hozAlign:"left",width:250},
  { title:"Mosquito", field:'mosquito',hozAlign:"left",width:250},
  { title:"Palomilla", field:'palomilla',hozAlign:"left",width:250},
  { title:"Gorgojo", field:'gorgojo',hozAlign:"left",width:250},
  { title:"Escarabajo", field:'escarabajo',hozAlign:"left",width:250},
  { title:"Termita subterranea", field:'termita_subterranea',hozAlign:"left",width:250},
  { title:"Caracol", field:'caracol',hozAlign:"left",width:250},
  { title:"Otra plaga", field:'otra_plaga',hozAlign:"left",width:250},
];

var dataTable1 = [
  {
    folio:'100001',
    num_dispositivo:'1',
    status:'Status Example',
    status_bulbo:'Status Example',
    condicion_dispositivo:'Condición Dispositivo',
    cambio_trampa:'Cambio',
    cambio_bulbo:'Cambio',
    mosca_domestica:'10',
    mosca_fruta:'10',
    mosca_drenaje:'10',
    mosca_metalica:'10',
    mariposa:'10',
    gorgojos:'10',
    chicharrita:'10',
    abejas:'10',
    avispas:'10',
    mosquito:'10',
    mariquita:'10',
    otras_plagas:'10',
    descripcion:'Ninguna',
    realizada:'10',
  },
  {
    folio:'100001',
    num_dispositivo:'1',
    status:'Status Example',
    status_bulbo:'Status Example',
    condicion_dispositivo:'Condición Dispositivo',
    cambio_trampa:'Cambio',
    cambio_bulbo:'Cambio',
    mosca_domestica:'10',
    mosca_fruta:'10',
    mosca_drenaje:'10',
    mosca_metalica:'10',
    mariposa:'10',
    gorgojos:'10',
    chicharrita:'10',
    abejas:'10',
    avispas:'10',
    mosquito:'10',
    mariquita:'10',
    otras_plagas:'10',
    descripcion:'Ninguna',
    realizada:'10',
  },
  {
    folio:'100001',
    num_dispositivo:'1',
    status:'Status Example',
    status_bulbo:'Status Example',
    condicion_dispositivo:'Condición Dispositivo',
    cambio_trampa:'Cambio',
    cambio_bulbo:'Cambio',
    mosca_domestica:'10',
    mosca_fruta:'10',
    mosca_drenaje:'10',
    mosca_metalica:'10',
    mariposa:'10',
    gorgojos:'10',
    chicharrita:'10',
    abejas:'10',
    avispas:'10',
    mosquito:'10',
    mariquita:'10',
    otras_plagas:'10',
    descripcion:'Ninguna',
    realizada:'10',
  },
  {
    folio:'100001',
    num_dispositivo:'1',
    status:'Status Example',
    status_bulbo:'Status Example',
    condicion_dispositivo:'Condición Dispositivo',
    cambio_trampa:'Cambio',
    cambio_bulbo:'Cambio',
    mosca_domestica:'10',
    mosca_fruta:'10',
    mosca_drenaje:'10',
    mosca_metalica:'10',
    mariposa:'10',
    gorgojos:'10',
    chicharrita:'10',
    abejas:'10',
    avispas:'10',
    mosquito:'10',
    mariquita:'10',
    otras_plagas:'10',
    descripcion:'Ninguna',
    realizada:'10',
  },
  {
    folio:'100001',
    num_dispositivo:'1',
    status:'Status Example',
    status_bulbo:'Status Example',
    condicion_dispositivo:'Condición Dispositivo',
    cambio_trampa:'Cambio',
    cambio_bulbo:'Cambio',
    mosca_domestica:'10',
    mosca_fruta:'10',
    mosca_drenaje:'10',
    mosca_metalica:'10',
    mariposa:'10',
    gorgojos:'10',
    chicharrita:'10',
    abejas:'10',
    avispas:'10',
    mosquito:'10',
    mariquita:'10',
    otras_plagas:'10',
    descripcion:'Ninguna',
    realizada:'10',
  },
  {
    folio:'100001',
    num_dispositivo:'1',
    status:'Status Example',
    status_bulbo:'Status Example',
    condicion_dispositivo:'Condición Dispositivo',
    cambio_trampa:'Cambio',
    cambio_bulbo:'Cambio',
    mosca_domestica:'10',
    mosca_fruta:'10',
    mosca_drenaje:'10',
    mosca_metalica:'10',
    mariposa:'10',
    gorgojos:'10',
    chicharrita:'10',
    abejas:'10',
    avispas:'10',
    mosquito:'10',
    mariquita:'10',
    otras_plagas:'10',
    descripcion:'Ninguna',
    realizada:'10',
  },
  {
    folio:'100001',
    num_dispositivo:'1',
    status:'Status Example',
    status_bulbo:'Status Example',
    condicion_dispositivo:'Condición Dispositivo',
    cambio_trampa:'Cambio',
    cambio_bulbo:'Cambio',
    mosca_domestica:'10',
    mosca_fruta:'10',
    mosca_drenaje:'10',
    mosca_metalica:'10',
    mariposa:'10',
    gorgojos:'10',
    chicharrita:'10',
    abejas:'10',
    avispas:'10',
    mosquito:'10',
    mariquita:'10',
    otras_plagas:'10',
    descripcion:'Ninguna',
    realizada:'10',
  },
  {
    folio:'100001',
    num_dispositivo:'1',
    status:'Status Example',
    status_bulbo:'Status Example',
    condicion_dispositivo:'Condición Dispositivo',
    cambio_trampa:'Cambio',
    cambio_bulbo:'Cambio',
    mosca_domestica:'10',
    mosca_fruta:'10',
    mosca_drenaje:'10',
    mosca_metalica:'10',
    mariposa:'10',
    gorgojos:'10',
    chicharrita:'10',
    abejas:'10',
    avispas:'10',
    mosquito:'10',
    mariquita:'10',
    otras_plagas:'10',
    descripcion:'Ninguna',
    realizada:'10',
  },
  {
    folio:'100001',
    num_dispositivo:'1',
    status:'Status Example',
    status_bulbo:'Status Example',
    condicion_dispositivo:'Condición Dispositivo',
    cambio_trampa:'Cambio',
    cambio_bulbo:'Cambio',
    mosca_domestica:'10',
    mosca_fruta:'10',
    mosca_drenaje:'10',
    mosca_metalica:'10',
    mariposa:'10',
    gorgojos:'10',
    chicharrita:'10',
    abejas:'10',
    avispas:'10',
    mosquito:'10',
    mariquita:'10',
    otras_plagas:'10',
    descripcion:'Ninguna',
    realizada:'10',
  },
  {
    folio:'100001',
    num_dispositivo:'1',
    status:'Status Example',
    status_bulbo:'Status Example',
    condicion_dispositivo:'Condición Dispositivo',
    cambio_trampa:'Cambio',
    cambio_bulbo:'Cambio',
    mosca_domestica:'10',
    mosca_fruta:'10',
    mosca_drenaje:'10',
    mosca_metalica:'10',
    mariposa:'10',
    gorgojos:'10',
    chicharrita:'10',
    abejas:'10',
    avispas:'10',
    mosquito:'10',
    mariquita:'10',
    otras_plagas:'10',
    descripcion:'Ninguna',
    realizada:'10',
  },
];


var data1 = {
  labels: ['2022-12-01','2022-12-08','2022-12-15','2022-12-25','2023-01-03'],
  datasets: [
    {
      label: 'Volador 1',
      data: [25,10,20,25,20],
      borderColor: "#264653",
      fill: false
    },
        {
      label: 'Volador 1',
      data: [5,52,11,85,65],
      borderColor: "#1b747c",
      fill: false
    },
        {
      label: 'Volador 1',
      data: [12,4,20,54,30],
      borderColor: "#26988e",
      fill: false
    },
        {
      label: 'Volador 1',
      data: [15,20,30,45,50],
      borderColor: "#1c7c81",
      fill: false
    },
  ]
};



var setOptions1 = {
  responsive: true,
  plugins: {
    legend: {
      display: true,
      position: 'top',
    },
    title: {
        display: true,
        text: 'Reporte de Tendencia Por Roedores',
        font: {
          size: 25
        }
    },
    datalabels: {
      color: 'white',
    }
  },
  scales: {
    y:{
      ticks: {
        stepSize: 1
      }, 
    }
  },
};