
var columsTable1 = [
  {title:"Folio", field:'folio', hozAlign:"right", formatter:"link", formatterParams:{
  url:function(cell){return "https://app.linkaform.com/#/records/detail/" + cell.getData().record_id}, 
  target:"_blank",}, width:100},
  { title:"Store ID", field:'store_id',hozAlign:"right",width:200},
  { title:"Merchant", field:'merchant',hozAlign:"left",width:300},
  { title:"Store", field:'store',hozAlign:"left",width:300},
  { title:"Promotor", field:'promotor',hozAlign:"left",width:300},
  { title:"Fecha", field:'fecha_creacion',hozAlign:"center",width:150},
  { title:"Hora", field:'hora',hozAlign:"center",width:150},

  { title:"Acceso al portal (usuario y contraseña)", field:'pregunta_1',hozAlign:"left",width:300},
  { title:"Cómo el cliente crea su cuenta en KueskiPay ", field:'pregunta_2',hozAlign:"left",width:300},
  { title:"Cómo el cliente usa KueskiPay para pagar  ", field:'pregunta_3',hozAlign:"left",width:300},
  { title:"Como el vendedor/asesor usa KueskiPay para cobrar ", field:'pregunta_4',hozAlign:"left",width:300},
  { title:"Términos y condiciones de las promociones vigentes", field:'pregunta_5',hozAlign:"left",width:300},
  { title:"Cómo el cliente usa un cupón de descuento ", field:'pregunta_6',hozAlign:"left",width:300},
  { title:"Ventajas competitivas, beneficios y características de KueskiPay  ", field:'pregunta_7',hozAlign:"left",width:300},
  { title:"Compartir los datos de soporte telefónico ", field:'pregunta_8',hozAlign:"left",width:300},
  { title:"Canales de comunicación oficiales (WA, correo, etc.)", field:'pregunta_9',hozAlign:"left",width:300},
  {
    title:"Material publicitario disponible de Kuesk",
    columns:[
      { title:"Sticker de Ventana", field:'pregunta_11A',hozAlign:"left",width:300},
      { title:"Stickers para piso de venta", field:'pregunta_11B',hozAlign:"left",width:300},
      { title:"Banner Mini", field:'pregunta_11C',hozAlign:"left",width:300},
      { title:"Otro: Especificar", field:'pregunta_11D',hozAlign:"left",width:300},
    ],
  },
  {
    title:"¿Dónde hay presencia de material de Kueski?",
    columns:[
      { title:"En la entrada", field:'pregunta_12A',hozAlign:"left",width:300},
      { title:"En caja", field:'pregunta_12B',hozAlign:"left",width:300},
      { title:"Piso de venta (colgadores, paredes, espejos, etc)", field:'pregunta_12C',hozAlign:"left",width:300},
      { title:"Vestidores", field:'pregunta_12D',hozAlign:"left",width:300},
      { title:"Portados por el personal (botones, gafetes, ropa, etc)", field:'pregunta_12E',hozAlign:"left",width:300},
    ],
  },

  {
    title:"Material publicitario básico disponible de Aplazo",
    columns:[
      { title:"Sticker de Ventana", field:'pregunta_13A',hozAlign:"left",width:300},
      { title:"Stickers para piso de venta", field:'pregunta_13B',hozAlign:"left",width:300},
      { title:"Banner Mini", field:'pregunta_13C',hozAlign:"left",width:300},
      { title:"Otro", field:'pregunta_13D',hozAlign:"left",width:300},
    ],
  },
  {
    title:"Donde hay presencia de material de Aplazo",
    columns:[
      { title:"En la entrada", field:'pregunta_14A',hozAlign:"left",width:300},
      { title:"En caja", field:'pregunta_14B',hozAlign:"left",width:300},
      { title:"Vestidores", field:'pregunta_14C',hozAlign:"left",width:300},
      { title:"Portados por el personal (botones, gafetes, ropa, etc)", field:'pregunta_14D',hozAlign:"left",width:300},
      { title:"Otro", field:'pregunta_14E',hozAlign:"left",width:300},
    ],
  },
  { title:"Describe las fallas o bugs que encontraste en tu visita y cómo se resolvieron Si no hubo ninguna omite esta pregunta", field:'pregunta_15',hozAlign:"left",width:300},
  { title:"En tu visita, ¿Qué obstáculos y/o retos tiene la tienda?", field:'pregunta_16',hozAlign:"left",width:300},
  { title:"Comparte tus comentarios adicionales", field:'pregunta_17',hozAlign:"left",width:300},
  {
    title:"¿Hay Material Publicitario de Kueski?",
    columns:[
      { title:"Sí", field:'pregunta_15A',hozAlign:"left",width:300},
      { title:"No", field:'pregunta_15B',hozAlign:"left",width:300},
    ],
  },
  {
    title:"¿Dónde hay presencia de material de Kueski?",
    columns:[
      { title:"En la entrada", field:'pregunta_16A',hozAlign:"left",width:300},
      { title:"En caja", field:'pregunta_16B',hozAlign:"left",width:300},
      { title:"Vestidores", field:'pregunta_16C',hozAlign:"left",width:300},
      { title:"Portados por el personal (botones, gafetes, ropa, etc)", field:'pregunta_16D',hozAlign:"left",width:300},
      { title:"Otro", field:'pregunta_16E',hozAlign:"left",width:300},
    ],
  },
  {
    title:"Material Publicitario Disponible de Kueski",
    columns:[
      { title:"Banner ( Cualquier tipo y Tamaño)", field:'pregunta_17A',hozAlign:"left",width:300},
      { title:"Sticker ( Cualquier tipo y Tamaño)", field:'pregunta_17B',hozAlign:"left",width:300},
      { title:"Lona ( Cualquier tipo y Tamaño)", field:'pregunta_17C',hozAlign:"left",width:300},
      { title:"Pantalla", field:'pregunta_17D',hozAlign:"left",width:300},
      { title:"Otro", field:'pregunta_17E',hozAlign:"left",width:300},
    ],
  },
  {
    title:"¿Dejaste material publicitario?",
    columns:[
      { title:"Sí", field:'pregunta_18A',hozAlign:"left",width:300},
      { title:"No", field:'pregunta_18B',hozAlign:"left",width:300},
    ],
  },
  {
    title:"¿ Por que ?",
    columns:[
      { title:"No contaba con material", field:'pregunta_19A',hozAlign:"left",width:300},
      { title:"No me permitieron", field:'pregunta_19B',hozAlign:"left",width:300},
    ],
  },
  {
    title:"¿Hay material publicitario de aplazo?",
    columns:[
      { title:"Sí", field:'pregunta_20A',hozAlign:"left",width:300},
      { title:"No", field:'pregunta_20B',hozAlign:"left",width:300},
    ],
  },
  {
    title:"¿Dónde hay presencia de material de aplazo?",
    columns:[
      { title:"Entrada", field:'pregunta_21A',hozAlign:"left",width:300},
      { title:"Caja", field:'pregunta_21B',hozAlign:"left",width:300},
      { title:"Piso de venta (mesas exhibición, paredes, espejos, etc)", field:'pregunta_21C',hozAlign:"left",width:300},
      { title:"Portados por el personal (botones, gafetes, ropa, etc)", field:'pregunta_21D',hozAlign:"left",width:300},
    ],
  },
  {
    title:"¿Dónde hay presencia de material de aplazo?",
    columns:[
      { title:"Entrada", field:'pregunta_21A',hozAlign:"left",width:300},
      { title:"Caja", field:'pregunta_21B',hozAlign:"left",width:300},
      { title:"Piso de venta (mesas exhibición, paredes, espejos, etc)", field:'pregunta_21C',hozAlign:"left",width:300},
      { title:"Portados por el personal (botones, gafetes, ropa, etc)", field:'pregunta_21D',hozAlign:"left",width:300},
    ],
  },
  {
    title:"Material publicitario disponible de aplazo",
    columns:[
      { title:"Banner (cualquier tipo y tamaño", field:'pregunta_21A',hozAlign:"left",width:300},
      { title:"Sticker (cualquier tipo tipo y tamaño)", field:'pregunta_21B',hozAlign:"left",width:300},
      { title:"Lona (cualquier tipo tipo y tamaño)", field:'pregunta_21C',hozAlign:"left",width:300},
      { title:"Portados por el personal (botones, gafetes, ropa, etc)", field:'pregunta_21D',hozAlign:"left",width:300},
      { title:"Pantalla", field:'pregunta_21E',hozAlign:"left",width:300},
      { title:"Otro", field:'pregunta_21F',hozAlign:"left",width:300},
    ],
  },
];




var dataTable1 = [
  {
    "folio": "850-11702", 
    "record_id": "63eaed385a3ef7414d4899da", 
    "store_id": "1209250816961081402", 
    "merchant": "Calvin Klein Instore", 
    "store": "Ck Parque Lindavista", 
    "promotor": "Alberto Torres",
    "fecha": "2023-02-14", 
    "hora": " 08:08:45", 
    "pregunta_1": 'Tuve que capacitar desde cero',
    "pregunta_2": 'Resolvi unas cuantas dudas',
    "pregunta_3": 'El staff de la tienda domina el tema o no tiene problemas',
    "pregunta_4": 'Resolvi unas cuantas dudas',
    "pregunta_5": 'El staff de la tienda domina el tema o no tiene problemas',
    "pregunta_6": 'Tuve que capacitar desde cero',
    "pregunta_7": 'Tuve que capacitar desde cero',
    "pregunta_8": 'Resolvi unas cuantas dudas',
    "pregunta_9": 'Resolvi unas cuantas dudas',
    "pregunta_11A": 'Sticker de Ventana',
    "pregunta_11B": '',
    "pregunta_11C": '',
    "pregunta_11D": '',
    "pregunta_12A": '',
    "pregunta_12B": '',
    "pregunta_12C": 'Piso de venta (colgadores, paredes, espejos, etc)',
    "pregunta_12D": '',
    "pregunta_12E": '',
    "pregunta_13A": '',
    "pregunta_13B": 'pregunta_13B',
    "pregunta_13C": '',
    "pregunta_13D": '',
    "pregunta_14A": '',
    "pregunta_14B": 'pregunta_14B',
    "pregunta_14C": '',
    "pregunta_14D": '',
    "pregunta_14E": '',
    "pregunta_15A": 'Sí',
    "pregunta_15B": '',
    "pregunta_16A": '',
    "pregunta_16B": '',
    "pregunta_16C": 'Vestidores',
    "pregunta_16D": '',
    "pregunta_16E": '',
    "pregunta_17A": 'Banner ( Cualquier tipo y Tamaño)',
    "pregunta_17B": '',
    "pregunta_17C": '',
    "pregunta_17D": '',
    "pregunta_17E": '',
    "pregunta_18A": 'Sí',
    "pregunta_18B": '',
    "pregunta_19A": 'No contaba con material',
    "pregunta_19B": '',
    "pregunta_20A": 'Sí',
    "pregunta_20B": '',
    "pregunta_21A": '',
    "pregunta_21B": 'Caja',
    "pregunta_21C": '',
    "pregunta_21D": '',
    "pregunta_21A": '',
    "pregunta_21B": '',
    "pregunta_21C": 'Piso de venta (mesas exhibición, paredes, espejos, etc)',
    "pregunta_21D": '',
    "pregunta_21A": '',
    "pregunta_21B": '',
    "pregunta_21C": '',
    "pregunta_21D": '',
    "pregunta_21E": '',
    "pregunta_21F": '',
  }, 
    {
    "folio": "850-11702", 
    "record_id": "63eaed385a3ef7414d4899da", 
    "store_id": "1209250816961081402", 
    "merchant": "Calvin Klein Instore", 
    "store": "Ck Parque Lindavista", 
    "promotor": "Alberto Torres",
    "fecha": "2023-02-14", 
    "hora": " 08:08:45", 
    "pregunta_1": 'Tuve que capacitar desde cero',
    "pregunta_2": 'Resolvi unas cuantas dudas',
    "pregunta_3": 'El staff de la tienda domina el tema o no tiene problemas',
    "pregunta_4": 'Resolvi unas cuantas dudas',
    "pregunta_5": 'El staff de la tienda domina el tema o no tiene problemas',
    "pregunta_6": 'Tuve que capacitar desde cero',
    "pregunta_7": 'Tuve que capacitar desde cero',
    "pregunta_8": 'Resolvi unas cuantas dudas',
    "pregunta_9": 'Resolvi unas cuantas dudas',
    "pregunta_11A": 'Sticker de Ventana',
    "pregunta_11B": '',
    "pregunta_11C": '',
    "pregunta_11D": '',
    "pregunta_12A": 'En la entrada',
    "pregunta_12B": '',
    "pregunta_12C": '',
    "pregunta_12D": '',
    "pregunta_12E": '',
    "pregunta_13A": '',
    "pregunta_13B": 'Stickers para piso de venta',
    "pregunta_13C": '',
    "pregunta_13D": '',
    "pregunta_14A": '',
    "pregunta_14B": '',
    "pregunta_14C": '',
    "pregunta_14D": 'Portados por el personal (botones, gafetes, ropa, etc)',
    "pregunta_14E": '',
    "pregunta_15A": '',
    "pregunta_15B": '',
    "pregunta_16A": '',
    "pregunta_16B": '',
    "pregunta_16C": '',
    "pregunta_16D": 'En tu visita, ¿Qué obstáculos y/o retos tiene la tienda?',
    "pregunta_16E": '',
    "pregunta_17A": 'Banner ( Cualquier tipo y Tamaño)',
    "pregunta_17B": '',
    "pregunta_17C": '',
    "pregunta_17D": '',
    "pregunta_17E": '',
    "pregunta_18A": 'Sí',
    "pregunta_18B": '',
    "pregunta_19A": 'No contaba con material',
    "pregunta_19B": '',
    "pregunta_20A": 'Sí',
    "pregunta_20B": '',
    "pregunta_21A": '',
    "pregunta_21B": '',
    "pregunta_21C": 'Piso de venta (mesas exhibición, paredes, espejos, etc)',
    "pregunta_21D": '',
    "pregunta_21A": '',
    "pregunta_21B": '',
    "pregunta_21C": '',
    "pregunta_21D": 'Portados por el personal (botones, gafetes, ropa, etc)',
    "pregunta_21A": 'Banner (cualquier tipo y tamaño',
    "pregunta_21B": '',
    "pregunta_21C": '',
    "pregunta_21D": '',
    "pregunta_21E": '',
    "pregunta_21F": '',
  },
  {
    "folio": "850-11702", 
    "record_id": "63eaed385a3ef7414d4899da", 
    "store_id": "1209250816961081402", 
    "merchant": "Calvin Klein Instore", 
    "store": "Ck Parque Lindavista", 
    "promotor": "Alberto Torres",
    "fecha": "2023-02-14", 
    "hora": " 08:08:45", 
    "pregunta_1": 'Tuve que capacitar desde cero',
    "pregunta_2": 'Resolvi unas cuantas dudas',
    "pregunta_3": 'El staff de la tienda domina el tema o no tiene problemas',
    "pregunta_4": 'Resolvi unas cuantas dudas',
    "pregunta_5": 'El staff de la tienda domina el tema o no tiene problemas',
    "pregunta_6": 'Tuve que capacitar desde cero',
    "pregunta_7": 'Tuve que capacitar desde cero',
    "pregunta_8": 'Resolvi unas cuantas dudas',
    "pregunta_9": 'Resolvi unas cuantas dudas',
    "pregunta_11A": 'Sticker de Ventana',
    "pregunta_11B": '',
    "pregunta_11C": '',
    "pregunta_11D": '',
    "pregunta_12A": '',
    "pregunta_12B": '',
    "pregunta_12C": 'Piso de venta (colgadores, paredes, espejos, etc)',
    "pregunta_12D": '',
    "pregunta_12E": '',
    "pregunta_13A": '',
    "pregunta_13B": 'pregunta_13B',
    "pregunta_13C": '',
    "pregunta_13D": '',
    "pregunta_14A": '',
    "pregunta_14B": 'pregunta_14B',
    "pregunta_14C": '',
    "pregunta_14D": '',
    "pregunta_14E": '',
    "pregunta_15A": 'Sí',
    "pregunta_15B": '',
    "pregunta_16A": '',
    "pregunta_16B": '',
    "pregunta_16C": 'Vestidores',
    "pregunta_16D": '',
    "pregunta_16E": '',
    "pregunta_17A": 'Banner ( Cualquier tipo y Tamaño)',
    "pregunta_17B": '',
    "pregunta_17C": '',
    "pregunta_17D": '',
    "pregunta_17E": '',
    "pregunta_18A": 'Sí',
    "pregunta_18B": '',
    "pregunta_19A": 'No contaba con material',
    "pregunta_19B": '',
    "pregunta_20A": 'Sí',
    "pregunta_20B": '',
    "pregunta_21A": '',
    "pregunta_21B": 'Caja',
    "pregunta_21C": '',
    "pregunta_21D": '',
    "pregunta_21A": '',
    "pregunta_21B": '',
    "pregunta_21C": 'Piso de venta (mesas exhibición, paredes, espejos, etc)',
    "pregunta_21D": '',
    "pregunta_21A": '',
    "pregunta_21B": '',
    "pregunta_21C": '',
    "pregunta_21D": '',
    "pregunta_21E": '',
    "pregunta_21F": '',
  }, 
    {
    "folio": "850-11702", 
    "record_id": "63eaed385a3ef7414d4899da", 
    "store_id": "1209250816961081402", 
    "merchant": "Calvin Klein Instore", 
    "store": "Ck Parque Lindavista", 
    "promotor": "Alberto Torres",
    "fecha": "2023-02-14", 
    "hora": " 08:08:45", 
    "pregunta_1": 'Tuve que capacitar desde cero',
    "pregunta_2": 'Resolvi unas cuantas dudas',
    "pregunta_3": 'El staff de la tienda domina el tema o no tiene problemas',
    "pregunta_4": 'Resolvi unas cuantas dudas',
    "pregunta_5": 'El staff de la tienda domina el tema o no tiene problemas',
    "pregunta_6": 'Tuve que capacitar desde cero',
    "pregunta_7": 'Tuve que capacitar desde cero',
    "pregunta_8": 'Resolvi unas cuantas dudas',
    "pregunta_9": 'Resolvi unas cuantas dudas',
    "pregunta_11A": 'Sticker de Ventana',
    "pregunta_11B": '',
    "pregunta_11C": '',
    "pregunta_11D": '',
    "pregunta_12A": 'En la entrada',
    "pregunta_12B": '',
    "pregunta_12C": '',
    "pregunta_12D": '',
    "pregunta_12E": '',
    "pregunta_13A": '',
    "pregunta_13B": 'Stickers para piso de venta',
    "pregunta_13C": '',
    "pregunta_13D": '',
    "pregunta_14A": '',
    "pregunta_14B": '',
    "pregunta_14C": '',
    "pregunta_14D": 'Portados por el personal (botones, gafetes, ropa, etc)',
    "pregunta_14E": '',
    "pregunta_15A": '',
    "pregunta_15B": '',
    "pregunta_16A": '',
    "pregunta_16B": '',
    "pregunta_16C": '',
    "pregunta_16D": 'En tu visita, ¿Qué obstáculos y/o retos tiene la tienda?',
    "pregunta_16E": '',
    "pregunta_17A": 'Banner ( Cualquier tipo y Tamaño)',
    "pregunta_17B": '',
    "pregunta_17C": '',
    "pregunta_17D": '',
    "pregunta_17E": '',
    "pregunta_18A": 'Sí',
    "pregunta_18B": '',
    "pregunta_19A": 'No contaba con material',
    "pregunta_19B": '',
    "pregunta_20A": 'Sí',
    "pregunta_20B": '',
    "pregunta_21A": '',
    "pregunta_21B": '',
    "pregunta_21C": 'Piso de venta (mesas exhibición, paredes, espejos, etc)',
    "pregunta_21D": '',
    "pregunta_21A": '',
    "pregunta_21B": '',
    "pregunta_21C": '',
    "pregunta_21D": 'Portados por el personal (botones, gafetes, ropa, etc)',
    "pregunta_21A": 'Banner (cualquier tipo y tamaño',
    "pregunta_21B": '',
    "pregunta_21C": '',
    "pregunta_21D": '',
    "pregunta_21E": '',
    "pregunta_21F": '',
  }, 
  {
    "folio": "850-11702", 
    "record_id": "63eaed385a3ef7414d4899da", 
    "store_id": "1209250816961081402", 
    "merchant": "Calvin Klein Instore", 
    "store": "Ck Parque Lindavista", 
    "promotor": "Alberto Torres",
    "fecha": "2023-02-14", 
    "hora": " 08:08:45", 
    "pregunta_1": 'Tuve que capacitar desde cero',
    "pregunta_2": 'Resolvi unas cuantas dudas',
    "pregunta_3": 'El staff de la tienda domina el tema o no tiene problemas',
    "pregunta_4": 'Resolvi unas cuantas dudas',
    "pregunta_5": 'El staff de la tienda domina el tema o no tiene problemas',
    "pregunta_6": 'Tuve que capacitar desde cero',
    "pregunta_7": 'Tuve que capacitar desde cero',
    "pregunta_8": 'Resolvi unas cuantas dudas',
    "pregunta_9": 'Resolvi unas cuantas dudas',
    "pregunta_11A": 'Sticker de Ventana',
    "pregunta_11B": '',
    "pregunta_11C": '',
    "pregunta_11D": '',
    "pregunta_12A": '',
    "pregunta_12B": '',
    "pregunta_12C": 'Piso de venta (colgadores, paredes, espejos, etc)',
    "pregunta_12D": '',
    "pregunta_12E": '',
    "pregunta_13A": '',
    "pregunta_13B": 'pregunta_13B',
    "pregunta_13C": '',
    "pregunta_13D": '',
    "pregunta_14A": '',
    "pregunta_14B": 'pregunta_14B',
    "pregunta_14C": '',
    "pregunta_14D": '',
    "pregunta_14E": '',
    "pregunta_15A": 'Sí',
    "pregunta_15B": '',
    "pregunta_16A": '',
    "pregunta_16B": '',
    "pregunta_16C": 'Vestidores',
    "pregunta_16D": '',
    "pregunta_16E": '',
    "pregunta_17A": 'Banner ( Cualquier tipo y Tamaño)',
    "pregunta_17B": '',
    "pregunta_17C": '',
    "pregunta_17D": '',
    "pregunta_17E": '',
    "pregunta_18A": 'Sí',
    "pregunta_18B": '',
    "pregunta_19A": 'No contaba con material',
    "pregunta_19B": '',
    "pregunta_20A": 'Sí',
    "pregunta_20B": '',
    "pregunta_21A": '',
    "pregunta_21B": 'Caja',
    "pregunta_21C": '',
    "pregunta_21D": '',
    "pregunta_21A": '',
    "pregunta_21B": '',
    "pregunta_21C": 'Piso de venta (mesas exhibición, paredes, espejos, etc)',
    "pregunta_21D": '',
    "pregunta_21A": '',
    "pregunta_21B": '',
    "pregunta_21C": '',
    "pregunta_21D": '',
    "pregunta_21E": '',
    "pregunta_21F": '',
  }, 
    {
    "folio": "850-11702", 
    "record_id": "63eaed385a3ef7414d4899da", 
    "store_id": "1209250816961081402", 
    "merchant": "Calvin Klein Instore", 
    "store": "Ck Parque Lindavista", 
    "promotor": "Alberto Torres",
    "fecha": "2023-02-14", 
    "hora": " 08:08:45", 
    "pregunta_1": 'Tuve que capacitar desde cero',
    "pregunta_2": 'Resolvi unas cuantas dudas',
    "pregunta_3": 'El staff de la tienda domina el tema o no tiene problemas',
    "pregunta_4": 'Resolvi unas cuantas dudas',
    "pregunta_5": 'El staff de la tienda domina el tema o no tiene problemas',
    "pregunta_6": 'Tuve que capacitar desde cero',
    "pregunta_7": 'Tuve que capacitar desde cero',
    "pregunta_8": 'Resolvi unas cuantas dudas',
    "pregunta_9": 'Resolvi unas cuantas dudas',
    "pregunta_11A": 'Sticker de Ventana',
    "pregunta_11B": '',
    "pregunta_11C": '',
    "pregunta_11D": '',
    "pregunta_12A": 'En la entrada',
    "pregunta_12B": '',
    "pregunta_12C": '',
    "pregunta_12D": '',
    "pregunta_12E": '',
    "pregunta_13A": '',
    "pregunta_13B": 'Stickers para piso de venta',
    "pregunta_13C": '',
    "pregunta_13D": '',
    "pregunta_14A": '',
    "pregunta_14B": '',
    "pregunta_14C": '',
    "pregunta_14D": 'Portados por el personal (botones, gafetes, ropa, etc)',
    "pregunta_14E": '',
    "pregunta_15A": '',
    "pregunta_15B": '',
    "pregunta_16A": '',
    "pregunta_16B": '',
    "pregunta_16C": '',
    "pregunta_16D": 'En tu visita, ¿Qué obstáculos y/o retos tiene la tienda?',
    "pregunta_16E": '',
    "pregunta_17A": 'Banner ( Cualquier tipo y Tamaño)',
    "pregunta_17B": '',
    "pregunta_17C": '',
    "pregunta_17D": '',
    "pregunta_17E": '',
    "pregunta_18A": 'Sí',
    "pregunta_18B": '',
    "pregunta_19A": 'No contaba con material',
    "pregunta_19B": '',
    "pregunta_20A": 'Sí',
    "pregunta_20B": '',
    "pregunta_21A": '',
    "pregunta_21B": '',
    "pregunta_21C": 'Piso de venta (mesas exhibición, paredes, espejos, etc)',
    "pregunta_21D": '',
    "pregunta_21A": '',
    "pregunta_21B": '',
    "pregunta_21C": '',
    "pregunta_21D": 'Portados por el personal (botones, gafetes, ropa, etc)',
    "pregunta_21A": 'Banner (cualquier tipo y tamaño',
    "pregunta_21B": '',
    "pregunta_21C": '',
    "pregunta_21D": '',
    "pregunta_21E": '',
    "pregunta_21F": '',
  }, 
  {
    "folio": "850-11702", 
    "record_id": "63eaed385a3ef7414d4899da", 
    "store_id": "1209250816961081402", 
    "merchant": "Calvin Klein Instore", 
    "store": "Ck Parque Lindavista", 
    "promotor": "Alberto Torres",
    "fecha": "2023-02-14", 
    "hora": " 08:08:45", 
    "pregunta_1": 'Tuve que capacitar desde cero',
    "pregunta_2": 'Resolvi unas cuantas dudas',
    "pregunta_3": 'El staff de la tienda domina el tema o no tiene problemas',
    "pregunta_4": 'Resolvi unas cuantas dudas',
    "pregunta_5": 'El staff de la tienda domina el tema o no tiene problemas',
    "pregunta_6": 'Tuve que capacitar desde cero',
    "pregunta_7": 'Tuve que capacitar desde cero',
    "pregunta_8": 'Resolvi unas cuantas dudas',
    "pregunta_9": 'Resolvi unas cuantas dudas',
    "pregunta_11A": 'Sticker de Ventana',
    "pregunta_11B": '',
    "pregunta_11C": '',
    "pregunta_11D": '',
    "pregunta_12A": '',
    "pregunta_12B": '',
    "pregunta_12C": 'Piso de venta (colgadores, paredes, espejos, etc)',
    "pregunta_12D": '',
    "pregunta_12E": '',
    "pregunta_13A": '',
    "pregunta_13B": 'pregunta_13B',
    "pregunta_13C": '',
    "pregunta_13D": '',
    "pregunta_14A": '',
    "pregunta_14B": 'pregunta_14B',
    "pregunta_14C": '',
    "pregunta_14D": '',
    "pregunta_14E": '',
    "pregunta_15A": 'Sí',
    "pregunta_15B": '',
    "pregunta_16A": '',
    "pregunta_16B": '',
    "pregunta_16C": 'Vestidores',
    "pregunta_16D": '',
    "pregunta_16E": '',
    "pregunta_17A": 'Banner ( Cualquier tipo y Tamaño)',
    "pregunta_17B": '',
    "pregunta_17C": '',
    "pregunta_17D": '',
    "pregunta_17E": '',
    "pregunta_18A": 'Sí',
    "pregunta_18B": '',
    "pregunta_19A": 'No contaba con material',
    "pregunta_19B": '',
    "pregunta_20A": 'Sí',
    "pregunta_20B": '',
    "pregunta_21A": '',
    "pregunta_21B": 'Caja',
    "pregunta_21C": '',
    "pregunta_21D": '',
    "pregunta_21A": '',
    "pregunta_21B": '',
    "pregunta_21C": 'Piso de venta (mesas exhibición, paredes, espejos, etc)',
    "pregunta_21D": '',
    "pregunta_21A": '',
    "pregunta_21B": '',
    "pregunta_21C": '',
    "pregunta_21D": '',
    "pregunta_21E": '',
    "pregunta_21F": '',
  }, 
    {
    "folio": "850-11702", 
    "record_id": "63eaed385a3ef7414d4899da", 
    "store_id": "1209250816961081402", 
    "merchant": "Calvin Klein Instore", 
    "store": "Ck Parque Lindavista", 
    "promotor": "Alberto Torres",
    "fecha": "2023-02-14", 
    "hora": " 08:08:45", 
    "pregunta_1": 'Tuve que capacitar desde cero',
    "pregunta_2": 'Resolvi unas cuantas dudas',
    "pregunta_3": 'El staff de la tienda domina el tema o no tiene problemas',
    "pregunta_4": 'Resolvi unas cuantas dudas',
    "pregunta_5": 'El staff de la tienda domina el tema o no tiene problemas',
    "pregunta_6": 'Tuve que capacitar desde cero',
    "pregunta_7": 'Tuve que capacitar desde cero',
    "pregunta_8": 'Resolvi unas cuantas dudas',
    "pregunta_9": 'Resolvi unas cuantas dudas',
    "pregunta_11A": 'Sticker de Ventana',
    "pregunta_11B": '',
    "pregunta_11C": '',
    "pregunta_11D": '',
    "pregunta_12A": 'En la entrada',
    "pregunta_12B": '',
    "pregunta_12C": '',
    "pregunta_12D": '',
    "pregunta_12E": '',
    "pregunta_13A": '',
    "pregunta_13B": 'Stickers para piso de venta',
    "pregunta_13C": '',
    "pregunta_13D": '',
    "pregunta_14A": '',
    "pregunta_14B": '',
    "pregunta_14C": '',
    "pregunta_14D": 'Portados por el personal (botones, gafetes, ropa, etc)',
    "pregunta_14E": '',
    "pregunta_15A": '',
    "pregunta_15B": '',
    "pregunta_16A": '',
    "pregunta_16B": '',
    "pregunta_16C": '',
    "pregunta_16D": 'En tu visita, ¿Qué obstáculos y/o retos tiene la tienda?',
    "pregunta_16E": '',
    "pregunta_17A": 'Banner ( Cualquier tipo y Tamaño)',
    "pregunta_17B": '',
    "pregunta_17C": '',
    "pregunta_17D": '',
    "pregunta_17E": '',
    "pregunta_18A": 'Sí',
    "pregunta_18B": '',
    "pregunta_19A": 'No contaba con material',
    "pregunta_19B": '',
    "pregunta_20A": 'Sí',
    "pregunta_20B": '',
    "pregunta_21A": '',
    "pregunta_21B": '',
    "pregunta_21C": 'Piso de venta (mesas exhibición, paredes, espejos, etc)',
    "pregunta_21D": '',
    "pregunta_21A": '',
    "pregunta_21B": '',
    "pregunta_21C": '',
    "pregunta_21D": 'Portados por el personal (botones, gafetes, ropa, etc)',
    "pregunta_21A": 'Banner (cualquier tipo y tamaño',
    "pregunta_21B": '',
    "pregunta_21C": '',
    "pregunta_21D": '',
    "pregunta_21E": '',
    "pregunta_21F": '',
  }, 
  {
    "folio": "850-11702", 
    "record_id": "63eaed385a3ef7414d4899da", 
    "store_id": "1209250816961081402", 
    "merchant": "Calvin Klein Instore", 
    "store": "Ck Parque Lindavista", 
    "promotor": "Alberto Torres",
    "fecha": "2023-02-14", 
    "hora": " 08:08:45", 
    "pregunta_1": 'Tuve que capacitar desde cero',
    "pregunta_2": 'Resolvi unas cuantas dudas',
    "pregunta_3": 'El staff de la tienda domina el tema o no tiene problemas',
    "pregunta_4": 'Resolvi unas cuantas dudas',
    "pregunta_5": 'El staff de la tienda domina el tema o no tiene problemas',
    "pregunta_6": 'Tuve que capacitar desde cero',
    "pregunta_7": 'Tuve que capacitar desde cero',
    "pregunta_8": 'Resolvi unas cuantas dudas',
    "pregunta_9": 'Resolvi unas cuantas dudas',
    "pregunta_11A": 'Sticker de Ventana',
    "pregunta_11B": '',
    "pregunta_11C": '',
    "pregunta_11D": '',
    "pregunta_12A": '',
    "pregunta_12B": '',
    "pregunta_12C": 'Piso de venta (colgadores, paredes, espejos, etc)',
    "pregunta_12D": '',
    "pregunta_12E": '',
    "pregunta_13A": '',
    "pregunta_13B": 'pregunta_13B',
    "pregunta_13C": '',
    "pregunta_13D": '',
    "pregunta_14A": '',
    "pregunta_14B": 'pregunta_14B',
    "pregunta_14C": '',
    "pregunta_14D": '',
    "pregunta_14E": '',
    "pregunta_15A": 'Sí',
    "pregunta_15B": '',
    "pregunta_16A": '',
    "pregunta_16B": '',
    "pregunta_16C": 'Vestidores',
    "pregunta_16D": '',
    "pregunta_16E": '',
    "pregunta_17A": 'Banner ( Cualquier tipo y Tamaño)',
    "pregunta_17B": '',
    "pregunta_17C": '',
    "pregunta_17D": '',
    "pregunta_17E": '',
    "pregunta_18A": 'Sí',
    "pregunta_18B": '',
    "pregunta_19A": 'No contaba con material',
    "pregunta_19B": '',
    "pregunta_20A": 'Sí',
    "pregunta_20B": '',
    "pregunta_21A": '',
    "pregunta_21B": 'Caja',
    "pregunta_21C": '',
    "pregunta_21D": '',
    "pregunta_21A": '',
    "pregunta_21B": '',
    "pregunta_21C": 'Piso de venta (mesas exhibición, paredes, espejos, etc)',
    "pregunta_21D": '',
    "pregunta_21A": '',
    "pregunta_21B": '',
    "pregunta_21C": '',
    "pregunta_21D": '',
    "pregunta_21E": '',
    "pregunta_21F": '',
  }, 
    {
    "folio": "850-11702", 
    "record_id": "63eaed385a3ef7414d4899da", 
    "store_id": "1209250816961081402", 
    "merchant": "Calvin Klein Instore", 
    "store": "Ck Parque Lindavista", 
    "promotor": "Alberto Torres",
    "fecha": "2023-02-14", 
    "hora": " 08:08:45", 
    "pregunta_1": 'Tuve que capacitar desde cero',
    "pregunta_2": 'Resolvi unas cuantas dudas',
    "pregunta_3": 'El staff de la tienda domina el tema o no tiene problemas',
    "pregunta_4": 'Resolvi unas cuantas dudas',
    "pregunta_5": 'El staff de la tienda domina el tema o no tiene problemas',
    "pregunta_6": 'Tuve que capacitar desde cero',
    "pregunta_7": 'Tuve que capacitar desde cero',
    "pregunta_8": 'Resolvi unas cuantas dudas',
    "pregunta_9": 'Resolvi unas cuantas dudas',
    "pregunta_11A": 'Sticker de Ventana',
    "pregunta_11B": '',
    "pregunta_11C": '',
    "pregunta_11D": '',
    "pregunta_12A": 'En la entrada',
    "pregunta_12B": '',
    "pregunta_12C": '',
    "pregunta_12D": '',
    "pregunta_12E": '',
    "pregunta_13A": '',
    "pregunta_13B": 'Stickers para piso de venta',
    "pregunta_13C": '',
    "pregunta_13D": '',
    "pregunta_14A": '',
    "pregunta_14B": '',
    "pregunta_14C": '',
    "pregunta_14D": 'Portados por el personal (botones, gafetes, ropa, etc)',
    "pregunta_14E": '',
    "pregunta_15A": '',
    "pregunta_15B": '',
    "pregunta_16A": '',
    "pregunta_16B": '',
    "pregunta_16C": '',
    "pregunta_16D": 'En tu visita, ¿Qué obstáculos y/o retos tiene la tienda?',
    "pregunta_16E": '',
    "pregunta_17A": 'Banner ( Cualquier tipo y Tamaño)',
    "pregunta_17B": '',
    "pregunta_17C": '',
    "pregunta_17D": '',
    "pregunta_17E": '',
    "pregunta_18A": 'Sí',
    "pregunta_18B": '',
    "pregunta_19A": 'No contaba con material',
    "pregunta_19B": '',
    "pregunta_20A": 'Sí',
    "pregunta_20B": '',
    "pregunta_21A": '',
    "pregunta_21B": '',
    "pregunta_21C": 'Piso de venta (mesas exhibición, paredes, espejos, etc)',
    "pregunta_21D": '',
    "pregunta_21A": '',
    "pregunta_21B": '',
    "pregunta_21C": '',
    "pregunta_21D": 'Portados por el personal (botones, gafetes, ropa, etc)',
    "pregunta_21A": 'Banner (cualquier tipo y tamaño',
    "pregunta_21B": '',
    "pregunta_21C": '',
    "pregunta_21D": '',
    "pregunta_21E": '',
    "pregunta_21F": '',
  },  
];





  



 

