var columsTable1 = [
  {title:"Folio", field:'folio', hozAlign:"right", formatter:"link", formatterParams:{
  url:function(cell){return "https://app.linkaform.com/#/records/detail/" + cell.getData().record_id}, 
  target:"_blank",},  headerTooltip:true,width:100},
  { title:"Store ID", field:'store_id',hozAlign:"right", headerTooltip:true,width:200},
  { title:"Merchant", field:'merchant',hozAlign:"left", headerTooltip:true,width:300},
  { title:"Store", field:'store',hozAlign:"left", headerTooltip:true,width:300},
  { title:"Promotor", field:'promotor',hozAlign:"left", headerTooltip:true,width:300},
  { title:"Fecha", field:'fecha',hozAlign:"center", headerTooltip:true,width:150},
  { title:"Hora", field:'hora',hozAlign:"center", headerTooltip:true,width:150},

  { title:"Acceso al portal (usuario y contraseña)", field:'pregunta_1',hozAlign:"left", headerTooltip:true,width:300},
  { title:"Cómo el cliente crea su cuenta en KueskiPay ", field:'pregunta_2',hozAlign:"left", headerTooltip:true,width:300},
  { title:"Cómo el cliente usa KueskiPay para pagar  ", field:'pregunta_3',hozAlign:"left", headerTooltip:true,width:300},
  { title:"Como el vendedor/asesor usa KueskiPay para cobrar ", field:'pregunta_4',hozAlign:"left", headerTooltip:true,width:300},
  { title:"Términos y condiciones de las promociones vigentes", field:'pregunta_5',hozAlign:"left", headerTooltip:true,width:300},
  { title:"Cómo el cliente usa un cupón de descuento ", field:'pregunta_6',hozAlign:"left", headerTooltip:true,width:300},
  { title:"Ventajas competitivas, beneficios y características de KueskiPay  ", field:'pregunta_7',hozAlign:"left", headerTooltip:true,width:300},
  { title:"Compartir los datos de bsoporte telefónico ", field:'pregunta_8',hozAlign:"left", headerTooltip:true,width:300},
  { title:"Canales de comunicación oficiales (WA, correo, etc.)", field:'pregunta_9',hozAlign:"left", headerTooltip:true,width:300},
  { title:"¿Hay presencia de Aplazo en la tienda?", field:'pregunta_21',hozAlign:"left", headerTooltip:true,width:300},
  { title:"¿Hay Material Publicitario de Kueski?", field:'pregunta_10',hozAlign:"left", headerTooltip:true,width:300},
  {
    title:"¿Dónde hay presencia de material de Kueski?",
    columns:[
      { title:"Piso de venta (mesas exhibición, paredes, espejos, etc)", field:'pregunta_11A',hozAlign:"left", headerTooltip:true,width:300},
      { title:"Caja", field:'pregunta_11B',hozAlign:"left", headerTooltip:true,width:300},
      { title:"Entrada", field:'pregunta_11C',hozAlign:"left", headerTooltip:true,width:300},
    ],
  },
  {
    title:"Material Publicitario Disponible de Kueski",
    columns:[
      { title:"Banner ( Cualquier tipo y Tamaño)", field:'pregunta_12A',hozAlign:"left", headerTooltip:true,width:300},
      { title:"Sticker ( Cualquier tipo y Tamaño)", field:'pregunta_12B',hozAlign:"left", headerTooltip:true,width:300},
      { title:"Lona ( Cualquier tipo y Tamaño)", field:'pregunta_12C',hozAlign:"left", headerTooltip:true,width:300},
      { title:"Pantalla", field:'pregunta_12D',hozAlign:"left", headerTooltip:true,width:300},
      { title:"Otro", field:'pregunta_12E',hozAlign:"left", headerTooltip:true,width:300},
    ],
  },
  { title:"¿Dejaste material publicitario?", field:'pregunta_13',hozAlign:"left", headerTooltip:true,width:300},
  { title:"¿Por que?", field:'pregunta_14',hozAlign:"left", headerTooltip:true,width:300},
  { title:"¿Hay material publicitario de aplazo?", field:'pregunta_15',hozAlign:"left", headerTooltip:true,width:300},
  {
    title:"¿Dónde hay presencia de material de aplazo?",
    columns:[
      { title:"Entrada", field:'pregunta_16A',hozAlign:"left", headerTooltip:true,width:300},
      { title:"Caja", field:'pregunta_16B',hozAlign:"left", headerTooltip:true,width:300},
      { title:"Piso de venta (mesas exhibición, paredes, espejos, etc)", field:'pregunta_16C',hozAlign:"left", headerTooltip:true,width:300},
    ],
  },
  {
    title:"Material publicitario disponible de aplazo",
    columns:[
      { title:"Banner (cualquier tipo y tamaño)", field:'pregunta_17A',hozAlign:"left", headerTooltip:true,width:300},
      { title:"Sticker (cualquier tipo y tamaño)", field:'pregunta_17B',hozAlign:"left", headerTooltip:true,width:300},
      { title:"Lona (cualquier tipo y tamaño)", field:'pregunta_17C',hozAlign:"left", headerTooltip:true,width:300},
      { title:"Portados por el personal (botones, gafetes, ropa, etc)", field:'pregunta_17D',hozAlign:"left", headerTooltip:true,width:300},
      { title:"Pantalla", field:'pregunta_17E',hozAlign:"left", headerTooltip:true,width:300},
      { title:"Otro", field:'pregunta_17F',hozAlign:"left", headerTooltip:true,width:300},
    ],
  },

  { title:"Describe las fallas o bugs que encontraste en tu visita y cómo se resolvieron Si no hubo ninguna omite esta pregunta", field:'pregunta_18',hozAlign:"left", headerTooltip:true,width:300},
  { title:"En tu visita, ¿Qué obstáculos y/o retos tiene la tienda?", field:'pregunta_19',hozAlign:"left", headerTooltip:true,width:300},
  { title:"Comparte tus comentarios adicionales", field:'pregunta_20',hozAlign:"left", headerTooltip:true,width:300},
];

var dataTable1 = [
  {
    "folio": "850-11702", 
    "record_id": "63eaed385a3ef7414d4899da", 
    "store_id": "1209250816961081402", 
    "merchant": "Calvin Klein Instore", 
    "store": "Ck Parque Lindavista", 
    "promotor": "Alberto Torres",
    "fecha": "2023-02-14", 
    "hora": " 08:08:45", 
    "pregunta_1": 'Tuve que capacitar desde cero',
    "pregunta_2": 'Resolvi unas cuantas dudas',
    "pregunta_3": 'El staff de la tienda domina el tema o no tiene problemas',
    "pregunta_4": 'Resolvi unas cuantas dudas',
    "pregunta_5": 'El staff de la tienda domina el tema o no tiene problemas',
    "pregunta_6": 'Tuve que capacitar desde cero',
    "pregunta_7": 'Tuve que capacitar desde cero',
    "pregunta_8": 'Resolvi unas cuantas dudas',
    "pregunta_9": 'Resolvi unas cuantas dudas',
    "pregunta_10": 'Sí',
    "pregunta_11A": 'En caja',
    "pregunta_12A": 'Banner ( Cualquier tipo y Tamaño)',
    "pregunta_12B": '',
    "pregunta_12C": '',
    "pregunta_12D": '',
    "pregunta_12E": '',
    "pregunta_13": 'Sí',
    "pregunta_14": 'No contaba con Material',
    "pregunta_15": 'Sí',
    "pregunta_16A": 'Entrada',
    "pregunta_17": 'Lona (cualquier tipo tipo y tamaño)',
    "pregunta_18": 'Comentario de ejemplo',
    "pregunta_19": 'Comentario de ejemplo',
    "pregunta_20": 'Comentario de ejemplo',
  }, 
    {
    "folio": "850-11702", 
    "record_id": "63eaed385a3ef7414d4899da", 
    "store_id": "1209250816961081402", 
    "merchant": "Calvin Klein Instore", 
    "store": "Ck Parque Lindavista", 
    "promotor": "Alberto Torres",
    "fecha": "2023-02-14", 
    "hora": " 08:08:45", 
    "pregunta_1": 'Tuve que capacitar desde cero',
    "pregunta_2": 'Resolvi unas cuantas dudas',
    "pregunta_3": 'El staff de la tienda domina el tema o no tiene problemas',
    "pregunta_4": 'Resolvi unas cuantas dudas',
    "pregunta_5": 'El staff de la tienda domina el tema o no tiene problemas',
    "pregunta_6": 'Tuve que capacitar desde cero',
    "pregunta_7": 'Tuve que capacitar desde cero',
    "pregunta_8": 'Resolvi unas cuantas dudas',
    "pregunta_9": 'Resolvi unas cuantas dudas',
    "pregunta_10": 'Sí',
    "pregunta_11A": 'En caja',
    "pregunta_11C": '',
    "pregunta_11D": '',
    "pregunta_11E": '',
    "pregunta_12A": 'Banner ( Cualquier tipo y Tamaño)',
    "pregunta_12B": '',
    "pregunta_12C": '',
    "pregunta_12D": '',
    "pregunta_12E": '',
    "pregunta_13": 'Sí',
    "pregunta_14": 'No contaba con Material',
    "pregunta_15": 'Sí',
    "pregunta_16A": 'Entrada',
    "pregunta_17": 'Lona (cualquier tipo tipo y tamaño)',
    "pregunta_18": 'Comentario de ejemplo',
    "pregunta_19": 'Comentario de ejemplo',
    "pregunta_20": 'Comentario de ejemplo',
  }, 
    {
    "folio": "850-11702", 
    "record_id": "63eaed385a3ef7414d4899da", 
    "store_id": "1209250816961081402", 
    "merchant": "Calvin Klein Instore", 
    "store": "Ck Parque Lindavista", 
    "promotor": "Alberto Torres",
    "fecha": "2023-02-14", 
    "hora": " 08:08:45", 
    "pregunta_1": 'Tuve que capacitar desde cero',
    "pregunta_2": 'Resolvi unas cuantas dudas',
    "pregunta_3": 'El staff de la tienda domina el tema o no tiene problemas',
    "pregunta_4": 'Resolvi unas cuantas dudas',
    "pregunta_5": 'El staff de la tienda domina el tema o no tiene problemas',
    "pregunta_6": 'Tuve que capacitar desde cero',
    "pregunta_7": 'Tuve que capacitar desde cero',
    "pregunta_8": 'Resolvi unas cuantas dudas',
    "pregunta_9": 'Resolvi unas cuantas dudas',
    "pregunta_10": 'Sí',
    "pregunta_11A": 'En caja',
    "pregunta_11C": '',
    "pregunta_11D": '',
    "pregunta_11E": '',
    "pregunta_12A": 'Banner ( Cualquier tipo y Tamaño)',
    "pregunta_12B": '',
    "pregunta_12C": '',
    "pregunta_12D": '',
    "pregunta_12E": '',
    "pregunta_13": 'Sí',
    "pregunta_14": 'No contaba con Material',
    "pregunta_15": 'Sí',
    "pregunta_16A": 'Entrada',
    "pregunta_17": 'Lona (cualquier tipo tipo y tamaño)',
    "pregunta_18": 'Comentario de ejemplo',
    "pregunta_19": 'Comentario de ejemplo',
    "pregunta_20": 'Comentario de ejemplo',
  }, 
  {
    "folio": "850-11702", 
    "record_id": "63eaed385a3ef7414d4899da", 
    "store_id": "1209250816961081402", 
    "merchant": "Calvin Klein Instore", 
    "store": "Ck Parque Lindavista", 
    "promotor": "Alberto Torres",
    "fecha": "2023-02-14", 
    "hora": " 08:08:45", 
    "pregunta_1": 'Tuve que capacitar desde cero',
    "pregunta_2": 'Resolvi unas cuantas dudas',
    "pregunta_3": 'El staff de la tienda domina el tema o no tiene problemas',
    "pregunta_4": 'Resolvi unas cuantas dudas',
    "pregunta_5": 'El staff de la tienda domina el tema o no tiene problemas',
    "pregunta_6": 'Tuve que capacitar desde cero',
    "pregunta_7": 'Tuve que capacitar desde cero',
    "pregunta_8": 'Resolvi unas cuantas dudas',
    "pregunta_9": 'Resolvi unas cuantas dudas',
    "pregunta_10": 'Sí',
    "pregunta_11A": 'En caja',
    "pregunta_11C": '',
    "pregunta_11D": '',
    "pregunta_11E": '',
    "pregunta_12A": 'Banner ( Cualquier tipo y Tamaño)',
    "pregunta_12B": '',
    "pregunta_12C": '',
    "pregunta_12D": '',
    "pregunta_12E": '',
    "pregunta_13": 'Sí',
    "pregunta_14": 'No contaba con Material',
    "pregunta_15": 'Sí',
    "pregunta_16A": 'Entrada',
    "pregunta_17": 'Lona (cualquier tipo tipo y tamaño)',
    "pregunta_18": 'Comentario de ejemplo',
    "pregunta_19": 'Comentario de ejemplo',
    "pregunta_20": 'Comentario de ejemplo',
  }, 
  {
    "folio": "850-11702", 
    "record_id": "63eaed385a3ef7414d4899da", 
    "store_id": "1209250816961081402", 
    "merchant": "Calvin Klein Instore", 
    "store": "Ck Parque Lindavista", 
    "promotor": "Alberto Torres",
    "fecha": "2023-02-14", 
    "hora": " 08:08:45", 
    "pregunta_1": 'Tuve que capacitar desde cero',
    "pregunta_2": 'Resolvi unas cuantas dudas',
    "pregunta_3": 'El staff de la tienda domina el tema o no tiene problemas',
    "pregunta_4": 'Resolvi unas cuantas dudas',
    "pregunta_5": 'El staff de la tienda domina el tema o no tiene problemas',
    "pregunta_6": 'Tuve que capacitar desde cero',
    "pregunta_7": 'Tuve que capacitar desde cero',
    "pregunta_8": 'Resolvi unas cuantas dudas',
    "pregunta_9": 'Resolvi unas cuantas dudas',
    "pregunta_10": 'Sí',
    "pregunta_11A": 'En caja',
    "pregunta_11C": '',
    "pregunta_11D": '',
    "pregunta_11E": '',
    "pregunta_12A": 'Banner ( Cualquier tipo y Tamaño)',
    "pregunta_12B": '',
    "pregunta_12C": '',
    "pregunta_12D": '',
    "pregunta_12E": '',
    "pregunta_13": 'Sí',
    "pregunta_14": 'No contaba con Material',
    "pregunta_15": 'Sí',
    "pregunta_16A": 'Entrada',
    "pregunta_17": 'Lona (cualquier tipo tipo y tamaño)',
    "pregunta_18": 'Comentario de ejemplo',
    "pregunta_19": 'Comentario de ejemplo',
    "pregunta_20": 'Comentario de ejemplo',
  }, 
  {
    "folio": "850-11702", 
    "record_id": "63eaed385a3ef7414d4899da", 
    "store_id": "1209250816961081402", 
    "merchant": "Calvin Klein Instore", 
    "store": "Ck Parque Lindavista", 
    "promotor": "Alberto Torres",
    "fecha": "2023-02-14", 
    "hora": " 08:08:45", 
    "pregunta_1": 'Tuve que capacitar desde cero',
    "pregunta_2": 'Resolvi unas cuantas dudas',
    "pregunta_3": 'El staff de la tienda domina el tema o no tiene problemas',
    "pregunta_4": 'Resolvi unas cuantas dudas',
    "pregunta_5": 'El staff de la tienda domina el tema o no tiene problemas',
    "pregunta_6": 'Tuve que capacitar desde cero',
    "pregunta_7": 'Tuve que capacitar desde cero',
    "pregunta_8": 'Resolvi unas cuantas dudas',
    "pregunta_9": 'Resolvi unas cuantas dudas',
    "pregunta_10": 'Sí',
    "pregunta_11A": 'En caja',
    "pregunta_11C": '',
    "pregunta_11D": '',
    "pregunta_11E": '',
    "pregunta_12A": 'Banner ( Cualquier tipo y Tamaño)',
    "pregunta_12B": '',
    "pregunta_12C": '',
    "pregunta_12D": '',
    "pregunta_12E": '',
    "pregunta_13": 'Sí',
    "pregunta_14": 'No contaba con Material',
    "pregunta_15": 'Sí',
    "pregunta_16A": 'Entrada',
    "pregunta_17": 'Lona (cualquier tipo tipo y tamaño)',
    "pregunta_18": 'Comentario de ejemplo',
    "pregunta_19": 'Comentario de ejemplo',
    "pregunta_20": 'Comentario de ejemplo',
  }, 
  {
    "folio": "850-11702", 
    "record_id": "63eaed385a3ef7414d4899da", 
    "store_id": "1209250816961081402", 
    "merchant": "Calvin Klein Instore", 
    "store": "Ck Parque Lindavista", 
    "promotor": "Alberto Torres",
    "fecha": "2023-02-14", 
    "hora": " 08:08:45", 
    "pregunta_1": 'Tuve que capacitar desde cero',
    "pregunta_2": 'Resolvi unas cuantas dudas',
    "pregunta_3": 'El staff de la tienda domina el tema o no tiene problemas',
    "pregunta_4": 'Resolvi unas cuantas dudas',
    "pregunta_5": 'El staff de la tienda domina el tema o no tiene problemas',
    "pregunta_6": 'Tuve que capacitar desde cero',
    "pregunta_7": 'Tuve que capacitar desde cero',
    "pregunta_8": 'Resolvi unas cuantas dudas',
    "pregunta_9": 'Resolvi unas cuantas dudas',
    "pregunta_10": 'Sí',
    "pregunta_11A": 'En caja',
    "pregunta_11C": '',
    "pregunta_11D": '',
    "pregunta_11E": '',
    "pregunta_12A": 'Banner ( Cualquier tipo y Tamaño)',
    "pregunta_12B": '',
    "pregunta_12C": '',
    "pregunta_12D": '',
    "pregunta_12E": '',
    "pregunta_13": 'Sí',
    "pregunta_14": 'No contaba con Material',
    "pregunta_15": 'Sí',
    "pregunta_16A": 'Entrada',
    "pregunta_17": 'Lona (cualquier tipo tipo y tamaño)',
    "pregunta_18": 'Comentario de ejemplo',
    "pregunta_19": 'Comentario de ejemplo',
    "pregunta_20": 'Comentario de ejemplo',
  }, 
  {
    "folio": "850-11702", 
    "record_id": "63eaed385a3ef7414d4899da", 
    "store_id": "1209250816961081402", 
    "merchant": "Calvin Klein Instore", 
    "store": "Ck Parque Lindavista", 
    "promotor": "Alberto Torres",
    "fecha": "2023-02-14", 
    "hora": " 08:08:45", 
    "pregunta_1": 'Tuve que capacitar desde cero',
    "pregunta_2": 'Resolvi unas cuantas dudas',
    "pregunta_3": 'El staff de la tienda domina el tema o no tiene problemas',
    "pregunta_4": 'Resolvi unas cuantas dudas',
    "pregunta_5": 'El staff de la tienda domina el tema o no tiene problemas',
    "pregunta_6": 'Tuve que capacitar desde cero',
    "pregunta_7": 'Tuve que capacitar desde cero',
    "pregunta_8": 'Resolvi unas cuantas dudas',
    "pregunta_9": 'Resolvi unas cuantas dudas',
    "pregunta_10": 'Sí',
    "pregunta_11A": 'En caja',
    "pregunta_11C": '',
    "pregunta_11D": '',
    "pregunta_11E": '',
    "pregunta_12A": 'Banner ( Cualquier tipo y Tamaño)',
    "pregunta_12B": '',
    "pregunta_12C": '',
    "pregunta_12D": '',
    "pregunta_12E": '',
    "pregunta_13": 'Sí',
    "pregunta_14": 'No contaba con Material',
    "pregunta_15": 'Sí',
    "pregunta_16A": 'Entrada',
    "pregunta_17": 'Lona (cualquier tipo tipo y tamaño)',
    "pregunta_18": 'Comentario de ejemplo',
    "pregunta_19": 'Comentario de ejemplo',
    "pregunta_20": 'Comentario de ejemplo',
  }, 
  {
    "folio": "850-11702", 
    "record_id": "63eaed385a3ef7414d4899da", 
    "store_id": "1209250816961081402", 
    "merchant": "Calvin Klein Instore", 
    "store": "Ck Parque Lindavista", 
    "promotor": "Alberto Torres",
    "fecha": "2023-02-14", 
    "hora": " 08:08:45", 
    "pregunta_1": 'Tuve que capacitar desde cero',
    "pregunta_2": 'Resolvi unas cuantas dudas',
    "pregunta_3": 'El staff de la tienda domina el tema o no tiene problemas',
    "pregunta_4": 'Resolvi unas cuantas dudas',
    "pregunta_5": 'El staff de la tienda domina el tema o no tiene problemas',
    "pregunta_6": 'Tuve que capacitar desde cero',
    "pregunta_7": 'Tuve que capacitar desde cero',
    "pregunta_8": 'Resolvi unas cuantas dudas',
    "pregunta_9": 'Resolvi unas cuantas dudas',
    "pregunta_10": 'Sí',
    "pregunta_11A": 'En caja',
    "pregunta_11C": '',
    "pregunta_11D": '',
    "pregunta_11E": '',
    "pregunta_12A": 'Banner ( Cualquier tipo y Tamaño)',
    "pregunta_12B": '',
    "pregunta_12C": '',
    "pregunta_12D": '',
    "pregunta_12E": '',
    "pregunta_13": 'Sí',
    "pregunta_14": 'No contaba con Material',
    "pregunta_15": 'Sí',
    "pregunta_16A": 'Entrada',
    "pregunta_17": 'Lona (cualquier tipo tipo y tamaño)',
    "pregunta_18": 'Comentario de ejemplo',
    "pregunta_19": 'Comentario de ejemplo',
    "pregunta_20": 'Comentario de ejemplo',
  }, 
  {
    "folio": "850-11702", 
    "record_id": "63eaed385a3ef7414d4899da", 
    "store_id": "1209250816961081402", 
    "merchant": "Calvin Klein Instore", 
    "store": "Ck Parque Lindavista", 
    "promotor": "Alberto Torres",
    "fecha": "2023-02-14", 
    "hora": " 08:08:45", 
    "pregunta_1": 'Tuve que capacitar desde cero',
    "pregunta_2": 'Resolvi unas cuantas dudas',
    "pregunta_3": 'El staff de la tienda domina el tema o no tiene problemas',
    "pregunta_4": 'Resolvi unas cuantas dudas',
    "pregunta_5": 'El staff de la tienda domina el tema o no tiene problemas',
    "pregunta_6": 'Tuve que capacitar desde cero',
    "pregunta_7": 'Tuve que capacitar desde cero',
    "pregunta_8": 'Resolvi unas cuantas dudas',
    "pregunta_9": 'Resolvi unas cuantas dudas',
    "pregunta_10": 'Sí',
    "pregunta_11A": 'En caja',
    "pregunta_11C": '',
    "pregunta_11D": '',
    "pregunta_11E": '',
    "pregunta_12A": 'Banner ( Cualquier tipo y Tamaño)',
    "pregunta_12B": '',
    "pregunta_12C": '',
    "pregunta_12D": '',
    "pregunta_12E": '',
    "pregunta_13": 'Sí',
    "pregunta_14": 'No contaba con Material',
    "pregunta_15": 'Sí',
    "pregunta_16A": 'Entrada',
    "pregunta_17": 'Lona (cualquier tipo tipo y tamaño)',
    "pregunta_18": 'Comentario de ejemplo',
    "pregunta_19": 'Comentario de ejemplo',
    "pregunta_20": 'Comentario de ejemplo',
  }, 
  {
    "folio": "850-11702", 
    "record_id": "63eaed385a3ef7414d4899da", 
    "store_id": "1209250816961081402", 
    "merchant": "Calvin Klein Instore", 
    "store": "Ck Parque Lindavista", 
    "promotor": "Alberto Torres",
    "fecha": "2023-02-14", 
    "hora": " 08:08:45", 
    "pregunta_1": 'Tuve que capacitar desde cero',
    "pregunta_2": 'Resolvi unas cuantas dudas',
    "pregunta_3": 'El staff de la tienda domina el tema o no tiene problemas',
    "pregunta_4": 'Resolvi unas cuantas dudas',
    "pregunta_5": 'El staff de la tienda domina el tema o no tiene problemas',
    "pregunta_6": 'Tuve que capacitar desde cero',
    "pregunta_7": 'Tuve que capacitar desde cero',
    "pregunta_8": 'Resolvi unas cuantas dudas',
    "pregunta_9": 'Resolvi unas cuantas dudas',
    "pregunta_10": 'Sí',
    "pregunta_11A": 'En caja',
    "pregunta_11C": '',
    "pregunta_11D": '',
    "pregunta_11E": '',
    "pregunta_12A": 'Banner ( Cualquier tipo y Tamaño)',
    "pregunta_12B": '',
    "pregunta_12C": '',
    "pregunta_12D": '',
    "pregunta_12E": '',
    "pregunta_13": 'Sí',
    "pregunta_14": 'No contaba con Material',
    "pregunta_15": 'Sí',
    "pregunta_16A": 'Entrada',
    "pregunta_17": 'Lona (cualquier tipo tipo y tamaño)',
    "pregunta_18": 'Comentario de ejemplo',
    "pregunta_19": 'Comentario de ejemplo',
    "pregunta_20": 'Comentario de ejemplo',
  },   
];

var columsTable2 = [
  {title:"Folio", field:'folio', hozAlign:"right", formatter:"link", formatterParams:{
  url:function(cell){return "https://app.linkaform.com/#/records/detail/" + cell.getData().record_id}, 
  target:"_blank",},  headerTooltip:true,width:100},
  { title:"Store ID", field:'store_id',hozAlign:"right", headerTooltip:true,width:200},
  { title:"Merchant", field:'merchant',hozAlign:"left", headerTooltip:true,width:300},
  { title:"Store", field:'store',hozAlign:"left", headerTooltip:true,width:300},
  { title:"Promotor", field:'promotor',hozAlign:"left", headerTooltip:true,width:300},
  { title:"Fecha", field:'fecha',hozAlign:"center", headerTooltip:true,width:150},
  { title:"Hora", field:'hora',hozAlign:"center", headerTooltip:true,width:150},

  { title:"¿La tienda cuenta con usuario y contraseña ?", field:'pregunta_1',hozAlign:"left", headerTooltip:true,width:300},
  { title:"¿La tienda ya cuenta con los datos de soporte telefónico servicio al cliente y tienda?", field:'pregunta_2',hozAlign:"left", headerTooltip:true,width:300},
  { title:"Describe las fallas u optunidades de mejora que te comentaron los vendedores, y cómo se resolvieron.", field:'pregunta_3',hozAlign:"left", headerTooltip:true,width:300},
  {
    title:"En tu visita, ¿Qué obstáculos y/o retos tiene la tienda?",
    columns:[
      { title:"Clientes no les interesa Kueski Pay", field:'pregunta_4A',hozAlign:"left", headerTooltip:true,width:300},
      { title:"Vendedores no cuentan con capacitación", field:'pregunta_4B',hozAlign:"left", headerTooltip:true,width:300},
      { title:"Vendedores no ofrecen Kueski Pay", field:'pregunta_4C',hozAlign:"left", headerTooltip:true,width:300},
      { title:"Dar Beneficios de Kuesky Pay a Vendedores", field:'pregunta_4D',hozAlign:"left", headerTooltip:true,width:300},
      { title:"No tienen autorización de corporativo para ofrecer Kueski", field:'pregunta_4F',hozAlign:"left", headerTooltip:true,width:300},
      { title:"Otro", field:'pregunta_4G',hozAlign:"left", headerTooltip:true,width:300},
    ],
  },
  { title:"¿Compartiste las ventas que tiene con Kueski Pay actualmente la tienda?", field:'pregunta_5',hozAlign:"left", headerTooltip:true,width:300},
  {
    title:"¿La tienda cuenta con publicidad de Kueski?",
    columns:[
      { title:"No", field:'pregunta_6A',hozAlign:"left", headerTooltip:true,width:300},
      { title:"Sticker", field:'pregunta_6B',hozAlign:"left", headerTooltip:true,width:300},
      { title:"Carta Informativa ( mini banner )", field:'pregunta_6C',hozAlign:"left", headerTooltip:true,width:300},
      { title:"Video Pantalla", field:'pregunta_6D',hozAlign:"left", headerTooltip:true,width:300},
    ],
  },
  { title:"¿Numero telefonico de sucursal?", field:'pregunta_8',hozAlign:"left", headerTooltip:true,width:300},
  { title:"¿Cuál es el nombre del gerente de sucursal o encargado?", field:'pregunta_9',hozAlign:"left", headerTooltip:true,width:300},
  { title:"¿Cuál es el mail del gerente o encargado de sucursal?", field:'pregunta_10',hozAlign:"left", headerTooltip:true,width:300},
  {
    title:"¿La tienda tiene promociones vigentes de Kueski?",
    columns:[
      { title:"Respuesta", field:'pregunta_11',hozAlign:"left", headerTooltip:true,width:300},
      { title:"¿Cuál?", field:'pregunta_12',hozAlign:"left", headerTooltip:true,width:300},
    ],
  },
  {
    title:"¿ Tuvo alguna  promoción de Kueski el mes pasado ?",
    columns:[
      { title:"Respuesta", field:'pregunta_13',hozAlign:"left", headerTooltip:true,width:300},
      { title:"¿Cuál?", field:'pregunta_14',hozAlign:"left", headerTooltip:true,width:300},
    ],
  },
  {
    title:"¿La tienda tiene promociones vigentes de la marca?",
    columns:[
      { title:"Respuesta", field:'pregunta_15',hozAlign:"left", headerTooltip:true,width:300},
      { title:"¿Cuál?", field:'pregunta_16',hozAlign:"left", headerTooltip:true,width:300},
    ],
  },
  {
    title:"¿La tienda tuvo alguna  promoción de la marca el mes pasado?",
    columns:[
      { title:"Respuesta", field:'pregunta_17',hozAlign:"left", headerTooltip:true,width:300},
      { title:"¿Cuál?", field:'pregunta_18',hozAlign:"left", headerTooltip:true,width:300},
    ],
  },
  { title:"Comentarios Adicionales", field:'pregunta_19',hozAlign:"left", headerTooltip:true,width:300},
  { title:"¿La tienda cuenta con cobro de Aplazo?", field:'pregunta_20',hozAlign:"left", headerTooltip:true,width:300},
  {
    title:"¿La tienda cuenta con publicidad de Aplazo?",
    columns:[
      { title:"No", field:'pregunta_21A',hozAlign:"left", headerTooltip:true,width:300},
      { title:"Banner", field:'pregunta_21B',hozAlign:"left", headerTooltip:true,width:300},
      { title:"Sticker", field:'pregunta_21C',hozAlign:"left", headerTooltip:true,width:300},
      { title:"Video Pantalla", field:'pregunta_21D',hozAlign:"left", headerTooltip:true,width:300},
      { title:"Carta Informativa", field:'pregunta_21E',hozAlign:"left", headerTooltip:true,width:300},
      { title:"Cenefa", field:'pregunta_21F',hozAlign:"left", headerTooltip:true,width:300},
      { title:"Stopper", field:'pregunta_21G',hozAlign:"left", headerTooltip:true,width:300},
      { title:"Otro", field:'pregunta_21H',hozAlign:"left", headerTooltip:true,width:300},
    ],
  },
  {
    title:"¿Tiene algún incentivo de Aplazo?",
    columns:[
      { title:"Respuesta", field:'pregunta_22',hozAlign:"left", headerTooltip:true,width:300},
      { title:"Desarrollar Respuesta", field:'pregunta_23',hozAlign:"left", headerTooltip:true,width:300},
    ],
  },
  {
    title:"¿Tiene alguna promoción la tienda con Aplazo?",
    columns:[
      { title:"Respuesta", field:'pregunta_24',hozAlign:"left", headerTooltip:true,width:300},
      { title:"Desarrollar Respuesta", field:'pregunta_25',hozAlign:"left", headerTooltip:true,width:300},
    ],
  },
];
  
var columsTable3 = [
  {title:"Folio", field:'folio', hozAlign:"right", formatter:"link", formatterParams:{
  url:function(cell){return "https://app.linkaform.com/#/records/detail/" + cell.getData().record_id}, 
  target:"_blank",},  headerTooltip:true,width:100},
  { title:"Store ID", field:'store_id',hozAlign:"right", headerTooltip:true,width:200},
  { title:"Merchant", field:'merchant',hozAlign:"left", headerTooltip:true,width:300},
  { title:"Store", field:'store',hozAlign:"left", headerTooltip:true,width:300},
  { title:"Promotor", field:'promotor',hozAlign:"left", headerTooltip:true,width:300},
  { title:"Fecha", field:'fecha',hozAlign:"center", headerTooltip:true,width:150},
  { title:"Hora", field:'hora',hozAlign:"center", headerTooltip:true,width:150},

  { title:"¿La tienda cuenta con usuario y contraseña?", field:'pregunta_1',hozAlign:"left", headerTooltip:true,width:300},
  { title:"¿La tienda cuenta con el portal de cobro activo?", field:'pregunta_2',hozAlign:"left", headerTooltip:true,width:300},
  { title:"¿El personal de tienda esta debidamente enterado y capacitado de Código de pago?", field:'pregunta_3',hozAlign:"left", headerTooltip:true,width:300},
  { title:"¿La tienda ya cuenta con los datos de soporte telefónico servicio al cliente y tienda?", field:'pregunta_4',hozAlign:"left", headerTooltip:true,width:300},
  { title:"¿Vendedores están capacitados en proceso de cobro y qué es Kueski Pay?", field:'pregunta_5',hozAlign:"left", headerTooltip:true,width:300},
  { title:"¿Cajeros están capacitados en proceso de cobro y qué es Kueski Pay?", field:'pregunta_6',hozAlign:"left", headerTooltip:true,width:300},
  { title:"¿Gerente, subgerente, jefe de piso están capacitados en proceso de cobro y qué es Kueski Pay?", field:'pregunta_7',hozAlign:"left", headerTooltip:true,width:300},
  { title:"¿El personal de tienda esta debidamente enterado y capacitado de Downpayment?", field:'pregunta_8',hozAlign:"left", headerTooltip:true,width:300},
  { title:"¿El personal de tienda esta debidamente enterado y capacitado de cupón 10% de descuento para nuevos clientes?", field:'pregunta_9',hozAlign:"left", headerTooltip:true,width:300},
  {
    title:"¿En tu visita, ¿Qué obstáculos y/o retos tiene la tienda?",
    columns:[
      { title:"Clientes no les interesa Kueski Pay", field:'pregunta_10A',hozAlign:"left", headerTooltip:true,width:300},
      { title:"Vendedores no cuentan con capacitación", field:'pregunta_10B',hozAlign:"left", headerTooltip:true,width:300},
      { title:"Vendedores no ofrecen Kueski Pay", field:'pregunta_10C',hozAlign:"left", headerTooltip:true,width:300},
      { title:"Dar Beneficios de Kuesky Pay a Vendedores", field:'pregunta_10D',hozAlign:"left", headerTooltip:true,width:300},
      { title:"No tienen autorización de corporativo para ofrecer Kueski", field:'pregunta_10E',hozAlign:"left", headerTooltip:true,width:300},
      { title:"Otro", field:'pregunta_10F',hozAlign:"left", headerTooltip:true,width:300},
    ],
  },
  { title:"¿Numero telefonico de sucursal?", field:'pregunta_11',hozAlign:"left", headerTooltip:true,width:300},
  { title:"¿Cuál es el nombre del gerente de sucursal o encargado?", field:'pregunta_12',hozAlign:"left", headerTooltip:true,width:300},
  { title:"¿Cuál es el mail del gerente o encargado de sucursal?", field:'pregunta_13',hozAlign:"left", headerTooltip:true,width:300},
  { title:"¿Tuvo alguna promoción de Kueski el mes pasado?", field:'pregunta_14',hozAlign:"left", headerTooltip:true,width:300},
  { title:"¿La tienda cuenta con publicidad de Kueski?", field:'pregunta_15',hozAlign:"left", headerTooltip:true,width:300},
  { title:"Banner mini acrílico 4", field:'pregunta_16',hozAlign:"left", headerTooltip:true,width:300},
  { title:"Sticker para piso de venta negro", field:'pregunta_17',hozAlign:"left", headerTooltip:true,width:300},
  { title:"Sticker para piso de venta blanco QR", field:'pregunta_18',hozAlign:"left", headerTooltip:true,width:300},
  { title:"Sticker para piso de venta blanco", field:'pregunta_19',hozAlign:"left", headerTooltip:true,width:300},
  { title:"Sticker para piso de venta negro QR", field:'pregunta_20',hozAlign:"left", headerTooltip:true,width:300},
  { title:"Banner Mini Blanco", field:'pregunta_21',hozAlign:"left", headerTooltip:true,width:300},
  { title:"Banner Mini Negro", field:'pregunta_22',hozAlign:"left", headerTooltip:true,width:300},
  { title:"Banner Mini Generico", field:'pregunta_23',hozAlign:"left", headerTooltip:true,width:300},
  { title:"Sticker ventana 1", field:'pregunta_24',hozAlign:"left", headerTooltip:true,width:300},
  { title:"Sticker ventana piso de venta 1 QR", field:'pregunta_25',hozAlign:"left", headerTooltip:true,width:300},
  { title:"Sticker ventana piso de venta 2", field:'pregunta_26',hozAlign:"left", headerTooltip:true,width:300},
  { title:"Tentcard genérico 2023", field:'pregunta_27',hozAlign:"left", headerTooltip:true,width:300},
  { title:"Sticker genérico 2023", field:'pregunta_28',hozAlign:"left", headerTooltip:true,width:300},
  { title:"Tentcard 10% negro", field:'pregunta_29',hozAlign:"left", headerTooltip:true,width:300},
  { title:"Tentcard 10% azul", field:'pregunta_30',hozAlign:"left", headerTooltip:true,width:300},
  { title:"¿La tienda tiene promociones vigentes de la marca?", field:'pregunta_31',hozAlign:"left", headerTooltip:true,width:300},
  { title:"¿La tienda tuvo alguna promoción de la marca el mes pasado?", field:'pregunta_32',hozAlign:"left", headerTooltip:true,width:300},
  { title:"¿La tienda cuenta con cobro de Aplazo?", field:'pregunta_33',hozAlign:"left", headerTooltip:true,width:300},
  {
    title:"¿La tienda cuenta con publicidad de Aplazo?",
    columns:[
      { title:"No", field:'pregunta_34A',hozAlign:"left", headerTooltip:true,width:70},
      { title:"Banner", field:'pregunta_34B',hozAlign:"left", headerTooltip:true,width:100},
      { title:"Sticker", field:'pregunta_34C',hozAlign:"left", headerTooltip:true,width:100},
      { title:"Video Pantalla", field:'pregunta_34D',hozAlign:"left", headerTooltip:true,width:150},
      { title:"Carta Informativa", field:'pregunta_34E',hozAlign:"left", headerTooltip:true,width:200},
      { title:"Cenefa", field:'pregunta_34F',hozAlign:"left", headerTooltip:true,width:100},
      { title:"Stopper", field:'pregunta_34G',hozAlign:"left", headerTooltip:true,width:100},
      { title:"Otro", field:'pregunta_34H',hozAlign:"left", headerTooltip:true,width:70},
    ],
  },
  { title:"¿Tiene algún incentivo de Aplazo?", field:'pregunta_35',hozAlign:"left", headerTooltip:true,width:300},
  { title:"¿Tiene alguna promoción la tienda con Aplazo?", field:'pregunta_36',hozAlign:"left", headerTooltip:true,width:300},
  { title:"¿La tienda cuenta con publicidad de Aplazo?", field:'pregunta_37',hozAlign:"left", headerTooltip:true,width:300},
];