var columsTable1 = [
  {title:"Folio", field:'folio', hozAlign:"right", formatter:"link", formatterParams:{
  url:function(cell){return "https://app.linkaform.com/#/records/detail/" + cell.getData().record_id}, 
  target:"_blank",},  headerTooltip:true,width:100},
  { title:"Store ID", field:'store_id',hozAlign:"right", headerTooltip:true,width:200},
  { title:"Merchant", field:'merchant',hozAlign:"left", headerTooltip:true,width:300},
  { title:"Store", field:'store',hozAlign:"left", headerTooltip:true,width:300},
  { title:"Promotor", field:'promotor',hozAlign:"left", headerTooltip:true,width:300},
  { title:"Fecha", field:'fecha',hozAlign:"center", headerTooltip:true,width:150},
  { title:"Hora", field:'hora',hozAlign:"center", headerTooltip:true,width:150},

  { title:"Acceso al portal (usuario y contraseña)", field:'pregunta_1',hozAlign:"left", headerTooltip:true,width:300},
  { title:"Cómo el cliente crea su cuenta en KueskiPay ", field:'pregunta_2',hozAlign:"left", headerTooltip:true,width:300},
  { title:"Cómo el cliente usa KueskiPay para pagar  ", field:'pregunta_3',hozAlign:"left", headerTooltip:true,width:300},
  { title:"Como el vendedor/asesor usa KueskiPay para cobrar ", field:'pregunta_4',hozAlign:"left", headerTooltip:true,width:300},
  { title:"Términos y condiciones de las promociones vigentes", field:'pregunta_5',hozAlign:"left", headerTooltip:true,width:300},
  { title:"Cómo el cliente usa un cupón de descuento ", field:'pregunta_6',hozAlign:"left", headerTooltip:true,width:300},
  { title:"Ventajas competitivas, beneficios y características de KueskiPay  ", field:'pregunta_7',hozAlign:"left", headerTooltip:true,width:300},
  { title:"Compartir los datos de soporte telefónico ", field:'pregunta_8',hozAlign:"left", headerTooltip:true,width:300},
  { title:"Canales de comunicación oficiales (WA, correo, etc.)", field:'pregunta_9',hozAlign:"left", headerTooltip:true,width:300},
  { title:"¿Hay Material Publicitario de Kueski?", field:'pregunta_10',hozAlign:"left", headerTooltip:true,width:300},
  {
    title:"¿Dónde hay presencia de material de Kueski?",
    columns:[
      { title:"Piso de venta (mesas exhibición, paredes, espejos, etc)", field:'pregunta_11A',hozAlign:"left", headerTooltip:true,width:300},
      { title:"Portados por el personal (botones, gafetes, ropa, etc)", field:'pregunta_11B',hozAlign:"left", headerTooltip:true,width:300},
    ],
  },
  {
    title:"Material Publicitario Disponible de Kueski",
    columns:[
      { title:"Banner ( Cualquier tipo y Tamaño)", field:'pregunta_12A',hozAlign:"left", headerTooltip:true,width:300},
      { title:"Sticker ( Cualquier tipo y Tamaño)", field:'pregunta_12B',hozAlign:"left", headerTooltip:true,width:300},
      { title:"Lona ( Cualquier tipo y Tamaño)", field:'pregunta_12C',hozAlign:"left", headerTooltip:true,width:300},
      { title:"Pantalla", field:'pregunta_12D',hozAlign:"left", headerTooltip:true,width:300},
      { title:"Otro", field:'pregunta_12E',hozAlign:"left", headerTooltip:true,width:300},
    ],
  },
  { title:"¿Dejaste material publicitario?", field:'pregunta_13',hozAlign:"left", headerTooltip:true,width:300},
  { title:"¿Por que?", field:'pregunta_14',hozAlign:"left", headerTooltip:true,width:300},
  { title:"¿Hay material publicitario de aplazo?", field:'pregunta_15',hozAlign:"left", headerTooltip:true,width:300},
  { title:"¿Dónde hay presencia de material de aplazo?", field:'pregunta_16',hozAlign:"left", headerTooltip:true,width:300},
  { title:"Material publicitario disponible de aplazo", field:'pregunta_17',hozAlign:"left", headerTooltip:true,width:300},
  { title:"Describe las fallas o bugs que encontraste en tu visita y cómo se resolvieron Si no hubo ninguna omite esta pregunta", field:'pregunta_18',hozAlign:"left", headerTooltip:true,width:300},
  { title:"En tu visita, ¿Qué obstáculos y/o retos tiene la tienda?", field:'pregunta_19',hozAlign:"left", headerTooltip:true,width:300},
  { title:"Comparte tus comentarios adicionales", field:'pregunta_20',hozAlign:"left", headerTooltip:true,width:300},
];



var dataTable1 = [
  {
    "folio": "850-11702", 
    "record_id": "63eaed385a3ef7414d4899da", 
    "store_id": "1209250816961081402", 
    "merchant": "Calvin Klein Instore", 
    "store": "Ck Parque Lindavista", 
    "promotor": "Alberto Torres",
    "fecha": "2023-02-14", 
    "hora": " 08:08:45", 
    "pregunta_1": 'Tuve que capacitar desde cero',
    "pregunta_2": 'Resolvi unas cuantas dudas',
    "pregunta_3": 'El staff de la tienda domina el tema o no tiene problemas',
    "pregunta_4": 'Resolvi unas cuantas dudas',
    "pregunta_5": 'El staff de la tienda domina el tema o no tiene problemas',
    "pregunta_6": 'Tuve que capacitar desde cero',
    "pregunta_7": 'Tuve que capacitar desde cero',
    "pregunta_8": 'Resolvi unas cuantas dudas',
    "pregunta_9": 'Resolvi unas cuantas dudas',
    "pregunta_10": 'Sí',
    "pregunta_11A": 'En caja',
    "pregunta_11B": '',
    "pregunta_12A": 'Banner ( Cualquier tipo y Tamaño)',
    "pregunta_12B": '',
    "pregunta_12C": '',
    "pregunta_12D": '',
    "pregunta_12E": '',
    "pregunta_13": 'Sí',
    "pregunta_14": 'No contaba con Material',
    "pregunta_15": 'Sí',
    "pregunta_16": 'Entrada',
    "pregunta_17": 'Lona (cualquier tipo tipo y tamaño)',
    "pregunta_18": 'Comentario de ejemplo',
    "pregunta_19": 'Comentario de ejemplo',
    "pregunta_20": 'Comentario de ejemplo',
  }, 
    {
    "folio": "850-11702", 
    "record_id": "63eaed385a3ef7414d4899da", 
    "store_id": "1209250816961081402", 
    "merchant": "Calvin Klein Instore", 
    "store": "Ck Parque Lindavista", 
    "promotor": "Alberto Torres",
    "fecha": "2023-02-14", 
    "hora": " 08:08:45", 
    "pregunta_1": 'Tuve que capacitar desde cero',
    "pregunta_2": 'Resolvi unas cuantas dudas',
    "pregunta_3": 'El staff de la tienda domina el tema o no tiene problemas',
    "pregunta_4": 'Resolvi unas cuantas dudas',
    "pregunta_5": 'El staff de la tienda domina el tema o no tiene problemas',
    "pregunta_6": 'Tuve que capacitar desde cero',
    "pregunta_7": 'Tuve que capacitar desde cero',
    "pregunta_8": 'Resolvi unas cuantas dudas',
    "pregunta_9": 'Resolvi unas cuantas dudas',
    "pregunta_10": 'Sí',
    "pregunta_11A": 'En caja',
    "pregunta_11B": '',
    "pregunta_11C": '',
    "pregunta_11D": '',
    "pregunta_11E": '',
    "pregunta_12A": 'Banner ( Cualquier tipo y Tamaño)',
    "pregunta_12B": '',
    "pregunta_12C": '',
    "pregunta_12D": '',
    "pregunta_12E": '',
    "pregunta_13": 'Sí',
    "pregunta_14": 'No contaba con Material',
    "pregunta_15": 'Sí',
    "pregunta_16": 'Entrada',
    "pregunta_17": 'Lona (cualquier tipo tipo y tamaño)',
    "pregunta_18": 'Comentario de ejemplo',
    "pregunta_19": 'Comentario de ejemplo',
    "pregunta_20": 'Comentario de ejemplo',
  }, 
    {
    "folio": "850-11702", 
    "record_id": "63eaed385a3ef7414d4899da", 
    "store_id": "1209250816961081402", 
    "merchant": "Calvin Klein Instore", 
    "store": "Ck Parque Lindavista", 
    "promotor": "Alberto Torres",
    "fecha": "2023-02-14", 
    "hora": " 08:08:45", 
    "pregunta_1": 'Tuve que capacitar desde cero',
    "pregunta_2": 'Resolvi unas cuantas dudas',
    "pregunta_3": 'El staff de la tienda domina el tema o no tiene problemas',
    "pregunta_4": 'Resolvi unas cuantas dudas',
    "pregunta_5": 'El staff de la tienda domina el tema o no tiene problemas',
    "pregunta_6": 'Tuve que capacitar desde cero',
    "pregunta_7": 'Tuve que capacitar desde cero',
    "pregunta_8": 'Resolvi unas cuantas dudas',
    "pregunta_9": 'Resolvi unas cuantas dudas',
    "pregunta_10": 'Sí',
    "pregunta_11A": 'En caja',
    "pregunta_11B": '',
    "pregunta_11C": '',
    "pregunta_11D": '',
    "pregunta_11E": '',
    "pregunta_12A": 'Banner ( Cualquier tipo y Tamaño)',
    "pregunta_12B": '',
    "pregunta_12C": '',
    "pregunta_12D": '',
    "pregunta_12E": '',
    "pregunta_13": 'Sí',
    "pregunta_14": 'No contaba con Material',
    "pregunta_15": 'Sí',
    "pregunta_16": 'Entrada',
    "pregunta_17": 'Lona (cualquier tipo tipo y tamaño)',
    "pregunta_18": 'Comentario de ejemplo',
    "pregunta_19": 'Comentario de ejemplo',
    "pregunta_20": 'Comentario de ejemplo',
  }, 
  {
    "folio": "850-11702", 
    "record_id": "63eaed385a3ef7414d4899da", 
    "store_id": "1209250816961081402", 
    "merchant": "Calvin Klein Instore", 
    "store": "Ck Parque Lindavista", 
    "promotor": "Alberto Torres",
    "fecha": "2023-02-14", 
    "hora": " 08:08:45", 
    "pregunta_1": 'Tuve que capacitar desde cero',
    "pregunta_2": 'Resolvi unas cuantas dudas',
    "pregunta_3": 'El staff de la tienda domina el tema o no tiene problemas',
    "pregunta_4": 'Resolvi unas cuantas dudas',
    "pregunta_5": 'El staff de la tienda domina el tema o no tiene problemas',
    "pregunta_6": 'Tuve que capacitar desde cero',
    "pregunta_7": 'Tuve que capacitar desde cero',
    "pregunta_8": 'Resolvi unas cuantas dudas',
    "pregunta_9": 'Resolvi unas cuantas dudas',
    "pregunta_10": 'Sí',
    "pregunta_11A": 'En caja',
    "pregunta_11B": '',
    "pregunta_11C": '',
    "pregunta_11D": '',
    "pregunta_11E": '',
    "pregunta_12A": 'Banner ( Cualquier tipo y Tamaño)',
    "pregunta_12B": '',
    "pregunta_12C": '',
    "pregunta_12D": '',
    "pregunta_12E": '',
    "pregunta_13": 'Sí',
    "pregunta_14": 'No contaba con Material',
    "pregunta_15": 'Sí',
    "pregunta_16": 'Entrada',
    "pregunta_17": 'Lona (cualquier tipo tipo y tamaño)',
    "pregunta_18": 'Comentario de ejemplo',
    "pregunta_19": 'Comentario de ejemplo',
    "pregunta_20": 'Comentario de ejemplo',
  }, 
  {
    "folio": "850-11702", 
    "record_id": "63eaed385a3ef7414d4899da", 
    "store_id": "1209250816961081402", 
    "merchant": "Calvin Klein Instore", 
    "store": "Ck Parque Lindavista", 
    "promotor": "Alberto Torres",
    "fecha": "2023-02-14", 
    "hora": " 08:08:45", 
    "pregunta_1": 'Tuve que capacitar desde cero',
    "pregunta_2": 'Resolvi unas cuantas dudas',
    "pregunta_3": 'El staff de la tienda domina el tema o no tiene problemas',
    "pregunta_4": 'Resolvi unas cuantas dudas',
    "pregunta_5": 'El staff de la tienda domina el tema o no tiene problemas',
    "pregunta_6": 'Tuve que capacitar desde cero',
    "pregunta_7": 'Tuve que capacitar desde cero',
    "pregunta_8": 'Resolvi unas cuantas dudas',
    "pregunta_9": 'Resolvi unas cuantas dudas',
    "pregunta_10": 'Sí',
    "pregunta_11A": 'En caja',
    "pregunta_11B": '',
    "pregunta_11C": '',
    "pregunta_11D": '',
    "pregunta_11E": '',
    "pregunta_12A": 'Banner ( Cualquier tipo y Tamaño)',
    "pregunta_12B": '',
    "pregunta_12C": '',
    "pregunta_12D": '',
    "pregunta_12E": '',
    "pregunta_13": 'Sí',
    "pregunta_14": 'No contaba con Material',
    "pregunta_15": 'Sí',
    "pregunta_16": 'Entrada',
    "pregunta_17": 'Lona (cualquier tipo tipo y tamaño)',
    "pregunta_18": 'Comentario de ejemplo',
    "pregunta_19": 'Comentario de ejemplo',
    "pregunta_20": 'Comentario de ejemplo',
  }, 
  {
    "folio": "850-11702", 
    "record_id": "63eaed385a3ef7414d4899da", 
    "store_id": "1209250816961081402", 
    "merchant": "Calvin Klein Instore", 
    "store": "Ck Parque Lindavista", 
    "promotor": "Alberto Torres",
    "fecha": "2023-02-14", 
    "hora": " 08:08:45", 
    "pregunta_1": 'Tuve que capacitar desde cero',
    "pregunta_2": 'Resolvi unas cuantas dudas',
    "pregunta_3": 'El staff de la tienda domina el tema o no tiene problemas',
    "pregunta_4": 'Resolvi unas cuantas dudas',
    "pregunta_5": 'El staff de la tienda domina el tema o no tiene problemas',
    "pregunta_6": 'Tuve que capacitar desde cero',
    "pregunta_7": 'Tuve que capacitar desde cero',
    "pregunta_8": 'Resolvi unas cuantas dudas',
    "pregunta_9": 'Resolvi unas cuantas dudas',
    "pregunta_10": 'Sí',
    "pregunta_11A": 'En caja',
    "pregunta_11B": '',
    "pregunta_11C": '',
    "pregunta_11D": '',
    "pregunta_11E": '',
    "pregunta_12A": 'Banner ( Cualquier tipo y Tamaño)',
    "pregunta_12B": '',
    "pregunta_12C": '',
    "pregunta_12D": '',
    "pregunta_12E": '',
    "pregunta_13": 'Sí',
    "pregunta_14": 'No contaba con Material',
    "pregunta_15": 'Sí',
    "pregunta_16": 'Entrada',
    "pregunta_17": 'Lona (cualquier tipo tipo y tamaño)',
    "pregunta_18": 'Comentario de ejemplo',
    "pregunta_19": 'Comentario de ejemplo',
    "pregunta_20": 'Comentario de ejemplo',
  }, 
  {
    "folio": "850-11702", 
    "record_id": "63eaed385a3ef7414d4899da", 
    "store_id": "1209250816961081402", 
    "merchant": "Calvin Klein Instore", 
    "store": "Ck Parque Lindavista", 
    "promotor": "Alberto Torres",
    "fecha": "2023-02-14", 
    "hora": " 08:08:45", 
    "pregunta_1": 'Tuve que capacitar desde cero',
    "pregunta_2": 'Resolvi unas cuantas dudas',
    "pregunta_3": 'El staff de la tienda domina el tema o no tiene problemas',
    "pregunta_4": 'Resolvi unas cuantas dudas',
    "pregunta_5": 'El staff de la tienda domina el tema o no tiene problemas',
    "pregunta_6": 'Tuve que capacitar desde cero',
    "pregunta_7": 'Tuve que capacitar desde cero',
    "pregunta_8": 'Resolvi unas cuantas dudas',
    "pregunta_9": 'Resolvi unas cuantas dudas',
    "pregunta_10": 'Sí',
    "pregunta_11A": 'En caja',
    "pregunta_11B": '',
    "pregunta_11C": '',
    "pregunta_11D": '',
    "pregunta_11E": '',
    "pregunta_12A": 'Banner ( Cualquier tipo y Tamaño)',
    "pregunta_12B": '',
    "pregunta_12C": '',
    "pregunta_12D": '',
    "pregunta_12E": '',
    "pregunta_13": 'Sí',
    "pregunta_14": 'No contaba con Material',
    "pregunta_15": 'Sí',
    "pregunta_16": 'Entrada',
    "pregunta_17": 'Lona (cualquier tipo tipo y tamaño)',
    "pregunta_18": 'Comentario de ejemplo',
    "pregunta_19": 'Comentario de ejemplo',
    "pregunta_20": 'Comentario de ejemplo',
  }, 
  {
    "folio": "850-11702", 
    "record_id": "63eaed385a3ef7414d4899da", 
    "store_id": "1209250816961081402", 
    "merchant": "Calvin Klein Instore", 
    "store": "Ck Parque Lindavista", 
    "promotor": "Alberto Torres",
    "fecha": "2023-02-14", 
    "hora": " 08:08:45", 
    "pregunta_1": 'Tuve que capacitar desde cero',
    "pregunta_2": 'Resolvi unas cuantas dudas',
    "pregunta_3": 'El staff de la tienda domina el tema o no tiene problemas',
    "pregunta_4": 'Resolvi unas cuantas dudas',
    "pregunta_5": 'El staff de la tienda domina el tema o no tiene problemas',
    "pregunta_6": 'Tuve que capacitar desde cero',
    "pregunta_7": 'Tuve que capacitar desde cero',
    "pregunta_8": 'Resolvi unas cuantas dudas',
    "pregunta_9": 'Resolvi unas cuantas dudas',
    "pregunta_10": 'Sí',
    "pregunta_11A": 'En caja',
    "pregunta_11B": '',
    "pregunta_11C": '',
    "pregunta_11D": '',
    "pregunta_11E": '',
    "pregunta_12A": 'Banner ( Cualquier tipo y Tamaño)',
    "pregunta_12B": '',
    "pregunta_12C": '',
    "pregunta_12D": '',
    "pregunta_12E": '',
    "pregunta_13": 'Sí',
    "pregunta_14": 'No contaba con Material',
    "pregunta_15": 'Sí',
    "pregunta_16": 'Entrada',
    "pregunta_17": 'Lona (cualquier tipo tipo y tamaño)',
    "pregunta_18": 'Comentario de ejemplo',
    "pregunta_19": 'Comentario de ejemplo',
    "pregunta_20": 'Comentario de ejemplo',
  }, 
  {
    "folio": "850-11702", 
    "record_id": "63eaed385a3ef7414d4899da", 
    "store_id": "1209250816961081402", 
    "merchant": "Calvin Klein Instore", 
    "store": "Ck Parque Lindavista", 
    "promotor": "Alberto Torres",
    "fecha": "2023-02-14", 
    "hora": " 08:08:45", 
    "pregunta_1": 'Tuve que capacitar desde cero',
    "pregunta_2": 'Resolvi unas cuantas dudas',
    "pregunta_3": 'El staff de la tienda domina el tema o no tiene problemas',
    "pregunta_4": 'Resolvi unas cuantas dudas',
    "pregunta_5": 'El staff de la tienda domina el tema o no tiene problemas',
    "pregunta_6": 'Tuve que capacitar desde cero',
    "pregunta_7": 'Tuve que capacitar desde cero',
    "pregunta_8": 'Resolvi unas cuantas dudas',
    "pregunta_9": 'Resolvi unas cuantas dudas',
    "pregunta_10": 'Sí',
    "pregunta_11A": 'En caja',
    "pregunta_11B": '',
    "pregunta_11C": '',
    "pregunta_11D": '',
    "pregunta_11E": '',
    "pregunta_12A": 'Banner ( Cualquier tipo y Tamaño)',
    "pregunta_12B": '',
    "pregunta_12C": '',
    "pregunta_12D": '',
    "pregunta_12E": '',
    "pregunta_13": 'Sí',
    "pregunta_14": 'No contaba con Material',
    "pregunta_15": 'Sí',
    "pregunta_16": 'Entrada',
    "pregunta_17": 'Lona (cualquier tipo tipo y tamaño)',
    "pregunta_18": 'Comentario de ejemplo',
    "pregunta_19": 'Comentario de ejemplo',
    "pregunta_20": 'Comentario de ejemplo',
  }, 
  {
    "folio": "850-11702", 
    "record_id": "63eaed385a3ef7414d4899da", 
    "store_id": "1209250816961081402", 
    "merchant": "Calvin Klein Instore", 
    "store": "Ck Parque Lindavista", 
    "promotor": "Alberto Torres",
    "fecha": "2023-02-14", 
    "hora": " 08:08:45", 
    "pregunta_1": 'Tuve que capacitar desde cero',
    "pregunta_2": 'Resolvi unas cuantas dudas',
    "pregunta_3": 'El staff de la tienda domina el tema o no tiene problemas',
    "pregunta_4": 'Resolvi unas cuantas dudas',
    "pregunta_5": 'El staff de la tienda domina el tema o no tiene problemas',
    "pregunta_6": 'Tuve que capacitar desde cero',
    "pregunta_7": 'Tuve que capacitar desde cero',
    "pregunta_8": 'Resolvi unas cuantas dudas',
    "pregunta_9": 'Resolvi unas cuantas dudas',
    "pregunta_10": 'Sí',
    "pregunta_11A": 'En caja',
    "pregunta_11B": '',
    "pregunta_11C": '',
    "pregunta_11D": '',
    "pregunta_11E": '',
    "pregunta_12A": 'Banner ( Cualquier tipo y Tamaño)',
    "pregunta_12B": '',
    "pregunta_12C": '',
    "pregunta_12D": '',
    "pregunta_12E": '',
    "pregunta_13": 'Sí',
    "pregunta_14": 'No contaba con Material',
    "pregunta_15": 'Sí',
    "pregunta_16": 'Entrada',
    "pregunta_17": 'Lona (cualquier tipo tipo y tamaño)',
    "pregunta_18": 'Comentario de ejemplo',
    "pregunta_19": 'Comentario de ejemplo',
    "pregunta_20": 'Comentario de ejemplo',
  }, 
  {
    "folio": "850-11702", 
    "record_id": "63eaed385a3ef7414d4899da", 
    "store_id": "1209250816961081402", 
    "merchant": "Calvin Klein Instore", 
    "store": "Ck Parque Lindavista", 
    "promotor": "Alberto Torres",
    "fecha": "2023-02-14", 
    "hora": " 08:08:45", 
    "pregunta_1": 'Tuve que capacitar desde cero',
    "pregunta_2": 'Resolvi unas cuantas dudas',
    "pregunta_3": 'El staff de la tienda domina el tema o no tiene problemas',
    "pregunta_4": 'Resolvi unas cuantas dudas',
    "pregunta_5": 'El staff de la tienda domina el tema o no tiene problemas',
    "pregunta_6": 'Tuve que capacitar desde cero',
    "pregunta_7": 'Tuve que capacitar desde cero',
    "pregunta_8": 'Resolvi unas cuantas dudas',
    "pregunta_9": 'Resolvi unas cuantas dudas',
    "pregunta_10": 'Sí',
    "pregunta_11A": 'En caja',
    "pregunta_11B": '',
    "pregunta_11C": '',
    "pregunta_11D": '',
    "pregunta_11E": '',
    "pregunta_12A": 'Banner ( Cualquier tipo y Tamaño)',
    "pregunta_12B": '',
    "pregunta_12C": '',
    "pregunta_12D": '',
    "pregunta_12E": '',
    "pregunta_13": 'Sí',
    "pregunta_14": 'No contaba con Material',
    "pregunta_15": 'Sí',
    "pregunta_16": 'Entrada',
    "pregunta_17": 'Lona (cualquier tipo tipo y tamaño)',
    "pregunta_18": 'Comentario de ejemplo',
    "pregunta_19": 'Comentario de ejemplo',
    "pregunta_20": 'Comentario de ejemplo',
  },   

];





  



 

